-- Domain: demo | Mode: 3nf | Seed: 7
-- Generated by Shape v0.9.1

-- ============================================================
-- Table: item
-- ============================================================

DROP TABLE IF EXISTS [dbo].[item];
GO
-- NOTE: Fabric Warehouse does not enforce PRIMARY KEY constraints;
-- [id] is the logical primary key.
CREATE TABLE [dbo].[item] (
    [id]                           BIGINT               NOT NULL,
    [name]                         VARCHAR(40)          NULL,
    [price]                        DECIMAL(10,2)        NOT NULL,
    [ratio]                        FLOAT                NULL,
    [active]                       BIT                  NOT NULL,
    [born]                         DATE                 NULL,
    [seen]                         DATETIME2(6)         NULL
);
GO

INSERT INTO [dbo].[item] ([id], [name], [price], [ratio], [active], [born], [seen])
VALUES
  (1, 'plain', 1.50, 0.5, 1, '2020-02-29', '2025-01-02 03:04:05.678000'),
  (2, 'O''Brien \ é', 0.00, NULL, 0, NULL, NULL);
GO

INSERT INTO [dbo].[item] ([id], [name], [price], [ratio], [active], [born], [seen])
VALUES
  (3, NULL, 12345.67, 2.0, 1, '1999-12-31', '2025-12-31 23:59:59');
GO

