-- Domain: demo | Mode: 3nf | Seed: 7
-- Generated by Shape v0.9.1

-- ============================================================
-- Table: item
-- ============================================================

IF OBJECT_ID('[dbo].[item]', 'U') IS NOT NULL
    DROP TABLE [dbo].[item];
GO
CREATE TABLE [dbo].[item] (
    [id]                           BIGINT               NOT NULL,
    [name]                         NVARCHAR(40)         NULL,
    [price]                        DECIMAL(10,2)        NOT NULL,
    [ratio]                        FLOAT                NULL,
    [active]                       BIT                  NOT NULL,
    [born]                         DATE                 NULL,
    [seen]                         DATETIME2            NULL,
    CONSTRAINT [PK_item] PRIMARY KEY ([id])
);
GO

INSERT INTO [dbo].[item] ([id], [name], [price], [ratio], [active], [born], [seen])
VALUES
  (1, N'plain', 1.50, 0.5, 1, N'2020-02-29', N'2025-01-02 03:04:05.678000'),
  (2, N'O''Brien \ é', 0.00, NULL, 0, NULL, NULL);
GO

INSERT INTO [dbo].[item] ([id], [name], [price], [ratio], [active], [born], [seen])
VALUES
  (3, NULL, 12345.67, 2.0, 1, N'1999-12-31', N'2025-12-31 23:59:59');
GO

