-- Domain: demo | Mode: 3nf | Seed: 7
-- Generated by Shape v0.9.0

-- ============================================================
-- Table: item
-- ============================================================

DROP TABLE IF EXISTS "dbo"."item" CASCADE;

CREATE TABLE "dbo"."item" (
    "id"                           BIGINT               NOT NULL,
    "name"                         VARCHAR(40)          NULL,
    "price"                        NUMERIC(10,2)        NOT NULL,
    "ratio"                        DOUBLE PRECISION     NULL,
    "active"                       BOOLEAN              NOT NULL,
    "born"                         DATE                 NULL,
    "seen"                         TIMESTAMP            NULL,
    CONSTRAINT "PK_item" PRIMARY KEY ("id")
);

INSERT INTO "dbo"."item" ("id", "name", "price", "ratio", "active", "born", "seen")
VALUES
  (1, 'plain', 1.50, 0.5, TRUE, '2020-02-29', '2025-01-02 03:04:05.678000'),
  (2, 'O''Brien \ é', 0.00, NULL, FALSE, NULL, NULL);

INSERT INTO "dbo"."item" ("id", "name", "price", "ratio", "active", "born", "seen")
VALUES
  (3, NULL, 12345.67, 2.0, TRUE, '1999-12-31', '2025-12-31 23:59:59');

