"""Offline lockfiles: declared dependency sets, and the check of a lock against them."""

import importlib.util
import sys
import textwrap
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
_spec = importlib.util.spec_from_file_location("offline_lock", ROOT / "scripts" / "offline_lock.py")
assert _spec and _spec.loader
offline_lock = importlib.util.module_from_spec(_spec)
sys.modules["offline_lock"] = offline_lock
_spec.loader.exec_module(offline_lock)

H = "sha256:" + "a" * 64


def _lock(*entries: str) -> str:
    return "\n".join(entries) + "\n"


def _entry(name: str, version: str, hashes: int = 1) -> str:
    lines = [f"{name}=={version} \\"]
    hs = [f"    --hash={H}"] * hashes
    return "\n".join([lines[0], " \\\n".join(hs)])


def test_declared_sets_cover_core_and_every_extra():
    sets = offline_lock.declared_sets(ROOT)
    assert "core" in sets
    assert {"yaml", "sign", "delta", "excel", "azure", "kafka", "dev"} <= set(sets)
    core = {offline_lock.canonical(r.name) for r in sets["core"]}
    assert {"numpy", "pyarrow"} <= core


def test_every_extra_set_contains_core():
    sets = offline_lock.declared_sets(ROOT)
    core = {offline_lock.canonical(r.name) for r in sets["core"]}
    for name, reqs in sets.items():
        names = {offline_lock.canonical(r.name) for r in reqs}
        assert core <= names, name


def test_first_party_extras_expand_to_third_party_dependencies():
    sets = offline_lock.declared_sets(ROOT)
    names = {offline_lock.canonical(r.name) for r in sets["kafka"]}
    assert "confluent-kafka" in names
    assert not any(n.startswith("sqllocks-shape") for n in names)


def test_first_party_extras_carry_their_plugin_extras():
    # #259: "sqllocks-shape-databases[postgres]" needs the plugin's postgres driver too
    sets = offline_lock.declared_sets(ROOT)
    names = {k: {offline_lock.canonical(r.name) for r in v} for k, v in sets.items()}
    assert "psycopg" in names["postgres"] and "pymysql" not in names["postgres"]
    assert "pymysql" in names["mysql"] and "psycopg" not in names["mysql"]
    assert {"psycopg", "pymysql"} <= names["databases"]


def test_check_passes_for_a_matching_lock(tmp_path):
    reqs = [offline_lock.parse_requirement("numpy>=2.0,<3")]
    lock = _lock(_entry("numpy", "2.1.0"))
    assert offline_lock.check_lock(lock, reqs) == []


def test_check_rejects_missing_package():
    reqs = [
        offline_lock.parse_requirement("numpy>=2.0,<3"),
        offline_lock.parse_requirement("pyarrow>=14"),
    ]
    problems = offline_lock.check_lock(_lock(_entry("numpy", "2.1.0")), reqs)
    assert any("pyarrow" in p and "missing" in p for p in problems)


def test_check_rejects_version_outside_declared_range():
    reqs = [offline_lock.parse_requirement("numpy>=2.0,<3")]
    problems = offline_lock.check_lock(_lock(_entry("numpy", "3.0.0")), reqs)
    assert any("numpy" in p and "3.0.0" in p for p in problems)


def test_check_boundary_versions():
    reqs = [offline_lock.parse_requirement("numpy>=2.0,<3")]
    assert offline_lock.check_lock(_lock(_entry("numpy", "2.0")), reqs) == []
    assert offline_lock.check_lock(_lock(_entry("numpy", "2.99.9")), reqs) == []
    assert offline_lock.check_lock(_lock(_entry("numpy", "1.99.9")), reqs)


def test_check_rejects_unhashed_entry():
    reqs = [offline_lock.parse_requirement("numpy>=2.0,<3")]
    problems = offline_lock.check_lock("numpy==2.1.0\n", reqs)
    assert any("hash" in p for p in problems)


def test_check_rejects_unpinned_entry():
    reqs = [offline_lock.parse_requirement("numpy>=2.0,<3")]
    problems = offline_lock.check_lock(f"numpy>=2.0 \\\n    --hash={H}\n", reqs)
    assert any("pinned" in p for p in problems)


def test_check_names_are_normalised():
    reqs = [offline_lock.parse_requirement("Confluent_Kafka>=2.5,<4")]
    assert offline_lock.check_lock(_lock(_entry("confluent-kafka", "2.6.0")), reqs) == []


def test_check_ignores_requirements_whose_marker_is_false_here():
    reqs = [offline_lock.parse_requirement("tzdata; sys_platform == 'nowhere'")]
    assert offline_lock.check_lock("", reqs) == []


def test_check_accepts_markers_and_comments_in_lock():
    text = textwrap.dedent(
        f"""\
        # This file was autogenerated
        numpy==2.1.0 ; python_version >= '3.11' \\
            --hash={H} \\
            --hash={H}
            # via sqllocks-shape
        """
    )
    assert offline_lock.check_lock(text, [offline_lock.parse_requirement("numpy>=2")]) == []


def test_check_directory_reports_missing_lock_file(tmp_path):
    problems = offline_lock.check_directory(tmp_path, ROOT)
    assert any("core" in p for p in problems)


def test_check_directory_passes_with_matching_locks(tmp_path):
    sets = offline_lock.declared_sets(ROOT)
    for name, reqs in sets.items():
        entries = []
        for r in reqs:
            ver = offline_lock.sample_version(r)
            entries.append(_entry(r.name, ver))
        (tmp_path / offline_lock.lock_name(name)).write_text(_lock(*entries))
    assert offline_lock.check_directory(tmp_path, ROOT) == []


@pytest.mark.parametrize("bad", ["tzdata", "pyarrow"])
def test_check_directory_flags_dropped_dependency(tmp_path, bad):
    sets = offline_lock.declared_sets(ROOT)
    for name, reqs in sets.items():
        entries = [
            _entry(r.name, offline_lock.sample_version(r))
            for r in reqs
            if not (name == "core" and offline_lock.canonical(r.name) == bad)
        ]
        (tmp_path / offline_lock.lock_name(name)).write_text(_lock(*entries))
    problems = offline_lock.check_directory(tmp_path, ROOT)
    # A universal lock covers every platform (docs/INSTALL.md): tzdata is Windows-only, but the lock
    # must still carry it, so dropping it is a finding on any host.
    assert any(bad in p for p in problems)


def test_first_party_extras_keep_the_plugin_extras_they_ask_for():
    """#259: `sqllocks-shape-databases[postgres]` brings the plugin's `postgres` extra."""
    sets = offline_lock.declared_sets(ROOT)
    names = {k: {offline_lock.canonical(r.name) for r in sets[k]} for k in sets}
    assert "psycopg" in names["postgres"]
    assert "pymysql" in names["mysql"]
    assert {"psycopg", "pymysql"} <= names["databases"]


def test_core_extras_named_by_a_plugin_are_expanded(tmp_path):
    """A plugin that asks for `sqllocks-shape[azure]` brings core's `azure` extra."""
    (tmp_path / "plugins" / "p").mkdir(parents=True)
    (tmp_path / "pyproject.toml").write_text(
        textwrap.dedent(
            """\
            [project]
            name = "sqllocks-shape"
            dependencies = ["numpy>=2"]
            [project.optional-dependencies]
            azure = ["adlfs>=2024.4.1"]
            p = ["sqllocks-shape-p[cloud]==0.9.0"]
            """
        )
    )
    (tmp_path / "plugins" / "p" / "pyproject.toml").write_text(
        textwrap.dedent(
            """\
            [project]
            name = "sqllocks-shape-p"
            dependencies = ["sqllocks-shape==0.9.0", "requests>=2"]
            [project.optional-dependencies]
            cloud = ["sqllocks-shape[azure]==0.9.0", "boto3>=1"]
            """
        )
    )
    sets = offline_lock.declared_sets(tmp_path)
    assert sorted(offline_lock.canonical(r.name) for r in sets["p"]) == [
        "adlfs",
        "boto3",
        "numpy",
        "requests",
    ]


def test_check_requires_marked_dependency_that_holds_on_some_supported_platform():
    reqs = [offline_lock.parse_requirement("tzdata; sys_platform == 'win32'")]
    assert any("tzdata" in p for p in offline_lock.check_lock("", reqs))


def test_check_requires_dependency_marked_for_one_python_only():
    reqs = [offline_lock.parse_requirement("backports; python_version == '3.14'")]
    assert any("backports" in p for p in offline_lock.check_lock("", reqs))
