"""W5-10 item 2: which local tools keep ``shape.fingerprint`` when they read and rewrite a file.

Each scenario rewrites a fingerprinted file or table with one tool and records whether the
fingerprint survives. The results are the table in ``docs/FINGERPRINT.md`` between the markers
below: this module renders it, and running it with ``SHAPE_UPDATE_DOCS=1`` rewrites the block.
Without that variable the test fails when the committed table differs from what the tools do
today, so the documentation cannot drift from the run.
"""

from __future__ import annotations

import os
import shutil
from collections.abc import Callable
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq
import pytest

from shape import fingerprint

DOC = Path(__file__).parents[2] / "docs" / "FINGERPRINT.md"
BEGIN = (
    "<!-- preservation-table:begin (generated by tests/w5_10/test_fingerprint_preservation.py) -->"
)
END = "<!-- preservation-table:end -->"
SURVIVES, LOST, NOT_RUN = "survives", "lost", "not run"

TABLE = pa.table({"id": pa.array([1, 2, 3], pa.int64()), "name": ["a", "b", "c"]})


def _fingerprinted_parquet(tmp: Path) -> Path:
    path = tmp / "src.parquet"
    pq.write_table(TABLE, path)
    doc = fingerprint.build("t", TABLE, dataset_id="sha256:x", reproducibility={"seed": 1})
    fingerprint.embed_text(path, fingerprint.dump(doc))
    return path


def _fingerprinted_delta(tmp: Path) -> Path:
    deltalake = pytest.importorskip("deltalake")
    path = tmp / "src_delta"
    deltalake.write_deltalake(str(path), TABLE)
    doc = fingerprint.build("t", TABLE, dataset_id="sha256:x", reproducibility={"seed": 1})
    fingerprint.embed_text(path, fingerprint.dump(doc))
    return path


def _kept(path: Path) -> str:
    return SURVIVES if fingerprint.read_text(path) is not None else LOST


# ---- scenarios: (tool, operation, input kind, function(tmp) -> result) -----------------------


def pyarrow_roundtrip(tmp: Path) -> str:
    src = _fingerprinted_parquet(tmp)
    out = tmp / "out.parquet"
    pq.write_table(pq.read_table(src), out)
    return _kept(out)


def pyarrow_columns_only(tmp: Path) -> str:
    src = _fingerprinted_parquet(tmp)
    out = tmp / "out.parquet"
    pq.write_table(pq.read_table(src, columns=["id"]), out)
    return _kept(out)


def pyarrow_new_schema(tmp: Path) -> str:
    src = _fingerprinted_parquet(tmp)
    out = tmp / "out.parquet"
    table = pq.read_table(src)
    with pq.ParquetWriter(out, pa.schema(list(table.schema))) as writer:
        writer.write_table(table)
    return _kept(out)


def pyarrow_dataset_write(tmp: Path) -> str:
    import pyarrow.dataset as ds

    src = _fingerprinted_parquet(tmp)
    out = tmp / "ds"
    ds.write_dataset(ds.dataset(src), out, format="parquet")
    return _kept(next(out.glob("*.parquet")))


def pandas_roundtrip(tmp: Path) -> str:
    pytest.importorskip("pandas")
    src = _fingerprinted_parquet(tmp)
    out = tmp / "out.parquet"
    pa_table = pa.Table.from_pandas(pq.read_table(src).to_pandas())
    pq.write_table(pa_table, out)
    return _kept(out)


def duckdb_copy_parquet(tmp: Path) -> str:
    duckdb = pytest.importorskip("duckdb")
    src = _fingerprinted_parquet(tmp)
    out = tmp / "out.parquet"
    duckdb.sql(f"COPY (SELECT * FROM read_parquet('{src}')) TO '{out}' (FORMAT PARQUET)")
    return _kept(out)


def duckdb_copy_with_kv_metadata(tmp: Path) -> str:
    duckdb = pytest.importorskip("duckdb")
    src = _fingerprinted_parquet(tmp)
    out = tmp / "out.parquet"
    text = fingerprint.read_text(src)
    assert text is not None
    quoted = text.replace("'", "''")
    duckdb.sql(
        f"COPY (SELECT * FROM read_parquet('{src}')) TO '{out}' "
        f"(FORMAT PARQUET, KV_METADATA {{'shape.fingerprint': '{quoted}'}})"
    )
    return _kept(out)


def duckdb_reads_parquet_metadata(tmp: Path) -> str:
    duckdb = pytest.importorskip("duckdb")
    src = _fingerprinted_parquet(tmp)
    rows = duckdb.sql(f"SELECT key FROM parquet_kv_metadata('{src}')").fetchall()
    return (
        SURVIVES if any(r[0] in (b"shape.fingerprint", "shape.fingerprint") for r in rows) else LOST
    )


def deltalake_write_from_parquet(tmp: Path) -> str:
    deltalake = pytest.importorskip("deltalake")
    src = _fingerprinted_parquet(tmp)
    out = tmp / "delta_out"
    deltalake.write_deltalake(str(out), pq.read_table(src))
    return _kept(out)


def deltalake_append(tmp: Path) -> str:
    deltalake = pytest.importorskip("deltalake")
    src = _fingerprinted_delta(tmp)
    deltalake.write_deltalake(str(src), TABLE, mode="append")
    return _kept(src)


def deltalake_overwrite(tmp: Path) -> str:
    deltalake = pytest.importorskip("deltalake")
    src = _fingerprinted_delta(tmp)
    deltalake.write_deltalake(str(src), TABLE, mode="overwrite")
    return _kept(src)


def deltalake_optimize(tmp: Path) -> str:
    deltalake = pytest.importorskip("deltalake")
    src = _fingerprinted_delta(tmp)
    deltalake.write_deltalake(str(src), TABLE, mode="append")
    deltalake.DeltaTable(str(src)).optimize.compact()
    return _kept(src)


def deltalake_to_new_table(tmp: Path) -> str:
    deltalake = pytest.importorskip("deltalake")
    src = _fingerprinted_delta(tmp)
    out = tmp / "delta_out"
    deltalake.write_deltalake(str(out), deltalake.DeltaTable(str(src)).to_pyarrow_table())
    return _kept(out)


def deltalake_copy_directory(tmp: Path) -> str:
    src = _fingerprinted_delta(tmp)
    out = tmp / "copy"
    shutil.copytree(src, out)
    return _kept(out)


def _duckdb_delta(tmp: Path) -> tuple[object, Path] | None:
    duckdb = pytest.importorskip("duckdb")
    src = _fingerprinted_delta(tmp)
    con = duckdb.connect()
    try:
        con.sql("INSTALL delta")
        con.sql("LOAD delta")
    except Exception:
        return None
    return con, src


def duckdb_delta_to_parquet(tmp: Path) -> str:
    found = _duckdb_delta(tmp)
    if found is None:
        return NOT_RUN
    con, src = found
    out = tmp / "out.parquet"
    con.sql(f"COPY (SELECT * FROM delta_scan('{src}')) TO '{out}' (FORMAT PARQUET)")
    return _kept(out)


SCENARIOS: list[tuple[str, str, str, Callable[[Path], str]]] = [
    ("pyarrow", "`pq.read_table` then `pq.write_table`", "Parquet file", pyarrow_roundtrip),
    (
        "pyarrow",
        "`pq.read_table(columns=[...])` then `pq.write_table`",
        "Parquet file",
        pyarrow_columns_only,
    ),
    (
        "pyarrow",
        "`ParquetWriter` with a schema built from the fields",
        "Parquet file",
        pyarrow_new_schema,
    ),
    ("pyarrow", "`pyarrow.dataset.write_dataset`", "Parquet file", pyarrow_dataset_write),
    (
        "pandas",
        "`to_pandas` then `Table.from_pandas` and `pq.write_table`",
        "Parquet file",
        pandas_roundtrip,
    ),
    (
        "DuckDB",
        "`COPY (SELECT * FROM read_parquet(...)) TO ...`",
        "Parquet file",
        duckdb_copy_parquet,
    ),
    ("DuckDB", "the same `COPY` with `KV_METADATA`", "Parquet file", duckdb_copy_with_kv_metadata),
    (
        "DuckDB",
        "`parquet_kv_metadata(...)` (read only)",
        "Parquet file",
        duckdb_reads_parquet_metadata,
    ),
    (
        "deltalake",
        "`write_deltalake` of the Parquet file's rows",
        "Parquet file",
        deltalake_write_from_parquet,
    ),
    ("deltalake", '`write_deltalake(mode="append")`', "Delta table", deltalake_append),
    ("deltalake", '`write_deltalake(mode="overwrite")`', "Delta table", deltalake_overwrite),
    ("deltalake", "`optimize.compact()`", "Delta table", deltalake_optimize),
    (
        "deltalake",
        "`to_pyarrow_table` then `write_deltalake` to a new table",
        "Delta table",
        deltalake_to_new_table,
    ),
    (
        "file copy",
        "`shutil.copytree` of the table directory",
        "Delta table",
        deltalake_copy_directory,
    ),
    (
        "DuckDB",
        "`COPY (SELECT * FROM delta_scan(...)) TO ...` (needs the `delta` extension)",
        "Delta table",
        duckdb_delta_to_parquet,
    ),
]


def run_scenarios(tmp_root: Path) -> list[tuple[str, str, str, str]]:
    rows = []
    for i, (tool, operation, kind, fn) in enumerate(SCENARIOS):
        tmp = tmp_root / f"s{i}"
        tmp.mkdir()
        try:
            result = fn(tmp)
        except pytest.skip.Exception:
            result = NOT_RUN
        rows.append((tool, operation, kind, result))
    return rows


def render(rows: list[tuple[str, str, str, str]]) -> str:
    lines = [
        "| Tool | Operation | Input | `shape.fingerprint` |",
        "|---|---|---|---|",
    ]
    lines += [f"| {t} | {o} | {k} | {r} |" for t, o, k, r in rows]
    return "\n".join(lines)


def block(text: str) -> str:
    return f"{BEGIN}\n{text}\n{END}"


def committed() -> str:
    doc = DOC.read_text(encoding="utf-8")
    start, stop = doc.index(BEGIN), doc.index(END) + len(END)
    return doc[start:stop]


def test_the_preservation_table_in_the_docs_is_what_the_tools_do(tmp_path):
    pytest.importorskip("deltalake")
    pytest.importorskip("duckdb")
    rows = run_scenarios(tmp_path)
    expected = block(render(rows))
    if os.environ.get("SHAPE_UPDATE_DOCS") == "1":
        doc = DOC.read_text(encoding="utf-8")
        start, stop = doc.index(BEGIN), doc.index(END) + len(END)
        DOC.write_text(doc[:start] + expected + doc[stop:], encoding="utf-8")
    assert committed() == expected


def test_a_fingerprint_written_by_shape_is_what_every_scenario_starts_from(tmp_path):
    src = _fingerprinted_parquet(tmp_path)
    assert fingerprint.verify(src).digest_ok
    delta = _fingerprinted_delta(tmp_path)
    assert fingerprint.verify(delta).digest_ok


def test_pyarrow_keeps_it_when_the_schema_is_kept_and_drops_it_when_rebuilt(tmp_path):
    (tmp_path / "a").mkdir()
    (tmp_path / "b").mkdir()
    assert pyarrow_roundtrip(tmp_path / "a") == SURVIVES
    assert pyarrow_new_schema(tmp_path / "b") == LOST


def test_surviving_the_rewrite_is_not_the_same_as_still_verifying(tmp_path):
    """A tool that keeps the entry while it changes the data leaves a fingerprint that no longer
    verifies: ``shape fingerprint verify`` recomputes ``table_id``, it does not trust the entry."""
    src = _fingerprinted_parquet(tmp_path)
    out = tmp_path / "out.parquet"
    pq.write_table(pq.read_table(src, columns=["id"]), out)
    assert fingerprint.read_text(out) is not None
    assert not fingerprint.verify(out).ok
