"""P4-04a: sequence, uuid, weighted_enum, distribution, empirical and pattern.

Each case of ``benchmarks/vs_spindle/strategy_1to1/cases.py`` is generated by the engine at Shape's
fixed seed (1042) and compared, under T-21 clauses (b)-(e), with the fingerprints of the pinned
baseline's strategy at its fixed seeds 43-46 (``fixtures/strategies/*.json``, regenerated and
checked by ``baseline.py --check``). Nothing here needs the baseline's venv.
"""

from __future__ import annotations

import importlib.util
import json
import re
import sys
import warnings
from pathlib import Path
from typing import Any

import numpy as np
import pyarrow as pa
import pytest

from shape.generation.engine import Engine

ROOT = Path(__file__).resolve().parents[2]
BENCH = ROOT / "benchmarks" / "vs_spindle"
S1 = BENCH / "strategy_1to1"
sys.path.insert(0, str(S1))
sys.path.insert(0, str(BENCH))

import cases as cases_mod  # noqa: E402
import compare  # noqa: E402
import fingerprint  # noqa: E402

_spec = importlib.util.spec_from_file_location(
    "vs_spindle_schema_import", BENCH / "schema_import.py"
)
assert _spec and _spec.loader
schema_import = importlib.util.module_from_spec(_spec)
sys.modules["vs_spindle_schema_import"] = schema_import
_spec.loader.exec_module(schema_import)

SHAPE_SEED = 1042
STRATEGIES = ("sequence", "uuid", "weighted_enum", "distribution", "empirical", "pattern")
CASES = {k: v for k, v in cases_mod.CASES.items() if v["strategy"] in STRATEGIES}
FIXTURES = {
    s: json.loads((BENCH / "fixtures" / "strategies" / f"{s}.json").read_text("utf-8"))
    for s in STRATEGIES
}


def _engine(case_id: str, rows: int = cases_mod.ROWS, seed: int = SHAPE_SEED) -> Engine:
    raw = cases_mod.schema_for(CASES[case_id], rows=rows)
    return Engine(schema_import.import_dump(raw), seed=seed)


def _column(case_id: str, **kw: Any) -> pa.Array:
    return _engine(case_id, **kw).generate_table("t").column("x").combine_chunks()


@pytest.fixture(scope="module")
def generated() -> dict[str, pa.Array]:
    return {cid: _column(cid) for cid in CASES}


def test_fixtures_cover_every_case():
    for cid, case in CASES.items():
        fx = FIXTURES[case["strategy"]]
        assert cid in fx["cases"], cid
        assert fx["seeds"] == [43, 44, 45, 46] and fx["rows"] == cases_mod.ROWS
        assert len(fx["cases"][cid]["fingerprints"]) == 4
    assert set(STRATEGIES) == set(cases_mod.strategies())


@pytest.mark.parametrize("case_id", sorted(CASES))
def test_equivalent_to_the_baseline(case_id, generated):
    case = CASES[case_id]
    fps = FIXTURES[case["strategy"]]["cases"][case_id]["fingerprints"]
    got = fingerprint.fingerprint(generated[case_id].to_pylist())
    assert compare.check(got, fps) == []


@pytest.mark.parametrize("case_id", sorted(c for c in CASES if CASES[c]["regex"]))
def test_values_follow_the_pattern(case_id, generated):
    rx = re.compile(CASES[case_id]["regex"])
    bad = [v for v in generated[case_id].to_pylist() if v is not None and not rx.fullmatch(v)]
    assert bad == []


@pytest.mark.parametrize("case_id", sorted(CASES))
def test_identical_for_any_chunking_and_random_access(case_id):
    rows = 20_000
    engine = _engine(case_id, rows=rows)
    whole = engine.generate_table("t", chunk_rows=rows).column("x").combine_chunks()
    for chunk in (1_000, 4_093):
        parts = engine.generate_table("t", chunk_rows=chunk).column("x").combine_chunks()
        assert parts.equals(whole), f"chunk {chunk}"
    piece = engine.generate_chunk("t", 12_345, 777).column("x")
    assert piece.equals(whole.slice(12_345, 777))


@pytest.mark.parametrize("case_id", sorted(CASES))
def test_deterministic_and_seeds_differ(case_id):
    a = _column(case_id, rows=3_000)
    assert a.equals(_column(case_id, rows=3_000))
    if CASES[case_id]["strategy"] != "sequence" and not re.fullmatch(
        r"pattern/(seq_.*|unresolved_token)", case_id
    ):
        other = _column(case_id, rows=3_000, seed=SHAPE_SEED + 1)
        assert not other.equals(a)


def test_the_comparison_can_fail():
    """Negative controls: a wrong mean, a wrong weight, a wrong family and a wrong format are
    each caught by the same comparison that passes above."""

    def fails(case_id: str, mutate: dict[str, Any]) -> list[str]:
        case = json.loads(json.dumps(CASES[case_id]))
        case["column"]["generator"].update(mutate)
        raw = cases_mod.schema_for(case)
        col = (
            Engine(schema_import.import_dump(raw), seed=SHAPE_SEED)
            .generate_table("t")
            .column("x")
            .combine_chunks()
        )
        fps = FIXTURES[CASES[case_id]["strategy"]]["cases"][case_id]["fingerprints"]
        return compare.check(fingerprint.fingerprint(col.to_pylist()), fps)

    assert fails("distribution/normal", {"mean": 101})
    assert fails("distribution/normal", {"std_dev": 17})
    assert fails("distribution/poisson", {"lambda": 7.2})
    assert fails("distribution/zipf", {"alpha": 1.9})
    assert fails("weighted_enum/three", {"values": {"gold": 0.45, "silver": 0.35, "bronze": 0.2}})
    assert fails("weighted_enum/three", {"values": {"gold": 0.5, "silver": 0.3, "tin": 0.2}})
    assert fails("pattern/seq_padded", {"format": "INV-{seq:7}"})
    assert fails("pattern/random", {"format": "{random:4}-{random:3}"})
    assert fails("sequence/default", {"start": 20_000})


# ---------------------------------------------------------------- behaviours


def test_sequence_values_are_exact():
    col = _column("sequence/offset_step", rows=1_000)
    assert col.to_pylist() == [1000 + 7 * i for i in range(1_000)]
    assert col.type == pa.int64()


def test_uuid_is_version_4_and_unique(generated):
    import uuid

    values = generated["uuid/default"].to_pylist()
    assert len(set(values)) == len(values)
    assert all(uuid.UUID(v).version == 4 for v in values[:500])


def test_weighted_enum_types(generated):
    assert generated["weighted_enum/three"].type == pa.string()
    assert generated["weighted_enum/numeric_labels"].type == pa.float64()
    assert set(generated["weighted_enum/numeric_labels"].to_pylist()) == {0.0, 1.0, 2.5}
    assert generated["weighted_enum/nullable"].null_count > 0


def test_distribution_types_bounds_and_scale(generated):
    for cid in (c for c in CASES if c.startswith("distribution/")):
        assert generated[cid].type == pa.float64(), cid
    clipped = np.asarray(generated["distribution/normal_clipped"].to_pylist())
    assert clipped.min() >= 20 and clipped.max() <= 90
    scaled = np.asarray(generated["distribution/log_normal_scale"].to_pylist())
    assert scaled.min() >= 5 and scaled.max() <= 400
    assert (np.round(scaled, 2) == scaled).all()
    assert set(generated["distribution/bernoulli"].to_pylist()) <= {0.0, 1.0}
    z = np.asarray(generated["distribution/zipf"].to_pylist())
    assert z.min() >= 1 and z.max() <= 200


def test_distribution_families_hit_their_moments():
    n = 400_000

    def draw(name: str, **p: Any) -> np.ndarray[Any, Any]:
        generator = {"strategy": "distribution", "distribution": name, **p}
        case = {
            "strategy": "distribution",
            "helpers": {},
            "regex": None,
            "column": cases_mod._col("x", "decimal", generator),
        }
        raw = cases_mod.schema_for(case, rows=n)
        col = Engine(schema_import.import_dump(raw), seed=5).generate_table("t").column("x")
        return np.asarray(col.to_pylist())

    u = draw("uniform", min=2, max=6)
    assert abs(u.mean() - 4) < 0.02
    g = draw("geometric", p=0.25)
    assert abs(g.mean() - 4) < 0.05 and g.min() == 1
    p = draw("poisson", **{"lambda": 4})
    assert abs(p.mean() - 4) < 0.02 and abs(p.var() - 4) < 0.05
    big = draw("poisson", **{"lambda": 2500})
    assert abs(big.mean() - 2500) < 1.0 and abs(big.std() - 50) < 0.5
    par = draw("pareto", alpha=3.0, min=2)
    assert par.min() >= 2 and abs(par.mean() - 3.0) < 0.05
    assert draw("geometric", p=1.0).max() == 1
    assert draw("poisson", **{"lambda": 0}).max() == 0


def test_empirical_follows_its_quantiles(generated):
    col = np.asarray(generated["empirical/linear"].to_pylist())
    q = cases_mod._QUANTILES
    got = np.quantile(col, [0.1, 0.25, 0.5, 0.75, 0.9])
    want = [q["p10"], q["p25"], q["p50"], q["p75"], q["p90"]]
    assert np.allclose(got, want, rtol=0.03)
    assert col.min() >= q["p1"] and col.max() <= q["p99"]
    anchored = np.asarray(generated["empirical/tail_anchors"].to_pylist())
    assert anchored.min() < q["p1"] and anchored.max() > q["p99"]


def test_empirical_cubic_without_scipy_falls_back_to_linear(monkeypatch):
    case = json.loads(json.dumps(CASES["empirical/linear"]))
    case["column"]["generator"]["interpolation"] = "cubic"
    raw = cases_mod.schema_for(case, rows=500)
    monkeypatch.setitem(sys.modules, "scipy", None)
    monkeypatch.setitem(sys.modules, "scipy.interpolate", None)
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        cubic = Engine(schema_import.import_dump(raw), seed=3).generate_table("t").column("x")
    assert any(issubclass(w.category, ImportWarning) for w in caught)
    linear = _column("empirical/linear", rows=500, seed=3)
    assert cubic.combine_chunks().equals(linear)


def test_pattern_reference_and_unresolved_tokens(generated):
    ref = generated["pattern/column_reference"].to_pylist()
    assert ref[0].split("-")[1:] == ["0001", "001"]
    assert ref[998].endswith("-0999-999") and ref[999].endswith("-1000-1000")
    assert generated["pattern/unresolved_token"].to_pylist()[:2] == ["{nothing}-01", "{nothing}-02"]
    assert generated["pattern/seq_padded"].to_pylist()[:2] == ["INV-000001", "INV-000002"]


def test_pattern_null_reference_gives_null():
    raw = cases_mod.schema_for(CASES["pattern/column_reference"], rows=2_000)
    raw["tables"]["t"]["columns"]["tier"]["nullable"] = True
    raw["tables"]["t"]["columns"]["tier"]["null_rate"] = 0.3
    table = Engine(schema_import.import_dump(raw), seed=9).generate_table("t")
    tier, x = table.column("tier").to_pylist(), table.column("x").to_pylist()
    assert any(t is None for t in tier)
    assert all((t is None) == (v is None) for t, v in zip(tier, x, strict=True))


@pytest.mark.parametrize(
    ("strategy", "spec", "message"),
    [
        ("weighted_enum", {}, "weighted_enum strategy requires a non-empty 'values'"),
        ("weighted_enum", {"values": {}}, "non-empty 'values'"),
        ("weighted_enum", {"values": {"a": -1, "b": 2}}, "non-negative"),
        ("weighted_enum", {"values": {"a": 0, "b": 0}}, "positive sum"),
        ("distribution", {"distribution": "no_such"}, "unknown distribution 'no_such'"),
        ("distribution", {"distribution": "uniform", "min": 5, "max": 1}, "low <= high"),
        ("distribution", {"distribution": "geometric", "p": 0}, "0 < p <= 1"),
        ("distribution", {"distribution": "zipf", "alpha": 0}, "a > 0"),
        ("distribution", {"distribution": "normal", "std_dev": -1}, "sigma >= 0"),
        ("empirical", {}, "requires 'quantiles'"),
        ("empirical", {"quantiles": {"p1": 1}}, "missing quantile keys"),
        ("pattern", {}, "requires 'format'"),
        ("pattern", {"format": ""}, "requires 'format'"),
    ],
)
def test_bad_specs_name_the_column(strategy, spec, message):
    case = {
        "strategy": strategy,
        "helpers": {},
        "regex": None,
        "column": cases_mod._col("x", "string", {"strategy": strategy, **spec}),
    }
    raw = cases_mod.schema_for(case, rows=10)
    engine = Engine(schema_import.import_dump(raw), seed=1)
    with pytest.raises(ValueError, match=re.escape(message)) as err:
        engine.generate_table("t")
    assert "t.x" in str(err.value) or message in str(err.value)
