"""P4-04c: conditional, correlated, lookup, reference_data, temporal, record_sample, record_field.

Each case of ``benchmarks/vs_spindle/strategy_1to1/cases.py`` is generated by the engine at Shape's
fixed seed (1042) and compared, under T-21 clauses (b)-(e), with the fingerprints of the pinned
baseline's strategy at its fixed seeds 43-46 (``fixtures/strategies/*.json``, regenerated and
checked by ``baseline.py --check``). Nothing here needs the baseline's venv. Datetime columns are
also compared on their month, weekday and hour-of-day profiles.
"""

from __future__ import annotations

import importlib.util
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pyarrow as pa
import pytest

from shape.generation import reference
from shape.generation.engine import Engine
from shape.generation.permutation import permute

ROOT = Path(__file__).resolve().parents[2]
BENCH = ROOT / "benchmarks" / "vs_spindle"
sys.path.insert(0, str(BENCH / "strategy_1to1"))
sys.path.insert(0, str(BENCH))

import cases as cases_mod  # noqa: E402
import compare  # noqa: E402
import fingerprint  # noqa: E402

_spec = importlib.util.spec_from_file_location(
    "vs_spindle_schema_import", BENCH / "schema_import.py"
)
assert _spec and _spec.loader
schema_import = importlib.util.module_from_spec(_spec)
sys.modules["vs_spindle_schema_import"] = schema_import
_spec.loader.exec_module(schema_import)

SHAPE_SEED = 1042
STRATEGIES = (
    "conditional",
    "correlated",
    "lookup",
    "reference_data",
    "temporal",
    "record_field",
    "record_sample",
)
CASES = {k: v for k, v in cases_mod.CASES.items() if v["strategy"] in STRATEGIES}
FIXTURES = {
    s: json.loads((BENCH / "fixtures" / "strategies" / f"{s}.json").read_text("utf-8"))
    for s in STRATEGIES
}


@pytest.fixture(autouse=True, scope="module")
def _datasets():
    for name, rows in cases_mod.DATASETS.items():
        reference.register_dataset(name, rows)
    yield
    for name in cases_mod.DATASETS:
        reference.unregister_dataset(name)


def _engine(case_id: str, rows: int | None = None, seed: int = SHAPE_SEED) -> Engine:
    raw = cases_mod.schema_for(CASES[case_id], rows=rows)
    return Engine(schema_import.import_dump(raw), seed=seed)


def _column(case_id: str, **kw: Any) -> pa.Array:
    return _engine(case_id, **kw).generate_table("t").column("x").combine_chunks()


@pytest.fixture(scope="module")
def generated(_datasets) -> dict[str, pa.Array]:
    return {cid: _column(cid) for cid in CASES}


def test_fixtures_cover_every_case():
    for cid, case in CASES.items():
        fx = FIXTURES[case["strategy"]]
        assert cid in fx["cases"], cid
        assert fx["seeds"] == [43, 44, 45, 46] and fx["rows"] == cases_mod.ROWS
        assert len(fx["cases"][cid]["fingerprints"]) == 4
    assert set(STRATEGIES) <= set(cases_mod.strategies())
    assert {c["strategy"] for c in CASES.values()} == set(STRATEGIES)


@pytest.mark.parametrize("case_id", sorted(CASES))
def test_equivalent_to_the_baseline(case_id, generated):
    case = CASES[case_id]
    fps = FIXTURES[case["strategy"]]["cases"][case_id]["fingerprints"]
    got = fingerprint.fingerprint(generated[case_id].to_pylist())
    assert compare.check(got, fps) == []


@pytest.mark.parametrize("case_id", sorted(CASES))
def test_identical_for_any_chunking_and_random_access(case_id):
    rows = CASES[case_id].get("rows", 20_000)
    engine = _engine(case_id, rows=rows)
    whole = engine.generate_table("t", chunk_rows=rows).column("x").combine_chunks()
    for chunk in (max(1, rows // 20), max(1, rows // 7) + 1):
        parts = engine.generate_table("t", chunk_rows=chunk).column("x").combine_chunks()
        assert parts.equals(whole), f"chunk {chunk}"
    start, count = rows // 3, max(1, rows // 8)
    piece = engine.generate_chunk("t", start, count).column("x")
    assert piece.equals(whole.slice(start, count))


@pytest.mark.parametrize("case_id", sorted(CASES))
def test_deterministic_and_seeds_differ(case_id):
    rows = CASES[case_id].get("rows", 3_000)
    a = _column(case_id, rows=rows)
    assert a.equals(_column(case_id, rows=rows))
    assert not _column(case_id, rows=rows, seed=SHAPE_SEED + 1).equals(a)


def test_the_comparison_can_fail():
    """Negative controls: each change is caught by the comparison that passes above."""

    def fails(case_id: str, mutate: dict[str, Any], helper: dict[str, Any] | None = None) -> bool:
        case = json.loads(json.dumps(CASES[case_id]))
        case["column"]["generator"].update(mutate)
        for name, change in (helper or {}).items():
            case["helpers"][name]["generator"].update(change)
        engine = Engine(schema_import.import_dump(cases_mod.schema_for(case)), seed=SHAPE_SEED)
        col = engine.generate_table("t").column("x").combine_chunks()
        fps = FIXTURES[CASES[case_id]["strategy"]]["cases"][case_id]["fingerprints"]
        return bool(compare.check(fingerprint.fingerprint(col.to_pylist()), fps))

    assert fails("correlated/multiply_params", {"params": {"factor_min": 1.3, "factor_max": 1.9}})
    assert fails("correlated/add", {"params": {"offset_min": 2, "offset_max": 22}})
    assert fails("correlated/subtract_clipped", {"rule": "add"})
    assert fails("conditional/equals_text", {"condition": "tier == 'B'"})
    assert fails("conditional/not_equals_number", {"true_generator": {"fixed": 5.4}})
    assert fails("conditional/is_null_fixed", {"true_generator": {"fixed": 1.5}})
    assert fails("lookup/small_parent", {}, {"pid": {"values": cases_mod._zipf_keys(40, 2.5)}})
    assert fails("lookup/small_parent", {"source_column": "pid"})
    assert fails(
        "temporal/seasonal_month", {"profiles": {"month": {**cases_mod._MONTHS_W, "Nov": 2.0}}}
    )
    assert fails("temporal/seasonal_dow", {"profiles": {"day_of_week": {"Sat": 1.0}}})
    assert fails(
        "temporal/seasonal_both_bimodal",
        {
            "profiles": {
                **CASES["temporal/seasonal_both_bimodal"]["column"]["generator"]["profiles"],
                "hour_of_day": {"distribution": "bimodal", "peaks": [10, 19], "std_dev": 2.5},
            }
        },
    )
    assert fails(
        "temporal/seasonal_month",
        {"profiles": {"month": cases_mod._MONTHS_W, "hour_of_day": {"distribution": "uniform"}}},
    )
    assert fails("temporal/uniform_range", {"end": "2024-03-30"})
    assert fails(
        "temporal/uniform_default", {"pattern": "seasonal", "profiles": {"month": {"Dec": 2}}}
    )
    assert fails("record_field/state", {"field": "zip"})


def test_a_changed_dataset_is_caught():
    cases = {
        "reference_data/weighted_name": [{**r, "weight": 1.0} for r in cases_mod.WEIGHTED],
        "reference_data/field_text": cases_mod.CATALOG[:-3],
    }
    for case_id, rows in cases.items():
        name = CASES[case_id]["column"]["generator"]["dataset"]
        reference.register_dataset(name, rows)
        try:
            col = _column(case_id)
        finally:
            reference.register_dataset(name, cases_mod.DATASETS[name])
        fps = FIXTURES["reference_data"]["cases"][case_id]["fingerprints"]
        assert compare.check(fingerprint.fingerprint(col.to_pylist()), fps), case_id


# ---------------------------------------------------------------- lookup


def _tables(
    parent_rows: int,
    via: dict[str, Any],
    x: dict[str, Any],
    *,
    parent: dict[str, Any] | None = None,
    child_rows: int = 50,
    extra: dict[str, Any] | None = None,
) -> Engine:
    """A parent table ``p`` (key ``pid`` 1.., column ``label``) and a child ``t`` with column
    ``via`` and ``x``."""
    col = cases_mod._col
    p_cols = {
        "pid": col("pid", "integer", {"strategy": "sequence", "start": 1}),
        "label": col("label", "string", {"strategy": "pattern", "format": "L{seq:3}"}),
        "n": col("n", "integer", {"strategy": "sequence", "start": 100, "step": 10}),
        **(parent or {}),
    }
    case = {
        "strategy": "lookup",
        "helpers": {"via": via},
        "regex": None,
        "column": col("x", "string", x),
        "tables": {"p": {"rows": parent_rows, "primary_key": ["pid"], "columns": p_cols}},
        **(extra or {}),
    }
    return Engine(schema_import.import_dump(cases_mod.schema_for(case, rows=child_rows)), seed=3)


def _enum(values: dict[str, float], **extra: Any) -> dict[str, Any]:
    return cases_mod._col(
        "via", "decimal", {"strategy": "weighted_enum", "values": values}, **extra
    )


def _lookup(source_column: str = "label", **extra: Any) -> dict[str, Any]:
    return {
        "strategy": "lookup",
        "source_table": "p",
        "source_column": source_column,
        "via": "via",
        **extra,
    }


def test_lookup_reads_the_parent_row_of_the_key():
    engine = _tables(5, _enum({"1": 1, "2": 1, "5": 1}), _lookup())
    t = engine.generate_table("t")
    keys = [int(v) for v in t["via"].to_pylist()]
    assert t["x"].to_pylist() == [f"L{k:03d}" for k in keys]
    assert {1, 2, 5} == set(keys)
    # The type of the source column is kept.
    numbers = _tables(5, _enum({"1": 1, "3": 1}), _lookup("n")).generate_table("t")
    assert numbers["x"].type == pa.int64()
    assert numbers["x"].to_pylist() == [100 + 10 * (int(k) - 1) for k in numbers["via"].to_pylist()]


def test_lookup_missing_and_null_keys_give_null():
    via = _enum({"1": 1, "9": 1}, nullable=True, null_rate=0.3)
    t = _tables(5, via, _lookup()).generate_table("t")
    for key, value in zip(t["via"].to_pylist(), t["x"].to_pylist(), strict=True):
        assert value == (None if key is None or key == 9.0 else "L001")
    assert None in t["via"].to_pylist() and 9.0 in t["via"].to_pylist()


def test_lookup_matches_integer_and_float_keys_by_value_and_text_keys():
    # float keys (a numeric weighted_enum) against an integer key column: matched by value
    t = _tables(4, _enum({"2": 1, "4": 1}), _lookup()).generate_table("t")
    assert set(t["x"].to_pylist()) == {"L002", "L004"}
    # text keys: the parent column is a pattern string, the child's via is text too
    col = cases_mod._col
    parent = {"code": col("code", "string", {"strategy": "pattern", "format": "K{seq:2}"})}
    via = col(
        "via", "string", {"strategy": "weighted_enum", "values": {"K01": 1, "K03": 1, "KZZ": 1}}
    )
    t = _tables(4, via, _lookup(key="code"), parent=parent).generate_table("t")
    got = dict(zip(t["via"].to_pylist(), t["x"].to_pylist(), strict=True))
    assert got == {"K01": "L001", "K03": "L003", "KZZ": None}


def test_lookup_takes_the_first_row_of_a_repeated_key():
    col = cases_mod._col
    parent = {"grp": col("grp", "integer", {"strategy": "weighted_enum", "values": {"7": 1}})}
    t = _tables(5, _enum({"7": 1}), _lookup(key="grp"), parent=parent).generate_table("t")
    assert set(t["x"].to_pylist()) == {"L001"}


def test_lookup_resolves_the_key_through_the_foreign_key_and_the_primary_key():
    col = cases_mod._col
    # `via` is not a column of the parent: the parent's primary key is used.
    engine = _tables(5, col("via", "integer", {"strategy": "sequence", "start": 1}), _lookup())
    assert engine.generate_table("t")["x"].to_pylist()[:5] == [
        "L001",
        "L002",
        "L003",
        "L004",
        "L005",
    ]
    # a parent without a single-column key and no `key`: a clear error
    engine = _tables(5, col("via", "integer", {"strategy": "sequence", "start": 1}), _lookup())
    engine.schema.tables["p"].primary_key = []
    with pytest.raises(ValueError, match="cannot tell which column of p"):
        engine.generate_table("t")


@pytest.mark.parametrize(
    ("x", "message"),
    [
        ({"strategy": "lookup", "source_table": "p"}, "requires 'source_table', 'source_column'"),
        (_lookup(source_table="nope"), "source table 'nope' is not in the schema"),
        (_lookup("nope"), "source column p.nope does not exist"),
        (_lookup(via="later"), "via column 'later' is not generated before t.x"),
        (_lookup(key="nope"), "lookup key 'nope' is not a column of p"),
        (_lookup(source_table="t", source_column="via"), "circular"),
    ],
)
def test_lookup_bad_specs(x, message):
    engine = _tables(5, _enum({"1": 1}), x)
    with pytest.raises(ValueError, match=re.escape(message)):
        engine.generate_table("t")


def test_lookup_through_a_cycle_of_tables_is_an_error_not_a_hang():
    col = cases_mod._col
    parent = {
        "back": col(
            "back",
            "string",
            {"strategy": "lookup", "source_table": "t", "source_column": "x", "via": "label"},
        )
    }
    engine = _tables(5, _enum({"1": 1}), _lookup("back"), parent=parent)
    with pytest.raises(ValueError, match="circular"):
        engine.generate_table("t")


def test_lookup_index_is_built_once_per_engine():
    from shape.generation import lookup

    engine = _tables(5, _enum({"1": 1, "2": 1}), _lookup())
    a = lookup.key_index(engine, "p", "pid")
    engine.generate_table("t")
    assert lookup.key_index(engine, "p", "pid") is a
    assert a.positions(pa.array([2, 9, None], type=pa.int64())).tolist() == [1, -1, -1]
    assert a.positions(pa.array([], type=pa.int64())).tolist() == []


# ---------------------------------------------------------------- conditional


def _conditional(condition: str, true: Any, false: Any, helpers: dict[str, Any]) -> pa.Table:
    case = {
        "strategy": "conditional",
        "helpers": helpers,
        "regex": None,
        "column": cases_mod._col(
            "x",
            "decimal",
            {
                "strategy": "conditional",
                "condition": condition,
                "true_generator": true,
                "false_generator": false,
            },
        ),
    }
    engine = Engine(schema_import.import_dump(cases_mod.schema_for(case, rows=400)), seed=2)
    return engine.generate_table("t")


def test_conditional_branches_and_types():
    h = {"tier": cases_mod._helper("tier", {"A": 1, "B": 1})}
    t = _conditional("tier == 'A'", {"fixed": 3}, {"fixed": "no"}, h)
    assert t["x"].type == pa.string()  # a text branch makes the column text
    assert set(t["x"].to_pylist()) == {"3.0", "no"} or set(t["x"].to_pylist()) == {"3", "no"}
    t = _conditional("tier != 'A'", {"fixed": True}, {"fixed": None}, h)
    assert t["x"].type == pa.float64()
    assert {(a, b) for a, b in zip(t["tier"].to_pylist(), t["x"].to_pylist(), strict=True)} == {
        ("B", 1.0),
        ("A", None),
    }
    t = _conditional("tier == 'A'", {}, {"fixed": 2}, h)
    assert {(a, b) for a, b in zip(t["tier"].to_pylist(), t["x"].to_pylist(), strict=True)} == {
        ("A", 0.0),
        ("B", 2.0),
    }


def test_conditional_null_foreign_key_looks_up_zero():
    col = cases_mod._col
    case = {
        "strategy": "conditional",
        "helpers": {
            "pid": cases_mod._helper(
                "pid", {"1": 1, "2": 1, "7": 1}, "decimal", nullable=True, null_rate=0.3
            )
        },
        "regex": None,
        "column": col(
            "x",
            "decimal",
            {
                "strategy": "conditional",
                "condition": "pid IS NULL",
                "true_generator": {"strategy": "lookup", **cases_mod._lookup("p", "n", "pid")},
                "false_generator": {"strategy": "lookup", **cases_mod._lookup("p", "n", "pid")},
            },
        ),
        "tables": {
            "p": cases_mod._parent(
                2, {"n": col("n", "integer", {"strategy": "sequence", "start": 10, "step": 10})}
            )
        },
    }
    t = Engine(
        schema_import.import_dump(cases_mod.schema_for(case, rows=300)), seed=2
    ).generate_table("t")
    got = {(k, v) for k, v in zip(t["pid"].to_pylist(), t["x"].to_pylist(), strict=True)}
    assert got == {(None, 0.0), (1.0, 10.0), (2.0, 20.0), (7.0, None)}


@pytest.mark.parametrize(
    ("condition", "true", "message"),
    [
        ("gibberish", {"fixed": 1}, "cannot read the condition 'gibberish'"),
        ("", {"fixed": 1}, "cannot read the condition ''"),
        ("nope IS NULL", {"fixed": 1}, "column 'nope' not generated before t.x"),
        ("nope == 3", {"fixed": 1}, "column 'nope' not generated before t.x"),
        ("tier == 'A'", {"strategy": "formula"}, "supports 'fixed' and 'lookup', not 'formula'"),
        ("tier == 'A'", {"strategy": "lookup", "via": "tier"}, "lookup requires"),
    ],
)
def test_conditional_bad_specs(condition, true, message):
    h = {"tier": cases_mod._helper("tier", {"A": 1, "B": 1})}
    with pytest.raises(ValueError, match=re.escape(message)):
        _conditional(condition, true, {"fixed": 0}, h)


# ---------------------------------------------------------------- correlated


def test_correlated_relation_bounds_and_nulls(generated):
    t = _engine("correlated/multiply_params").generate_table("t")
    ratio = np.asarray(t["x"].to_pylist()) / np.asarray(t["price"].to_pylist())
    assert ratio.min() >= 1.3 - 0.01 and ratio.max() <= 1.8 + 0.01
    assert (
        generated["correlated/subtract_clipped"].to_pylist()
        and min(generated["correlated/subtract_clipped"].to_pylist()) == 0.0
    )
    nulls = _engine("correlated/null_source").generate_table("t")
    assert nulls["x"].null_count == nulls["price"].null_count > 0
    assert (
        np.round(np.asarray(generated["correlated/operation_alias_scale"].to_pylist()), 3)
        == np.asarray(generated["correlated/operation_alias_scale"].to_pylist())
    ).all()
    assert generated["correlated/multiply_default"].type == pa.float64()


@pytest.mark.parametrize(
    ("spec", "message"),
    [
        ({}, "requires 'source_column'"),
        ({"source_column": "nope"}, "source column 'nope' is not generated yet"),
        ({"source_column": "price", "rule": "divide"}, "unknown rule 'divide'"),
        ({"source_column": "tag"}, "is not numeric"),
    ],
)
def test_correlated_bad_specs(spec, message):
    case = {
        "strategy": "correlated",
        "helpers": {
            "price": cases_mod._PRICE,
            "tag": cases_mod._col("tag", "string", {"strategy": "pattern", "format": "z{seq}"}),
        },
        "regex": None,
        "column": cases_mod._col("x", "decimal", {"strategy": "correlated", **spec}),
    }
    engine = Engine(schema_import.import_dump(cases_mod.schema_for(case, rows=20)), seed=1)
    with pytest.raises(ValueError, match=re.escape(message)):
        engine.generate_table("t")


# ---------------------------------------------------------------- reference data


def test_reference_data_types_and_membership(generated):
    assert generated["reference_data/strings"].type == pa.string()
    assert set(generated["reference_data/strings"].to_pylist()) == set(cases_mod.LABELS)
    assert generated["reference_data/field_float"].type == pa.float64()
    assert generated["reference_data/field_int"].type == pa.int64()
    assert set(generated["reference_data/weighted_name"].to_pylist()) <= {
        r["name"] for r in cases_mod.WEIGHTED
    }
    assert set(generated["reference_data/weighted_value_key"].to_pylist()) <= {
        r["value"] for r in cases_mod.WEIGHTED_VALUE
    }
    assert generated["reference_data/nullable"].null_count > 0


def test_record_groups_are_coherent_and_unique_is_unique(generated):
    places = {(r["city"], r["state"], r["zip"], r["lng"]) for r in cases_mod.PLACES}
    t = _engine("record_field/lng").generate_table("t")
    # anchor city, then lng from the same record
    by_city = {r["city"]: r for r in cases_mod.PLACES}
    assert all(
        by_city[c]["lng"] == v
        for c, v in zip(t["anchor"].to_pylist(), t["x"].to_pylist(), strict=True)
    )
    assert set(t["anchor"].to_pylist()) == set(by_city)
    del places
    unique = generated["record_sample/unique_all"].to_pylist()
    assert sorted(unique) == sorted(r["city"] for r in cases_mod.PLACES)
    subset = generated["record_sample/unique_subset"].to_pylist()
    assert len(subset) == len(set(subset)) == 45
    assert len(set(generated["record_sample/unique_too_many"].to_pylist())) <= 6  # with replacement
    u = _engine("record_field/unique_anchor").generate_table("t")
    states = {r["city"]: r["state"] for r in cases_mod.PLACES}
    assert [states[c] for c in u["anchor"].to_pylist()] == u["x"].to_pylist()


def test_record_field_before_or_after_the_anchor_agree():
    base = _engine("record_field/state")
    cols = base.schema.tables["t"].columns
    reordered = {k: cols[k] for k in ("id", "x", "anchor")}
    base.schema.tables["t"].columns = reordered
    after = Engine(base.schema, seed=SHAPE_SEED).generate_table("t")
    before = _engine("record_field/state").generate_table("t")
    assert after["x"].equals(before["x"]) and after["anchor"].equals(before["anchor"])


def test_last_record_sample_of_a_dataset_decides_the_record():
    case = json.loads(json.dumps(CASES["record_field/state"]))
    case["helpers"]["second"] = cases_mod._col(
        "second", "string", {"strategy": "record_sample", "dataset": "p404c_places", "field": "zip"}
    )
    raw = cases_mod.schema_for(case, rows=300)
    t = Engine(schema_import.import_dump(raw), seed=4).generate_table("t")
    by_zip = {r["zip"]: r["state"] for r in cases_mod.PLACES}
    assert [by_zip[z] for z in t["second"].to_pylist()] == t["x"].to_pylist()


@pytest.mark.parametrize(
    ("strategy", "spec", "message"),
    [
        ("reference_data", {}, "requires 'dataset'"),
        ("reference_data", {"dataset": "no_such_dataset"}, "'no_such_dataset' is not registered"),
        ("reference_data", {"dataset": "empty_set"}, "dataset 'empty_set' is empty"),
        (
            "reference_data",
            {"dataset": "bare_records", "field": "z"},
            "no field 'z', 'name' or 'value'",
        ),
        ("reference_data", {"dataset": "bad_weights"}, "non-negative weights"),
        ("record_sample", {"dataset": "p404c_places"}, "requires 'dataset' and 'field'"),
        ("record_sample", {"dataset": "p404c_labels", "field": "x"}, "holds plain values"),
        ("record_sample", {"dataset": "p404c_places", "field": "nope"}, "Field 'nope' not found"),
        (
            "record_field",
            {"dataset": "p404c_places", "field": "state"},
            "could not find a record_sample",
        ),
        ("record_field", {"field": "state"}, "requires 'dataset' and 'field'"),
    ],
)
def test_reference_bad_specs(strategy, spec, message):
    reference.register_dataset("empty_set", [])
    reference.register_dataset("bare_records", [{"a": 1}, {"a": 2}])
    reference.register_dataset("bad_weights", [{"name": "a", "weight": -1}])
    try:
        case = {
            "strategy": strategy,
            "helpers": {},
            "regex": None,
            "column": cases_mod._col("x", "string", {"strategy": strategy, **spec}),
        }
        engine = Engine(schema_import.import_dump(cases_mod.schema_for(case, rows=10)), seed=1)
        with pytest.raises(ValueError, match=re.escape(message)) as err:
            engine.generate_table("t")
    finally:
        for name in ("empty_set", "bare_records", "bad_weights"):
            reference.unregister_dataset(name)
    assert "t.x" in str(err.value) or "dataset" in str(err.value)


def test_unique_without_the_engine_needs_one():
    from shape.builtins.strategies.reference_data import RecordSample
    from shape.plugins.api.v1 import GenerationContext

    ctx = GenerationContext(1, "t", "c", 0, 0, 5)
    spec = {"dataset": "p404c_places", "field": "city", "unique": True}
    with pytest.raises(ValueError, match="needs the generation engine"):
        RecordSample().generate(spec, ctx)


def test_datasets_load_from_search_paths_and_the_environment(tmp_path, monkeypatch):
    (tmp_path / "from_file.json").write_text(json.dumps(["x", "y"]), "utf-8")
    other = tmp_path / "other"
    other.mkdir()
    (other / "from_env.json").write_text(json.dumps([{"name": "n", "weight": 1}]), "utf-8")
    reference.add_search_path(tmp_path)
    monkeypatch.setenv(reference.REFERENCE_PATH_ENV, str(other))
    try:
        assert reference.load_dataset("from_file").fields == ("value",)
        env = reference.load_dataset("from_env")
        assert env.records and len(env) == 1
        # an edited file is seen
        (tmp_path / "from_file.json").write_text(json.dumps(["x", "y", "z"]), "utf-8")
        assert len(reference.load_dataset("from_file")) == 3
        reference.clear_search_paths()
        reference.add_search_path(other)
        monkeypatch.delenv(reference.REFERENCE_PATH_ENV)
        with pytest.raises(reference.DatasetNotFoundError, match="from_file.json"):
            reference.load_dataset("from_file")
    finally:
        reference.clear_search_paths()
    assert os.environ.get(reference.REFERENCE_PATH_ENV) is None


def test_datasets_from_tables_and_mixed_columns():
    reference.register_dataset("tbl", pa.table({"a": [1, 2], "b": ["x", "y"]}))
    ds = reference.load_dataset("tbl")
    assert ds.records and ds.fields == ("a", "b") and ds.column("b").to_pylist() == ["x", "y"]
    reference.register_dataset("mixed", [{"v": 1}, {"v": "two"}, {"v": None}])
    assert reference.load_dataset("mixed").column("v").to_pylist() == ["1", "two", None]
    with pytest.raises(ValueError, match="list of strings or a list of objects"):
        reference.register_dataset("bad", [1, 2, 3])
    for name in ("tbl", "mixed"):
        reference.unregister_dataset(name)


# ---------------------------------------------------------------- temporal


def test_temporal_bounds_types_and_profiles(generated):
    for cid in (c for c in CASES if c.startswith("temporal/")):
        assert generated[cid].type == pa.timestamp("us"), cid
    uni = np.asarray(generated["temporal/uniform_range"].to_pylist(), dtype="datetime64[us]")
    assert uni.min() >= np.datetime64("2023-03-01") and uni.max() < np.datetime64("2024-03-01")
    # the end date is a possible day for the uniform range and the seasonal one alike (ISS-gen #10)
    assert uni.max() >= np.datetime64("2024-02-29")
    seasonal = np.asarray(generated["temporal/seasonal_dow"].to_pylist(), dtype="datetime64[us]")
    assert seasonal.max() >= np.datetime64("2025-12-31")
    assert seasonal.max() < np.datetime64("2026-01-01")
    # an hour profile gives whole seconds; none gives microseconds
    whole = np.asarray(
        generated["temporal/seasonal_both_bimodal"].to_pylist(), dtype="datetime64[us]"
    )
    assert (whole.astype("datetime64[s]") == whole).all()
    fine = np.asarray(generated["temporal/seasonal_month"].to_pylist(), dtype="datetime64[us]")
    assert (fine.astype("datetime64[s]") == fine).mean() < 0.01
    ref = np.asarray(generated["temporal/range_ref"].to_pylist(), dtype="datetime64[us]")
    assert ref.min() >= np.datetime64("2021-05-01") and ref.max() < np.datetime64("2022-05-01")
    short = np.asarray(
        generated["temporal/seasonal_short_range"].to_pylist(), dtype="datetime64[us]"
    )
    assert short.min() >= np.datetime64("2024-03-01") and short.max() < np.datetime64("2024-05-16")


def test_temporal_bimodal_hours_wrap_around_midnight(generated):
    t = np.asarray(generated["temporal/seasonal_bimodal_wrap"].to_pylist(), dtype="datetime64[us]")
    hours = ((t - t.astype("datetime64[D]")) // np.timedelta64(1, "h")).astype(int)
    share = np.bincount(hours, minlength=24) / len(hours)
    # Each peak puts about 13% of its mass on its own hour and spills into the neighbouring
    # hours, across midnight (a clipped tail would pile it on hour 23 and hour 0).
    assert 0.15 < share[[22, 3]].sum() < 0.18 and share[[23, 0, 1, 2]].min() > 0.04


def test_temporal_empty_bucket_probability_is_spread_over_the_range():
    from shape.builtins.strategies.temporal import _day_weights

    month_p = np.full(12, 1 / 12)
    dow_p = np.full(7, 1 / 7)
    first = int(np.datetime64("2024-03-01", "D").astype(np.int64))
    w = _day_weights(first, 76, month_p, dow_p)
    assert abs(w.sum() - 1.0) < 1e-12 and w[-1] < w[:-1].max() and (w > 0).all()
    # a range covering every bucket spreads nothing
    full = _day_weights(first, 800, month_p, dow_p)
    assert abs(full.sum() - 1.0) < 1e-12


@pytest.mark.parametrize(
    ("spec", "message"),
    [
        ({"start": "not a date"}, "start 'not a date' is not an ISO date"),
        ({"start": "2023-05-02", "end": "2023-05-01"}, "is before the start"),
        ({"start": "2023-05-01T08:00", "end": "2023-05-01T08:00"}, "end equals the start"),
        (
            {"pattern": "seasonal", "start": "2023-05-02", "end": "2023-05-01"},
            "is before the start",
        ),
        ({"pattern": "seasonal", "profiles": {"month": {"Jan": -1}}}, "non-negative"),
        (
            {
                "pattern": "seasonal",
                "profiles": {
                    "month": {
                        "Jan": 0,
                        "Feb": 0,
                        "Mar": 0,
                        "Apr": 0,
                        "May": 0,
                        "Jun": 0,
                        "Jul": 0,
                        "Aug": 0,
                        "Sep": 0,
                        "Oct": 0,
                        "Nov": 0,
                        "Dec": 0,
                    }
                },
            },
            "positive sum",
        ),
        (
            {
                "pattern": "seasonal",
                "profiles": {"hour_of_day": {"distribution": "bimodal", "std_dev": 0}},
            },
            "positive std_dev",
        ),
    ],
)
def test_temporal_bad_specs(spec, message):
    case = {
        "strategy": "temporal",
        "helpers": {},
        "regex": None,
        "column": cases_mod._col("x", "timestamp", {"strategy": "temporal", **spec}),
    }
    engine = Engine(schema_import.import_dump(cases_mod.schema_for(case, rows=10)), seed=1)
    with pytest.raises(ValueError, match=re.escape(message)):
        engine.generate_table("t")


# ---------------------------------------------------------------- the permutation


@pytest.mark.parametrize("n", [1, 2, 3, 7, 60, 1000, 4097, 65_537])
def test_permutation_is_a_bijection_evaluated_row_by_row(n):
    key = (0xDEADBEEF << 64) | 12345
    whole = permute(np.arange(n), n, key)
    assert sorted(whole.tolist()) == list(range(n))
    probe = np.array([0, n - 1, n // 2], dtype=np.int64)
    assert permute(probe, n, key).tolist() == whole[probe].tolist()
    if n > 7:
        assert permute(np.arange(n), n, key + 1).tolist() != whole.tolist()
        assert whole.tolist() != list(range(n))


def test_permutation_is_well_mixed():
    n = 10_000
    p = permute(np.arange(n), n, 99)
    # first-half rows land in the first half of the range about half of the time
    assert abs((p[: n // 2] < n // 2).mean() - 0.5) < 0.03
    assert abs(np.corrcoef(np.arange(n), p)[0, 1]) < 0.05
    with pytest.raises(ValueError):
        permute(np.arange(3), 0, 1)


@pytest.mark.parametrize(
    "module",
    ["shape.generation.lookup", "shape.generation.reference", "shape.generation.permutation"],
)
def test_stable_names_exist_and_are_documented(module):
    import importlib

    doc = importlib.import_module(module).__doc__ or ""
    m = re.search(r"Stable interface:(.*?)(?:\n\n|\Z)", doc, re.S)
    assert m, module
    names = re.findall(r"``(\w+)``", m.group(1))
    page = (ROOT / "docs" / "GENERATION_STRATEGIES.md").read_text("utf-8")
    assert names
    for name in names:
        assert hasattr(importlib.import_module(module), name), name
        assert name in page, f"{module}.{name} is not in docs/GENERATION_STRATEGIES.md"
