"""P4-07: the retail domain (``shape.domains`` entry ``retail``) generated by the product engine.

The plugin ships the schema and the four reference datasets. These tests check what it hands the
engine, and what the engine makes of it: the nine tables and their row counts at every scale, the
Arrow types of the baseline's output, output that does not depend on the chunk size, referential
integrity, the business rules, and the same schema as the baseline's dump. The statistical
comparison with the baseline is ``domain_1to1/verify.py --domain retail --impl shape``."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pyarrow as pa
import pyarrow.compute as pc
import pytest

from shape.generation.domains import DomainNotFoundError, domain_names, load_domain
from shape.generation.engine import Engine
from shape.generation.rules import validate_rules
from shape.plugins import kit
from shape.plugins.host import default_host

ROOT = Path(__file__).resolve().parents[2]
BENCH = ROOT / "benchmarks" / "vs_spindle"
sys.path.insert(0, str(BENCH))

import schema_import  # noqa: E402

TABLES = [
    "customer",
    "product_category",
    "promotion",
    "store",
    "address",
    "product",
    "order",
    "order_line",
    "return",
]
ROWS = {
    "small": [1_000, 50, 200, 150, 1_500, 500, 5_000, 12_500, 850],
    "medium": [50_000, 50, 200, 150, 75_000, 5_000, 500_000, 1_250_000, 85_000],
    "large": [500_000, 50, 200, 150, 750_000, 25_000, 5_000_000, 12_500_000, 850_000],
    "xlarge": [5_000_000, 50, 200, 150, 7_500_000, 100_000, 100_000_000, 250_000_000, 17_000_000],
}
TYPES = {
    ("customer", "signup_date"): pa.timestamp("ns"),
    ("promotion", "start_date"): pa.timestamp("ns"),
    ("promotion", "end_date"): pa.timestamp("ns"),
    ("order", "order_date"): pa.timestamp("us"),
    ("return", "return_date"): pa.timestamp("us"),
    ("customer", "customer_id"): pa.int64(),
    ("product", "unit_price"): pa.float64(),
    ("address", "is_primary"): pa.bool_(),
    ("customer", "email"): pa.string(),
}


@pytest.fixture(scope="module")
def retail():
    return load_domain("retail")


@pytest.fixture(scope="module")
def small(retail):
    return Engine(retail.schema, scale="small", seed=1042).generate()


def test_the_domain_is_discovered_and_conforms():
    assert "retail" in domain_names()
    kit.check_domain(default_host().get("shape.domains", "retail"))


def test_an_unknown_domain_names_the_installed_ones():
    with pytest.raises(DomainNotFoundError, match="retail"):
        load_domain("no_such_domain")


def test_the_definition_carries_reference_data_and_presets(retail):
    ref = retail.definition.reference_data
    assert {k: v.num_rows for k, v in ref.items()} == {
        "categories": 50,
        "product_names": 114,
        "promo_names": 50,
        "us_zip_locations": 40_977,
    }
    assert ref["us_zip_locations"].column_names == ["zip", "city", "state", "lat", "lng"]
    assert set(retail.definition.scale_presets) >= {"small", "medium", "large", "xlarge"}
    assert retail.definition.scale_presets["medium"]["order"] == 500_000


def test_the_schema_is_the_baselines_with_nanosecond_dates(retail):
    """The shipped schema is the baseline's retail dump, imported (P4-01a), with only the
    ``unit: ns`` of its uniform temporal columns added."""
    dump = json.loads((BENCH / "fixtures" / "schemas" / "retail_3nf.json").read_text("utf-8"))
    mine = retail.schema.to_dict()
    expected = schema_import.import_dump(dump).to_dict()
    for table in mine["tables"].values():
        for col in table["columns"].values():
            gen = col["generator"]
            if gen.get("unit") == "ns":
                assert col["name"] in ("signup_date", "start_date")
                del gen["unit"]
    assert mine == expected


@pytest.mark.parametrize("scale", sorted(ROWS))
def test_row_counts_equal_the_baselines_at_every_scale(retail, scale):
    counts = Engine(retail.schema, scale=scale, seed=1).row_counts
    assert [counts[t] for t in TABLES] == ROWS[scale]


def test_small_tables_columns_and_order(small):
    assert set(small.tables) == set(TABLES)
    assert {n: t.num_rows for n, t in small.tables.items()} == dict(
        zip(TABLES, ROWS["small"], strict=True)
    )
    assert small.tables["order_line"].column_names == [
        "order_line_id",
        "order_id",
        "product_id",
        "quantity",
        "promotion_id",
        "unit_price",
        "discount_percent",
        "line_total",
    ]
    assert small.tables["product"].column_names == [
        "product_id",
        "category_id",
        "product_name",
        "unit_price",
        "product_status",
        "cost",
    ]


@pytest.mark.parametrize(("key", "type_"), list(TYPES.items()))
def test_arrow_types_equal_the_baselines(small, key, type_):
    table, column = key
    assert small.tables[table].schema.field(column).type == type_


def test_foreign_keys_are_whole(small):
    t = small.tables
    pairs = [
        ("address", "customer_id", "customer", "customer_id"),
        ("product", "category_id", "product_category", "category_id"),
        ("product_category", "parent_category_id", "product_category", "category_id"),
        ("order", "customer_id", "customer", "customer_id"),
        ("order", "store_id", "store", "store_id"),
        ("order", "shipping_address_id", "address", "address_id"),
        ("order", "promotion_id", "promotion", "promotion_id"),
        ("order_line", "order_id", "order", "order_id"),
        ("order_line", "product_id", "product", "product_id"),
        ("order_line", "promotion_id", "promotion", "promotion_id"),
        ("return", "order_id", "order", "order_id"),
    ]
    for child, col, parent, key in pairs:
        values = t[child][col].drop_null()
        assert pc.all(pc.is_in(values, value_set=t[parent][key])).as_py(), (child, col)


def test_business_rules_hold_and_totals_add_up(retail, small):
    assert validate_rules(small.tables, retail.schema) == []
    assert small.remaining_violations == []
    lines = small.tables["order_line"]
    sums = pc.sum(lines["line_total"]).as_py()
    assert pc.sum(small.tables["order"]["order_total"]).as_py() == pytest.approx(sums, rel=1e-9)


def test_output_does_not_depend_on_the_chunk_size(retail):
    whole = Engine(retail.schema, scale="small", seed=7, chunk_rows=1_000).generate()
    other = Engine(retail.schema, scale="small", seed=7, chunk_rows=65_536).generate()
    for name in TABLES:
        assert whole.tables[name].equals(other.tables[name]), name


def test_the_same_seed_gives_the_same_tables_and_another_seed_does_not(retail):
    a = Engine(retail.schema, scale="small", seed=1).generate()
    b = Engine(retail.schema, scale="small", seed=1).generate()
    c = Engine(retail.schema, scale="small", seed=2).generate()
    assert all(a.tables[t].equals(b.tables[t]) for t in TABLES)
    assert not a.tables["order"].equals(c.tables["order"])


def test_a_temporal_unit_changes_the_type_not_the_instants(retail):
    from shape.builtins.strategies.temporal import Temporal
    from shape.generation.engine import EngineContext  # noqa: F401
    from shape.plugins.api.v1 import GenerationContext

    ctx = GenerationContext(seed=3, table="t", column="c", chunk=0, row_start=0, n_rows=50)
    spec = {"pattern": "uniform", "start": "2023-01-01", "end": "2023-12-31"}
    us = Temporal().generate(spec, ctx)
    ns = Temporal().generate({**spec, "unit": "ns"}, ctx)
    assert us.type == pa.timestamp("us") and ns.type == pa.timestamp("ns")
    assert ns.cast(pa.timestamp("us")).equals(us)
    from shape.generation.strategy_kit import StrategyError

    with pytest.raises(StrategyError, match="unit"):
        Temporal().generate({**spec, "unit": "fortnight"}, ctx)


def test_threads_do_not_change_the_retail_tables(retail, small, monkeypatch):
    monkeypatch.setenv("SHAPE_THREADS", "1")
    one = Engine(retail.schema, scale="small", seed=1042).generate()
    monkeypatch.setenv("SHAPE_THREADS", "4")
    four = Engine(retail.schema, scale="small", seed=1042, chunk_rows=700).generate()
    for name in TABLES:
        assert one.tables[name].equals(small.tables[name]), name
        assert four.tables[name].equals(small.tables[name]), name


def test_written_parquet_equals_the_generated_tables(retail, small, tmp_path):
    import pyarrow.parquet as pq

    from shape.generation.output import write_engine

    write_engine(Engine(retail.schema, scale="small", seed=1042), "parquet", tmp_path)
    for name in TABLES:
        assert pq.read_table(tmp_path / f"{name}.parquet").equals(small.tables[name]), name


def test_tables_are_handed_to_the_writer_before_the_last_validation(retail, monkeypatch):
    """``order`` is final once its computed total and its date repair are in; the validation that
    follows (and the repairs of later rules) must not delay it."""
    import shape.generation.engine as engine_module

    events: list[str] = []
    real = engine_module.validate_rules
    monkeypatch.setattr(
        engine_module,
        "validate_rules",
        lambda *a, **k: (events.append("validate"), real(*a, **k))[1],
    )
    Engine(retail.schema, scale="small", seed=1).generate(
        on_table=lambda name, table: events.append(name)
    )
    assert events.index("order") < events.index("validate")
    assert events.index("product") < events.index("validate")
    assert sorted(e for e in events if e != "validate") == sorted(TABLES)
