"""P4-04d: foreign_key, composite_foreign_key, composite_fk_field, first_per_parent,
self_referencing, self_ref_field, lifecycle and scd2.

Every case of ``benchmarks/vs_spindle/strategy_1to1/relational_cases.py`` (a multi-table schema per
configuration) is generated by the engine at Shape's fixed seed (1042) and compared, under T-21
clauses (b)-(f), with the baseline's observations at its fixed seeds 43-46
(``fixtures/strategies/*.json``, regenerated and checked by ``relational_baseline.py --check``).
Nothing here needs the baseline's venv.
"""

from __future__ import annotations

import copy
import datetime as dt
import importlib.util
import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import numpy as np
import pyarrow as pa
import pytest

from shape.generation.engine import Engine
from shape.kernel import dispatch

ROOT = Path(__file__).resolve().parents[2]
BENCH = ROOT / "benchmarks" / "vs_spindle"
S1 = BENCH / "strategy_1to1"
sys.path.insert(0, str(S1))
sys.path.insert(0, str(BENCH))

import fingerprint  # noqa: E402
import relational_cases as rc  # noqa: E402
import relational_compare as rcmp  # noqa: E402

_spec = importlib.util.spec_from_file_location(
    "vs_spindle_schema_import", BENCH / "schema_import.py"
)
assert _spec and _spec.loader
schema_import = importlib.util.module_from_spec(_spec)
sys.modules["vs_spindle_schema_import"] = schema_import
_spec.loader.exec_module(schema_import)

SHAPE_SEED = 1042
BASELINE_SEEDS = [43, 44, 45, 46]
STRATEGIES = (
    "foreign_key",
    "composite_foreign_key",
    "first_per_parent",
    "self_referencing",
    "lifecycle",
    "scd2",
)
FIXTURES = {
    s: json.loads((BENCH / "fixtures" / "strategies" / f"{s}.json").read_text("utf-8"))
    for s in STRATEGIES
}


def _schema_for(*args: Any, **kwargs: Any) -> dict[str, Any]:
    """A private copy of a case's schema: tests edit what they get, and the case harness
    shares dicts with its module-level cases (#329)."""
    return copy.deepcopy(rc.schema_for(*args, **kwargs))


def _engine(case: dict[str, Any], seed: int = SHAPE_SEED, **kw: Any) -> Engine:
    return Engine(schema_import.import_dump(_schema_for(case)), seed=seed, **kw)


def _lists(tables: dict[str, pa.Table]) -> dict[str, dict[str, list[Any]]]:
    return {n: {c: t[c].to_pylist() for c in t.column_names} for n, t in tables.items()}


@pytest.fixture(scope="module")
def generated() -> dict[str, dict[str, dict[str, list[Any]]]]:
    return {cid: _lists(_engine(case).generate().tables) for cid, case in rc.CASES.items()}


def _fails(case_id: str, tables: dict[str, dict[str, list[Any]]]) -> list[str]:
    case = rc.CASES[case_id]
    fx = FIXTURES[case["strategy"]]["cases"][case_id]["observations"]
    out: list[str] = []
    for name, values in rc.observe(case, tables).items():
        out += [f"{name}: {m}" for m in rcmp.check(name, fingerprint.fingerprint(values), fx[name])]
    return out


def test_fixtures_cover_every_case_and_the_fixed_seed_set():
    assert set(STRATEGIES) == set(rc.strategies())
    for cid, case in rc.CASES.items():
        fx = FIXTURES[case["strategy"]]
        assert fx["seeds"] == BASELINE_SEEDS, "T-21: the baseline seeds are exactly 43, 44, 45, 46"
        entry = fx["cases"][cid]
        assert set(entry["observations"]) == set(rc.observe(case, _tiny(case)))
        assert all(len(v) == 4 for v in entry["observations"].values())
        assert len(entry["invariants"]) == 4
    assert {c for fx in FIXTURES.values() for c in fx["cases"]} == set(rc.CASES)


def _tiny(case: dict[str, Any]) -> dict[str, dict[str, list[Any]]]:
    """A small generated copy of a case (to learn the names it observes)."""
    small = json.loads(json.dumps(case))
    for spec in small["tables"].values():
        spec["rows"] = min(spec["rows"], 60)
    return _lists(_engine(small).generate().tables)


@pytest.mark.parametrize("case_id", sorted(rc.CASES))
def test_equivalent_to_the_baseline(case_id, generated):
    assert _fails(case_id, generated[case_id]) == []


@pytest.mark.parametrize("case_id", sorted(rc.CASES))
def test_exact_invariants_hold_in_the_baseline_and_in_shape(case_id, generated):
    case = rc.CASES[case_id]
    for seed_facts in FIXTURES[case["strategy"]]["cases"][case_id]["invariants"]:
        assert all(v is True for v in seed_facts.values()), seed_facts
    facts = rc.invariants(case, generated[case_id])
    assert facts and all(v is True for v in facts.values()), facts


@pytest.mark.parametrize("case_id", sorted(rc.CASES))
def test_table_shapes_and_integrity(case_id):
    case = rc.CASES[case_id]
    result = _engine(case).generate()
    assert {n: t.num_rows for n, t in result.tables.items()} == {
        n: spec["rows"] for n, spec in case["tables"].items()
    }
    assert result.verify_integrity() == []


@pytest.mark.parametrize("case_id", sorted(rc.CASES))
def test_identical_for_any_chunking_and_random_access(case_id):
    case = json.loads(json.dumps(rc.CASES[case_id]))
    for spec in case["tables"].values():
        spec["rows"] = min(spec["rows"], 12_000) if spec["rows"] > 400 else spec["rows"]
    engine = _engine(case)
    for name, spec in case["tables"].items():
        rows = spec["rows"]
        whole = engine.generate_table(name, chunk_rows=rows)
        for chunk in (1_000, 4_093):
            assert engine.generate_table(name, chunk_rows=chunk).equals(whole), (name, chunk)
        lo = rows // 3
        piece = engine.generate_chunk(name, lo, min(777, rows - lo))
        assert pa.Table.from_batches([piece]).equals(whole.slice(lo, piece.num_rows)), name
    # a fresh engine reading the last chunk first (cold caches) gives the same rows
    fresh = _engine(case)
    name = next(reversed(case["tables"]))
    rows = case["tables"][name]["rows"]
    tail = fresh.generate_chunk(name, max(rows - 500, 0), min(500, rows))
    assert pa.Table.from_batches([tail]).equals(
        engine.generate_table(name, chunk_rows=rows).slice(max(rows - 500, 0), tail.num_rows)
    )


@pytest.mark.parametrize("case_id", sorted(rc.CASES))
def test_deterministic_and_seeds_differ(case_id):
    case = json.loads(json.dumps(rc.CASES[case_id]))
    for spec in case["tables"].values():
        spec["rows"] = min(spec["rows"], 3_000) if spec["rows"] > 400 else spec["rows"]
    a = _engine(case).generate().tables
    b = _engine(case).generate().tables
    assert all(a[n].equals(b[n]) for n in a)
    other = _engine(case, seed=SHAPE_SEED + 1).generate().tables
    if case_id != "self_referencing/one_level":  # every row is a root: nothing is random
        assert any(not a[n].equals(other[n]) for n in a)


def test_the_comparison_can_fail():
    """Negative controls: each wrong setting is caught by the comparison that passes above."""

    def fails(case_id: str, mutate: dict[str, Any], table: str, column: str) -> list[str]:
        case = json.loads(json.dumps(rc.CASES[case_id]))
        case["tables"][table]["columns"][column]["generator"].update(mutate)
        return _fails(case_id, _lists(_engine(case).generate().tables))

    assert fails("foreign_key/uniform", {"distribution": "zipf", "alpha": 1.2}, "c", "x")
    assert fails("foreign_key/zipf_top_level_alpha", {"alpha": 1.5}, "c", "x")
    assert fails("foreign_key/zipf_top_level_alpha", {"distribution": "pareto"}, "c", "x")
    assert fails("foreign_key/pareto_capped", {"max_per_parent": 80}, "c", "x")
    assert fails("foreign_key/pareto", {"alpha": 2.0}, "c", "x")
    assert fails("foreign_key/nullable", {}, "c", "x") == []
    assert fails("foreign_key/self_reference", {"distribution": "uniform"}, "e", "mgr") == []
    assert fails("composite_foreign_key/zipf", {"params": {"alpha": 2.0}}, "ret", "a")
    assert fails("composite_foreign_key/uniform", {"distribution": "zipf"}, "ret", "a")
    assert fails(
        "lifecycle/three_phases",
        {"phases": {"introduced": 0.2, "active": 0.65, "discontinued": 0.15}},
        "t",
        "x",
    )
    assert fails(
        "lifecycle/three_phases",
        {"phases": {"introduced": 0.1, "active": 0.75, "retired": 0.15}},
        "t",
        "x",
    )
    assert fails("self_referencing/levels3_roots8", {"levels": 4}, "cat", "parent_category_id")
    assert fails("self_referencing/levels3_roots8", {"root_count": 40}, "cat", "parent_category_id")
    assert fails("scd2/default_gap", {"min_gap_days": 30}, "dim", "effective_date")
    assert fails("scd2/default_gap", {"role": "is_current"}, "dim", "end_date")


def test_first_per_parent_negative_control():
    case = json.loads(json.dumps(rc.CASES["first_per_parent/default_true"]))
    tables = _lists(_engine(case).generate().tables)
    flipped = {**tables, "c": {**tables["c"], "flag": [not v for v in tables["c"]["flag"]]}}
    assert _fails("first_per_parent/default_true", flipped)
    assert not all(rc.invariants(rc.CASES["first_per_parent/default_true"], flipped).values())


# ---------------------------------------------------------------- behaviours


def _case(tables: dict[str, Any], observe_: dict[str, Any] | None = None) -> dict[str, Any]:
    return {"strategy": "x", "observer": "fk", "tables": tables, "observe": observe_ or {}}


def _t(rows: int, pk: list[str], **columns: dict[str, Any]) -> dict[str, Any]:
    return {"rows": rows, "pk": pk, "columns": columns}


def _col(name: str, strategy: str, type_: str = "integer", **spec: Any) -> dict[str, Any]:
    return rc.base._col(name, type_, {"strategy": strategy, **spec})


def test_foreign_key_capped_never_exceeds_the_cap_and_keeps_integrity():
    case = rc.CASES["foreign_key/pareto_capped"]
    engine = _engine(case)
    column = engine.generate().tables["c"]["x"].to_pylist()
    assert max(Counter(column).values()) <= 40
    assert len(set(column)) == 3_000, "every parent is used when the cap forces the spread"


def test_foreign_key_zipf_truncated_to_the_pool_has_the_right_shape():
    from shape.builtins.strategies._relational import ZIPF_HEAD, zipf_index

    u = (np.arange(400_000) + 0.5) / 400_000
    for pool, alpha in ((50, 1.2), (3_000, 1.5), (ZIPF_HEAD, 1.1)):
        idx = zipf_index(u, pool, alpha)
        assert idx.min() == 0 and idx.max() <= pool - 1
        weights = np.arange(1, pool + 1, dtype=np.float64) ** (-alpha)
        want = (weights / weights.sum())[:5]
        got = np.bincount(idx, minlength=5)[:5] / len(u)
        assert np.allclose(got, want, rtol=0.02, atol=1e-4), (pool, alpha, got, want)
    # a pool beyond the exact table: its tail is integrated, and its mass must match the power law
    for pool, alpha in ((3_000_000, 1.2), (3_000_000, 1.0), (50_000_000, 0.8)):
        idx = zipf_index(u, pool, alpha)
        assert idx.min() == 0 and idx.max() <= pool - 1
        low, high = ZIPF_HEAD + 0.5, pool + 0.5
        exact = (np.arange(1, ZIPF_HEAD + 1, dtype=np.float64) ** (-alpha)).sum()
        tail = (
            np.log(high / low)
            if alpha == 1.0
            else (low ** (1 - alpha) - high ** (1 - alpha)) / (alpha - 1)
        )
        assert abs((idx >= ZIPF_HEAD).mean() - tail / (exact + tail)) < 0.002, (pool, alpha)


def test_foreign_key_constrained_without_address_is_null_or_any_parent():
    for nullable in (True, False):
        cust = _t(50, ["cid"], cid=_col("cid", "sequence"))
        addr = _t(
            10,
            ["aid"],
            aid=_col("aid", "sequence"),
            cid=_col("cid", "foreign_key", ref="cust.cid"),
        )
        order = rc.base._col(
            "aid",
            "integer",
            {"strategy": "foreign_key", "ref": "addr.aid", "constrained_by": "cid"},
            nullable=nullable,
        )
        child = _t(
            2_000,
            ["oid"],
            oid=_col("oid", "sequence"),
            cid=_col("cid", "foreign_key", ref="cust.cid"),
            aid=order,
        )
        tables = _lists(
            _engine(_case({"cust": cust, "addr": addr, "ord": child})).generate().tables
        )
        owner = dict(zip(tables["addr"]["aid"], tables["addr"]["cid"], strict=True))
        has = set(owner.values())
        for aid, cid in zip(tables["ord"]["aid"], tables["ord"]["cid"], strict=True):
            if cid in has:
                assert owner[aid] == cid
            elif nullable:
                assert aid is None
            else:
                assert aid in owner


def test_foreign_key_constrained_by_a_column_that_is_not_there_draws_from_all_parents():
    parent = _t(30, ["pid"], pid=_col("pid", "sequence"))
    child = _t(
        500,
        ["id"],
        id=_col("id", "sequence"),
        x=_col("x", "foreign_key", ref="p.pid", constrained_by="missing"),
    )
    values = _lists(_engine(_case({"p": parent, "c": child})).generate().tables)["c"]["x"]
    assert len(set(values)) > 20 and set(values) <= set(range(1, 31))


def test_foreign_key_sample_with_a_filter_uses_only_matching_parents():
    parent = _t(
        400,
        ["pid"],
        pid=_col("pid", "sequence"),
        kind=_col("kind", "weighted_enum", "string", values={"open": 1, "closed": 1}),
    )
    child = _t(
        20,
        ["id"],
        id=_col("id", "sequence"),
        x=_col("x", "foreign_key", ref="p.pid", sample_rate=0.25, filter="kind = 'open'"),
    )
    tables = _lists(_engine(_case({"p": parent, "c": child})).generate().tables)
    open_ids = {
        p for p, k in zip(tables["p"]["pid"], tables["p"]["kind"], strict=True) if k == "open"
    }
    got = tables["c"]["x"]
    assert set(got) <= open_ids and len(set(got)) == 20


def test_foreign_key_sample_wraps_when_the_child_has_more_rows_than_the_sample():
    parent = _t(40, ["pid"], pid=_col("pid", "sequence"))
    child = _t(
        25,
        ["id"],
        id=_col("id", "sequence"),
        x=_col("x", "foreign_key", ref="p.pid", sample_rate=0.2),
    )
    got = _lists(_engine(_case({"p": parent, "c": child})).generate().tables)["c"]["x"]
    assert len(set(got)) == 8 and got[:8] == got[8:16]


def test_foreign_key_to_a_column_that_is_not_the_key():
    parent = _t(
        20,
        ["pid"],
        pid=_col("pid", "sequence"),
        code=_col("code", "pattern", "string", format="C{seq:3}"),
    )
    child = _t(
        300, ["id"], id=_col("id", "sequence"), x=_col("x", "foreign_key", "string", ref="p.code")
    )
    values = _lists(_engine(_case({"p": parent, "c": child})).generate().tables)["c"]["x"]
    assert set(values) <= {f"C{i:03d}" for i in range(1, 21)} and len(set(values)) > 10


def test_foreign_key_self_reference_with_a_uuid_key():
    emp = _t(
        500,
        ["eid"],
        eid=_col("eid", "uuid", "string"),
        mgr=_col("mgr", "foreign_key", "string", ref="e.eid"),
    )
    tables = _lists(_engine(_case({"e": emp})).generate().tables)["e"]
    assert set(tables["mgr"]) <= set(tables["eid"]) and len(set(tables["mgr"])) > 100


@pytest.mark.parametrize(
    ("spec", "message"),
    [
        ({"strategy": "foreign_key"}, "requires 'ref'"),
        ({"strategy": "foreign_key", "ref": "nodot"}, "format 'table.column'"),
        ({"strategy": "foreign_key", "ref": "nope.id"}, "there is no table 'nope'"),
        ({"strategy": "foreign_key", "ref": "p.nope"}, "has no column 'nope'"),
        (
            {"strategy": "foreign_key", "ref": "p.pid", "distribution": "zipf", "alpha": 0},
            "alpha must be positive",
        ),
        (
            {
                "strategy": "foreign_key",
                "ref": "p.pid",
                "distribution": "pareto",
                "max_per_parent": 0,
            },
            "max_per_parent must be positive",
        ),
        (
            {"strategy": "foreign_key", "ref": "p.pid", "sample_rate": "x"},
            "sample_rate must be a number",
        ),
        (
            {
                "strategy": "foreign_key",
                "ref": "p.pid",
                "sample_rate": 0.1,
                "filter": "kind = 'nothing'",
            },
            "has no column 'kind'",
        ),
        ({"strategy": "composite_foreign_key", "ref_columns": ["pid"]}, "'ref_table' is required"),
        (
            {"strategy": "composite_foreign_key", "ref_table": "p"},
            "'ref_columns' must be a non-empty list",
        ),
        (
            {"strategy": "composite_foreign_key", "ref_table": "q", "ref_columns": ["a"]},
            "there is no table 'q'",
        ),
        (
            {"strategy": "composite_foreign_key", "ref_table": "p", "ref_columns": ["zz"]},
            "ref_column 'zz' not found",
        ),
        ({"strategy": "composite_fk_field", "source_column": "x"}, "are required"),
        (
            {"strategy": "composite_fk_field", "source_column": "id", "ref_column": "pid"},
            "not found",
        ),
        ({"strategy": "first_per_parent"}, "requires 'parent_column'"),
        ({"strategy": "first_per_parent", "parent_column": "ghost"}, "has not been generated yet"),
        ({"strategy": "self_referencing", "pk_column": "nope"}, "pk_column 'nope' not found"),
        (
            {"strategy": "self_referencing", "pk_column": "id", "levels": 0},
            "levels must be at least 1",
        ),
        ({"strategy": "self_ref_field", "field": "level"}, "could not find '_sr_c_level'"),
        ({"strategy": "lifecycle"}, "requires a non-empty 'phases'"),
        ({"strategy": "lifecycle", "phases": {"a": -1}}, "non-negative"),
        ({"strategy": "lifecycle", "phases": {"a": 0}}, "positive sum"),
        ({"strategy": "scd2", "role": "version"}, "requires 'business_key'"),
        (
            {"strategy": "scd2", "role": "version", "business_key": "later"},
            "must be generated before",
        ),
        ({"strategy": "scd2", "role": "nope", "business_key": "id"}, "unknown role 'nope'"),
        (
            {"strategy": "scd2", "role": "end_date", "business_key": "id"},
            "requires the effective date column",
        ),
        (
            {"strategy": "scd2", "role": "version", "business_key": "id", "min_gap_days": -1},
            "must not be negative",
        ),
    ],
)
def test_bad_specs_name_the_column(spec, message):
    parent = _t(
        10,
        ["pid"],
        pid=_col("pid", "sequence"),
        a=_col("a", "sequence"),
        zz_unused=_col("zz_unused", "sequence"),
    )
    child = _t(
        10,
        ["id"],
        id=_col("id", "sequence"),
        x=rc.base._col("x", "integer", spec),
        later=_col("later", "sequence"),
    )
    case = _case({"p": parent, "c": child})
    # the schema validator accepts these specs (required keys are checked by the strategy)
    engine = Engine(schema_import.import_dump(_schema_for(case)), seed=1)
    with pytest.raises(ValueError, match=re.escape(message)) as err:
        engine.generate_table("c")
    assert "c.x" in str(err.value) or message in str(err.value)


def test_first_per_parent_is_marked_on_the_first_row_whatever_the_chunking():
    case = json.loads(json.dumps(rc.CASES["first_per_parent/zipf_parents"]))
    engine = _engine(case)
    parents = engine.generate_table("c")["cid"].to_pylist()
    flags = engine.generate_chunk("c", 40_000, 1_000).column("flag").to_pylist()  # read first
    seen: set[int] = set()
    first = []
    for p in parents:
        first.append(p not in seen)
        seen.add(p)
    assert flags == first[40_000:41_000]
    assert engine.generate_table("c")["flag"].to_pylist() == first


def test_first_per_parent_counts_nulls_as_one_parent():
    case = {
        "strategy": "first_per_parent",
        "observer": "first",
        "tables": {
            **rc._parent(50),
            "c": rc._table(
                400,
                ["id"],
                {
                    "id": rc._id(),
                    "cid": rc._fk("cid", "p.pid", nullable=True, null_rate=0.4),
                    "flag": rc.base._col(
                        "flag", "boolean", {"strategy": "first_per_parent", "parent_column": "cid"}
                    ),
                },
            ),
        },
        "observe": {},
    }
    t = _lists(_engine(case).generate().tables)["c"]
    nulls = [f for p, f in zip(t["cid"], t["flag"], strict=True) if p is None]
    assert sum(nulls) == 1 and nulls[0] is True
    assert sum(t["flag"]) == len({p for p in t["cid"]})


def test_self_referencing_with_a_non_sequence_key_and_hierarchy_shape():
    cols = {
        "category_id": _col("category_id", "uuid", "string"),
        "parent_category_id": _col(
            "parent_category_id",
            "self_referencing",
            "string",
            pk_column="category_id",
            levels=3,
            root_count=4,
        ),
        "level": _col("level", "self_ref_field", field="level"),
    }
    t = _lists(_engine(_case({"cat": _t(400, ["category_id"], **cols)})).generate().tables)["cat"]
    level = dict(zip(t["category_id"], t["level"], strict=True))
    assert Counter(t["level"]) == {1: 4, 2: 198, 3: 198}
    for parent, lv in zip(t["parent_category_id"], t["level"], strict=True):
        assert (parent is None) == (lv == 1)
        assert parent is None or level[parent] == lv - 1


def test_self_referencing_levels_follow_the_baseline_layout_exactly():
    from shape.builtins.strategies.hierarchy import level_bounds

    assert level_bounds(2_000, 3, 8) == ([0, 8, 1004], [8, 1004, 2000])
    assert level_bounds(25, 3, 8) == ([0, 8, 17], [8, 17, 25])  # 8 roots clamp to 25 // 3
    assert level_bounds(10, 4, 100) == ([0, 2, 5, 8], [2, 5, 8, 10])
    assert level_bounds(1_000, 1, 5) == ([0], [1_000])


def test_lifecycle_zero_weight_phase_never_appears(generated):
    assert "off" not in set(generated["lifecycle/zero_weight"]["t"]["x"])


def test_scd2_end_date_and_flags_in_a_hand_checked_table():
    raw = _schema_for(rc.CASES["scd2/gap_7_days"])
    raw["generation"]["scales"]["s"] = {"customer": 3, "dim": 12}
    raw["model"]["date_range"] = {"start": "2024-01-01", "end": "2024-12-31"}
    t = _lists(Engine(schema_import.import_dump(raw), seed=5).generate().tables)["dim"]
    by_key: dict[int, list[int]] = {}
    for i, key in enumerate(t["cust"]):
        by_key.setdefault(key, []).append(i)
    for rows in by_key.values():
        eff = [t["effective_date"][i] for i in rows]
        assert eff == sorted(eff) and all(
            b - a >= dt.timedelta(days=7) for a, b in zip(eff, eff[1:], strict=False)
        )
        assert [t["version"][i] for i in rows] == list(range(1, len(rows) + 1))
        assert [t["is_current"][i] for i in rows] == [False] * (len(rows) - 1) + [True]
        assert t["end_date"][rows[-1]] is None


def test_scd2_dates_stay_inside_the_model_window(generated):
    t = generated["scd2/short_window"]["dim"]
    assert min(t["effective_date"]) >= dt.datetime(2024, 1, 1)
    assert max(t["effective_date"]) <= dt.datetime(2024, 3, 1)


def test_scd2_is_current_and_version_without_an_effective_date_use_row_order():
    cols = {
        "id": _col("id", "sequence"),
        "k": _col("k", "foreign_key", ref="c.cid"),
        "ver": _col("ver", "scd2", role="version", business_key="k"),
        "cur": _col("cur", "scd2", "boolean", role="is_current", business_key="k"),
    }
    case = _case({"c": _t(5, ["cid"], cid=_col("cid", "sequence")), "d": _t(60, ["id"], **cols)})
    t = _lists(_engine(case).generate().tables)["d"]
    seen: Counter[int] = Counter()
    for key, ver in zip(t["k"], t["ver"], strict=True):
        seen[key] += 1
        assert ver == seen[key]
    last = {k: max(i for i, x in enumerate(t["k"]) if x == k) for k in set(t["k"])}
    assert [bool(c) for c in t["cur"]] == [last[k] == i for i, k in enumerate(t["k"])]


def test_scd2_null_business_keys_give_nulls():
    cols = {
        "id": _col("id", "sequence"),
        "k": rc.base._col(
            "k",
            "integer",
            {"strategy": "foreign_key", "ref": "c.cid"},
            nullable=True,
            null_rate=0.3,
        ),
        "effective_date": _col(
            "effective_date", "scd2", "date", role="effective_date", business_key="k"
        ),
        "ver": _col("ver", "scd2", role="version", business_key="k"),
    }
    case = _case({"c": _t(8, ["cid"], cid=_col("cid", "sequence")), "d": _t(200, ["id"], **cols)})
    t = _lists(_engine(case).generate().tables)["d"]
    assert any(k is None for k in t["k"])
    for k, eff, ver in zip(t["k"], t["effective_date"], t["ver"], strict=True):
        assert (k is None) == (eff is None) == (ver is None)


def test_composite_foreign_key_hands_every_column_of_one_parent_row():
    t = _lists(_engine(rc.CASES["composite_foreign_key/uniform"]).generate().tables)
    parent = set(zip(t["line"]["a"], t["line"]["b"], strict=True))
    assert set(zip(t["ret"]["a"], t["ret"]["b"], strict=True)) <= parent
    assert len(set(zip(t["ret"]["a"], t["ret"]["b"], strict=True))) > 2_900


def test_composite_foreign_key_names_that_are_not_columns_stay_internal():
    line = _t(
        40, ["a", "b"], a=_col("a", "sequence", start=100), b=_col("b", "sequence", start=5, step=3)
    )
    ret = _t(
        100,
        ["id"],
        id=_col("id", "sequence"),
        order_no=_col(
            "order_no", "composite_foreign_key", ref_table="line", ref_columns=["a", "b"]
        ),
        line_no=_col("line_no", "composite_fk_field", source_column="order_no", ref_column="b"),
    )
    result = _engine(_case({"line": line, "ret": ret})).generate()
    out = result.tables["ret"]
    assert set(out.column_names) == {"id", "order_no", "line_no"}
    assert "_cfo_order_no__b" not in out.column_names and "a" not in out.column_names
    pairs = {(100 + i, 5 + 3 * i) for i in range(40)}
    assert set(zip(out["order_no"].to_pylist(), out["line_no"].to_pylist(), strict=True)) <= pairs


# ---------------------------------------------------------------- the kernels


def _tables_under(
    kernel: str, monkeypatch: pytest.MonkeyPatch, case: dict[str, Any]
) -> dict[str, pa.Table]:
    monkeypatch.setenv("SHAPE_KERNEL", kernel)
    dispatch.reset()
    try:
        return _engine(case).generate().tables
    finally:
        monkeypatch.undo()
        dispatch.reset()


@pytest.mark.parametrize(
    "case_id",
    [
        "foreign_key/pareto_capped",
        "first_per_parent/zipf_parents",
        "scd2/skewed_business_keys",
        "scd2/default_gap",
        "self_referencing/levels3_roots8",
        "foreign_key/constrained_by",
        "composite_foreign_key/zipf",
    ],
)
def test_native_and_reference_kernels_generate_the_same_tables(case_id, monkeypatch):
    case = json.loads(json.dumps(rc.CASES[case_id]))
    for spec in case["tables"].values():
        spec["rows"] = min(spec["rows"], 4_000)
    native = _tables_under("rust", monkeypatch, case)
    twin = _tables_under("python", monkeypatch, case)
    assert all(native[n].equals(twin[n]) for n in native)


# ---------------------------------------------------------------- the documentation


def test_stable_names_exist_and_are_documented():
    import importlib

    docs = ROOT / "docs"
    text = (docs / "GENERATION_KERNEL.md").read_text("utf-8") + (
        docs / "GENERATION_STRATEGIES.md"
    ).read_text("utf-8")
    module = importlib.import_module("shape.generation.kernel_relational")
    names = re.findall(
        r"``(\w+)``", re.search(r"Stable interface:(.*?)(?:\n\n|\Z)", module.__doc__, re.S).group(1)
    )
    assert names
    for name in names:
        assert hasattr(module, name) and name in text, name
    engine_doc = (docs / "GENERATION_ENGINE.md").read_text("utf-8")
    assert "generate_column" in engine_doc and "cached" in engine_doc
    for strategy in (
        "foreign_key",
        "composite_foreign_key",
        "composite_fk_field",
        "first_per_parent",
        "self_referencing",
        "self_ref_field",
        "lifecycle",
        "scd2",
    ):
        assert f"### `{strategy}`" in text or f"`{strategy}`" in text, strategy
        assert strategy in (docs / "plugins" / "builtins.md").read_text("utf-8")


def test_foreign_key_fan_out_gives_the_configured_concentration():
    from shape.generation.fanout import top_share_of

    parent = _t(2_000, ["pid"], pid=_col("pid", "sequence"))
    child = _t(
        100_000,
        ["id"],
        id=_col("id", "sequence"),
        x=_col("x", "foreign_key", ref="p.pid", fan_out={"top_fraction": 0.2, "top_share": 0.8}),
    )
    engine = _engine(_case({"p": parent, "c": child}))
    column = np.asarray(engine.generate_table("c")["x"].to_pylist()) - 1
    assert abs(top_share_of(column, 2_000, 0.2) - 0.8) < 0.01
    again = _engine(_case({"p": parent, "c": child}))
    assert (
        again.generate_chunk("c", 70_000, 500)
        .column("x")
        .equals(engine.generate_table("c").column("x").slice(70_000, 500).combine_chunks())
    )
    bad = _t(
        10, ["id"], id=_col("id", "sequence"), x=_col("x", "foreign_key", ref="p.pid", fan_out=3)
    )
    with pytest.raises(ValueError, match="fan_out must be a mapping"):
        _engine(_case({"p": parent, "c": bad})).generate_table("c")
