"""P4-04b: faker, native, formula, derived and computed.

Every case of ``benchmarks/vs_spindle/strategy_1to1/cases_p404b.py`` is generated by the engine at
Shape's fixed seed (1042) and compared, under T-21 clauses (b)-(e), with the fingerprints of the
pinned baseline's strategy at its fixed seeds 43-46 (``fixtures/strategies/*.json``, rebuilt and
checked by ``baseline_p404b.py``). Nothing here needs the baseline's venv.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import re
import sys
import types
from collections.abc import Iterator, Mapping
from pathlib import Path
from typing import Any

import numpy as np
import pyarrow as pa
import pyarrow.compute as pc
import pytest

from shape.builtins.strategies import providers
from shape.builtins.strategies.derived import Computed, Derived
from shape.builtins.strategies.formula import Formula, compile_expression
from shape.generation.engine import Engine
from shape.generation.strategy_kit import StrategyError, stream

ROOT = Path(__file__).resolve().parents[2]
BENCH = ROOT / "benchmarks" / "vs_spindle"
S1 = BENCH / "strategy_1to1"
sys.path.insert(0, str(S1))
sys.path.insert(0, str(BENCH))

import cases_p404b as cases_mod  # noqa: E402
import fingerprint  # noqa: E402
import parts  # noqa: E402

_spec = importlib.util.spec_from_file_location(
    "vs_spindle_schema_import", BENCH / "schema_import.py"
)
assert _spec and _spec.loader
schema_import = importlib.util.module_from_spec(_spec)
sys.modules["vs_spindle_schema_import"] = schema_import
_spec.loader.exec_module(schema_import)

SHAPE_SEED = 1042
STRATEGIES = ("native", "faker", "formula", "derived", "computed")
CASES = cases_mod.CASES
FIXTURES = {
    s: json.loads((BENCH / "fixtures" / "strategies" / f"{s}.json").read_text("utf-8"))
    for s in STRATEGIES
}
POOLS = {
    name: providers.pool(name).to_pylist()
    for name in (
        "first_names last_names company_names street_names email_domains sentences uri_paths "
        "uri_domains us_states us_cities street_suffixes"
    ).split()
}


# ---------------------------------------------------------------- stand-ins for later packages


class StandInDates:
    """Uniform timestamps between ``start`` and ``end`` (the ``temporal`` strategy is another work
    package; what ``derived`` adds to a date does not depend on where the date came from)."""

    name = "test_dates"

    def generate(self, spec: Mapping[str, Any], ctx: Any) -> pa.Array:
        lo = int(np.datetime64(spec["start"], "us").astype(np.int64))
        hi = int(np.datetime64(spec["end"], "us").astype(np.int64))
        u = stream(ctx, "d").uniform(ctx.row_start, ctx.n_rows)
        return pa.array(lo + (u * (hi - lo)).astype(np.int64)).cast(pa.timestamp("us"))


class StandInForeignKey:
    """A uniformly drawn key of the referenced table (``foreign_key`` is another work package)."""

    name = "foreign_key"

    def generate(self, spec: Mapping[str, Any], ctx: Any) -> pa.Array:
        table = str(spec["ref"]).split(".")[0]
        pool = ctx.engine.key_pool(table)
        u = stream(ctx, "fk").uniform(ctx.row_start, ctx.n_rows)
        return pool.take(np.minimum((u * len(pool)).astype(np.int64), len(pool) - 1))


STAND_INS = {"test_dates": StandInDates(), "foreign_key": StandInForeignKey()}


def _engine(raw: dict[str, Any], seed: int = SHAPE_SEED, **kw: Any) -> Engine:
    return Engine(schema_import.import_dump(raw), seed=seed, strategies=STAND_INS, **kw)


def _case_engine(case_id: str, seed: int = SHAPE_SEED, **kw: Any) -> Engine:
    return _engine(cases_mod.schema_for(CASES[case_id], "shape"), seed, **kw)


class _Lazy(Mapping[str, list[Any]]):
    """A table's columns as Python lists, converted when first read."""

    def __init__(self, table: pa.Table) -> None:
        self._table = table
        self._cache: dict[str, list[Any]] = {}

    def __getitem__(self, key: str) -> list[Any]:
        if key not in self._cache:
            self._cache[key] = self._table.column(key).to_pylist()
        return self._cache[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self._table.column_names)

    def __len__(self) -> int:
        return self._table.num_columns


def _series(case_id: str, **kw: Any) -> list[Any]:
    result = _case_engine(case_id, **kw).generate()
    return parts.measure(
        CASES[case_id], {name: _Lazy(table) for name, table in result.tables.items()}
    )


@pytest.fixture(scope="module")
def generated() -> dict[str, list[Any]]:
    return {cid: _series(cid) for cid in CASES}


# ---------------------------------------------------------------- equivalence (T-21 b-e)


def test_fixtures_cover_every_case():
    for cid, case in CASES.items():
        fx = FIXTURES[case["strategy"]]
        assert cid in fx["cases"], cid
        assert fx["seeds"] == [43, 44, 45, 46] and fx["rows"] == cases_mod.ROWS
        assert len(fx["cases"][cid]["runs"]) == 4
    assert set(STRATEGIES) == set(cases_mod.strategies())


@pytest.mark.parametrize("strategy", ["native", "faker"])
def test_shape_pools_are_the_baselines(strategy):
    digests = FIXTURES[strategy]["pool_sha256"]
    assert set(digests) == set(POOLS)
    for name, entries in POOLS.items():
        text = "".join(f"{e}\n" for e in entries)
        assert hashlib.sha256(text.encode("utf-8")).hexdigest() == digests[name], name


@pytest.mark.parametrize("case_id", sorted(CASES))
def test_equivalent_to_the_baseline(case_id, generated):
    runs = FIXTURES[CASES[case_id]["strategy"]]["cases"][case_id]["runs"]
    series = generated[case_id]
    assert (
        parts.check_series(fingerprint.fingerprint(series), [r["fingerprint"] for r in runs]) == []
    )


@pytest.mark.parametrize("case_id", sorted(c for c in CASES if CASES[c]["parts"]))
def test_components_are_pool_members_with_the_baselines_frequencies(case_id, generated):
    runs = FIXTURES[CASES[case_id]["strategy"]]["cases"][case_id]["runs"]
    got = parts.parts_fingerprint(generated[case_id], CASES[case_id]["parts"], POOLS)
    assert parts.check_parts(got, [r["parts"] for r in runs]) == []


@pytest.mark.parametrize("case_id", sorted(c for c in CASES if CASES[c]["regex"]))
def test_values_follow_the_pattern(case_id, generated):
    rx = re.compile(CASES[case_id]["regex"])
    bad = [v for v in generated[case_id] if v is not None and not rx.fullmatch(v)]
    assert bad == []
    for run in FIXTURES[CASES[case_id]["strategy"]]["cases"][case_id]["runs"]:
        assert run["regex_match_rate"] == 1.0  # the baseline obeys the same pattern


def test_the_comparison_can_fail(generated):
    """Negative controls: each comparison that passes above rejects a deliberate change."""

    def mutated(case_id: str, edit: Any) -> list[Any]:
        case = json.loads(json.dumps(CASES[case_id]))
        edit(case)
        result = _engine(cases_mod.schema_for(case, "shape")).generate()
        return parts.measure(case, {n: _Lazy(t) for n, t in result.tables.items()})

    def fails(case_id: str, series: list[Any]) -> bool:
        runs = FIXTURES[CASES[case_id]["strategy"]]["cases"][case_id]["runs"]
        if parts.check_series(fingerprint.fingerprint(series), [r["fingerprint"] for r in runs]):
            return True
        if CASES[case_id]["parts"]:
            got = parts.parts_fingerprint(series, CASES[case_id]["parts"], POOLS)
            return bool(parts.check_parts(got, [r["parts"] for r in runs]))
        return False

    def target(case: dict[str, Any]) -> dict[str, Any]:
        return case["tables"][case["target"][0]]["columns"][case["target"][1]]["generator"]

    assert not fails("native/first_name", generated["native/first_name"])
    # another provider's text parses into the wrong pool
    assert fails("native/first_name", generated["native/last_name"])
    assert fails("native/name", generated["native/first_name"])
    assert fails("native/email", generated["native/company_email"])
    assert fails("native/sentence", generated["native/city"])
    assert fails("native/pystr", generated["native/first_name"])
    # a formula with a 10% error, a derived column with a shifted window, a different aggregate
    assert fails(
        "formula/line_total",
        mutated(
            "formula/line_total",
            lambda c: target(c).update(expression="quantity * unit_price * 1.1"),
        ),
    )
    assert fails(
        "formula/margin",
        mutated("formula/margin", lambda c: target(c).update(expression="price - cost - 1")),
    )
    assert fails(
        "derived/add_days_uniform",
        mutated(
            "derived/add_days_uniform",
            lambda c: target(c).update(params={"distribution": "uniform", "min": 4, "max": 31}),
        ),
    )
    assert fails(
        "derived/add_days_log_normal",
        mutated(
            "derived/add_days_log_normal",
            lambda c: target(c).update(
                params={
                    "distribution": "log_normal",
                    "mean": 1.7,
                    "sigma": 0.7,
                    "min": 1,
                    "max": 60,
                }
            ),
        ),
    )
    assert fails(
        "computed/sum_children",
        mutated("computed/sum_children", lambda c: target(c).update(rule="avg_children")),
    )
    assert fails("computed/count_children", generated["computed/sum_children"])


# ---------------------------------------------------------------- shared behaviour

PROVIDER_NAMES = sorted(providers.PROVIDERS)


def _text_engine(strategy: str, provider: str, rows: int, seed: int = 11, **extra: Any) -> Engine:
    case = cases_mod._case(strategy, cases_mod._text(strategy, provider, **extra), rows=rows)
    return _engine(cases_mod.schema_for(case, "shape"), seed)


@pytest.mark.parametrize("strategy", ["native", "faker"])
@pytest.mark.parametrize("provider", PROVIDER_NAMES)
def test_text_identical_for_any_chunking_and_random_access(strategy, provider):
    rows = 6_000
    engine = _text_engine(strategy, provider, rows)
    whole = engine.generate_table("t", chunk_rows=rows).column("x").combine_chunks()
    assert whole.type == pa.string() and whole.null_count == 0
    for chunk in (700, 2_049):
        parts_ = engine.generate_table("t", chunk_rows=chunk).column("x").combine_chunks()
        assert parts_.equals(whole), f"chunk {chunk}"
    piece = engine.generate_chunk("t", 4_321, 333).column("x")
    assert piece.equals(whole.slice(4_321, 333))
    assert whole.equals(
        _text_engine(strategy, provider, rows).generate_table("t").column("x").combine_chunks()
    )
    other = _text_engine(strategy, provider, rows, seed=12).generate_table("t").column("x")
    assert not other.combine_chunks().equals(whole)


def test_faker_serves_the_native_providers_identically():
    for provider in PROVIDER_NAMES:
        a = _text_engine("native", provider, 500).generate_table("t").column("x")
        b = _text_engine("faker", provider, 500).generate_table("t").column("x")
        assert a.equals(b), provider


# ---------------------------------------------------------------- native


def test_native_value_shapes():
    def col(provider: str, rows: int = 20_000) -> list[str]:
        return _text_engine("native", provider, rows).generate_table("t").column("x").to_pylist()

    ssn = col("ssn")
    areas = np.array([int(v[:3]) for v in ssn])
    assert areas.min() >= 1 and areas.max() <= 899 and not (areas == 666).any()
    assert all(1 <= int(v[4:6]) <= 99 and 1 <= int(v[7:]) <= 9999 for v in ssn)
    phones = col("phone_number")
    assert all(re.fullmatch(r"\([2-9]\d\d\) [2-9]\d\d-[1-9]\d{3}", v) for v in phones)
    area = np.array([int(v[1:4]) for v in phones])
    assert area.min() >= 200 and area.max() <= 998
    assert min(int(v[-4:]) for v in phones) >= 1000
    emails = col("email")
    assert all(re.fullmatch(r"[a-z]+\.[a-z']+[1-9]\d{0,2}@[\w.-]+", v) for v in emails)
    assert max(int(re.search(r"(\d+)@", v).group(1)) for v in emails) <= 998
    stems = {c.removesuffix(".com").split("@")[1] for c in col("company_email", 5_000)}
    assert all(len(s) <= 20 and s == s.lower() and " " not in s for s in stems)
    assert {v.split("/")[2] for v in col("uri", 5_000)} <= set(POOLS["uri_domains"])
    assert set(col("state_abbr")) <= set(POOLS["us_states"])
    assert set(col("pystr", 3_000)) and all(len(v) == 12 for v in col("word", 3_000))


def test_native_email_follows_first_and_last_name_columns():
    case = CASES["native/email_follows_names"]
    table = _case_engine("native/email_follows_names").generate_table("t")
    first = pc.utf8_lower(table["first_name"].combine_chunks()).to_pylist()
    last = pc.utf8_lower(table["last_name"].combine_chunks()).to_pylist()
    email = table["x"].to_pylist()
    assert case["strategy"] == "native"
    assert all(e.startswith(f"{f}.{la}") for e, f, la in zip(email, first, last, strict=True))
    # without those columns the e-mail draws its own names
    own = _text_engine("native", "email", 2_000).generate_table("t").column("x").to_pylist()
    assert len(set(own)) > 1_900


def test_native_email_with_null_names_is_null():
    raw = cases_mod.schema_for(CASES["native/email_follows_names"], "shape")
    raw["generation"]["scales"]["s"]["t"] = 3_000
    raw["tables"]["t"]["columns"]["first_name"].update(nullable=True, null_rate=0.3)
    table = _engine(raw, 5).generate_table("t")
    first, email = table["first_name"].to_pylist(), table["x"].to_pylist()
    assert any(f is None for f in first)
    assert all((f is None) == (e is None) for f, e in zip(first, email, strict=True))


def test_native_max_length_and_nulls_belong_to_the_column(generated):
    capped = generated["native/sentence_max_length"]
    assert max(len(v) for v in capped) == 24
    assert all(v == s[:24] for v, s in zip(capped, POOLS["sentences"] * 0 + capped, strict=False))
    series = generated["native/first_name_nullable"]
    assert abs(series.count(None) / len(series) - 0.2) < 0.01
    assert max(len(v) for v in generated["faker/city_max_length"] if v) <= 6


def test_native_default_provider_is_word():
    a = _text_engine("native", "word", 1_000).generate_table("t").column("x")
    case = cases_mod._case(
        "native", cases_mod._col("x", "string", {"strategy": "native"}), rows=1_000
    )
    b = _engine(cases_mod.schema_for(case, "shape"), 11).generate_table("t").column("x")
    assert a.equals(b)


def test_native_unknown_provider_names_the_column():
    engine = _text_engine("native", "date_of_birth", 10)
    with pytest.raises(
        StrategyError,
        match=r"native strategy does not handle provider 'date_of_birth' for column t\.x",
    ):
        engine.generate_table("t")


# ---------------------------------------------------------------- faker (exotic providers)


class _FakeFaker:
    """What the ``faker`` package offers, as far as the strategy uses it."""

    created: list[tuple[str, int | None]] = []

    def __init__(self, locale: str) -> None:
        self.locale = locale
        self._rng = np.random.default_rng(0)

    def seed_instance(self, seed: int) -> None:
        self._rng = np.random.default_rng(seed)
        _FakeFaker.created.append((self.locale, seed))

    def color_name(self) -> str:
        return f"color-{int(self._rng.integers(0, 10**9))}"

    def bothify(self, text: str = "??##") -> str:
        return text.replace("#", str(int(self._rng.integers(0, 10))))

    def age(self) -> int:
        return int(self._rng.integers(18, 90))

    mixed_value = "not callable"


@pytest.fixture
def fake_faker(monkeypatch):
    module = types.ModuleType("faker")
    module.Faker = _FakeFaker  # type: ignore[attr-defined]
    monkeypatch.setitem(sys.modules, "faker", module)
    providers._faker_pool.cache_clear()
    _FakeFaker.created.clear()
    yield module
    providers._faker_pool.cache_clear()


def _faker_engine(provider: str, rows: int, seed: int = 3, **spec: Any) -> Engine:
    case = cases_mod._case(
        "faker",
        cases_mod._col("x", "string", {"strategy": "faker", "provider": provider, **spec}),
        rows=rows,
    )
    return _engine(cases_mod.schema_for(case, "shape"), seed)


def test_faker_exotic_provider_fills_from_a_pool(fake_faker):
    engine = _faker_engine("color_name", 3_000)
    whole = engine.generate_table("t", chunk_rows=3_000).column("x").combine_chunks()
    assert len(set(whole.to_pylist())) == 3_000  # the table fits the pool: every value distinct
    chunked = engine.generate_table("t", chunk_rows=500).column("x").combine_chunks()
    assert chunked.equals(whole)
    assert engine.generate_chunk("t", 1_000, 77).column("x").equals(whole.slice(1_000, 77))
    assert len(_FakeFaker.created) == 1  # one pool for every chunk
    assert _FakeFaker.created[0][0] == "en_US"
    other = _faker_engine("color_name", 3_000, seed=4).generate_table("t").column("x")
    assert not other.combine_chunks().equals(whole)


def test_faker_pool_is_capped_and_sampled(fake_faker, monkeypatch):
    monkeypatch.setattr(providers, "FAKER_POOL_ROWS", 200)
    engine = _faker_engine("color_name", 5_000)
    whole = engine.generate_table("t", chunk_rows=5_000).column("x").combine_chunks()
    assert len(set(whole.to_pylist())) <= 200
    assert len(set(whole.to_pylist())) > 190
    assert engine.generate_table("t", chunk_rows=777).column("x").combine_chunks().equals(whole)


def test_faker_passes_args_and_the_models_locale(fake_faker):
    raw = cases_mod.schema_for(
        cases_mod._case(
            "faker",
            cases_mod._col(
                "x",
                "string",
                {"strategy": "faker", "provider": "bothify", "args": {"text": "AB-##"}},
            ),
            rows=40,
        ),
        "shape",
    )
    raw["model"]["locale"] = "de_DE"
    values = _engine(raw).generate_table("t").column("x").to_pylist()
    assert all(re.fullmatch(r"AB-\d\d", v) for v in values)
    assert _FakeFaker.created[0][0] == "de_DE"


def test_faker_non_text_values_and_max_length(fake_faker):
    ages = _faker_engine("age", 500).generate_table("t").column("x")
    assert (
        pa.types.is_integer(ages.type) and 18 <= pc.min(ages).as_py() <= pc.max(ages).as_py() < 90
    )
    case = cases_mod._case(
        "faker",
        cases_mod._text("faker", "color_name", max_length=8),
        rows=100,
    )
    values = (
        _engine(cases_mod.schema_for(case, "shape")).generate_table("t").column("x").to_pylist()
    )
    assert max(len(v) for v in values) == 8


def test_faker_unknown_provider_and_missing_package(fake_faker, monkeypatch):
    with pytest.raises(StrategyError, match="unknown faker provider 'nope'"):
        _faker_engine("nope", 5).generate_table("t")
    with pytest.raises(StrategyError, match="unknown faker provider 'mixed_value'"):
        _faker_engine("mixed_value", 5).generate_table("t")
    providers._faker_pool.cache_clear()
    monkeypatch.setitem(sys.modules, "faker", None)
    with pytest.raises(ImportError, match="pip install faker"):
        _faker_engine("color_name", 5).generate_table("t")
    # the built-in providers never need the package
    assert _faker_engine("city", 5).generate_table("t").num_rows == 5


# ---------------------------------------------------------------- formula


def _formula(expression: str, helpers: dict[str, Any] | None = None, rows: int = 500, **kw: Any):
    cols = {
        name: cases_mod._col(name, "decimal", gen, **kw.pop(f"{name}_extra", {}))
        for name, gen in (helpers or {}).items()
    }
    case = cases_mod._case(
        "formula",
        cases_mod._col("x", "decimal", {"strategy": "formula", "expression": expression}, **kw),
        helpers=cols,
        rows=rows,
    )
    return _engine(cases_mod.schema_for(case, "shape"), 21)


_AB = {
    "a": {"strategy": "distribution", "distribution": "uniform", "min": -5, "max": 100},
    "b": {"strategy": "distribution", "distribution": "uniform", "min": 1, "max": 20},
}


def _baseline_style(expression: str, columns: Mapping[str, np.ndarray[Any, Any]]) -> Any:
    """What the baseline's strategy computes: ``eval`` over numpy arrays (the reference value)."""
    ns = {
        "__builtins__": {"abs": abs, "round": round},
        "np_round": np.round, "np_clip": np.clip, "np_where": np.where,
        "np_maximum": np.maximum, "np_minimum": np.minimum, "np_abs": np.abs,
        "np_sqrt": np.sqrt, "np_log": np.log, "np_exp": np.exp, "np_floor": np.floor,
        "np_ceil": np.ceil, "np_nan": np.nan,
    }  # fmt: skip
    with np.errstate(all="ignore"):
        return eval(expression, ns, dict(columns))  # noqa: S307  (the reference, test only)


@pytest.mark.parametrize(
    "expression",
    [
        "a + b",
        "a - b * 2",
        "a * b / 3",
        "(a + 1) * (b - 1) / (b + 0.5)",
        "a // b",
        "a % b",
        "a ** 2",
        "b ** 0.5",
        "-a + +b",
        "np_round(a, 1)",
        "np_clip(a, 0, 50)",
        "np_where(a > 10, a, b)",
        "np_maximum(a, b) - np_minimum(a, b)",
        "np_abs(a) + abs(b)",
        "np_sqrt(b) + np_log(b) + np_exp(b / 10)",
        "np_floor(a) + np_ceil(b)",
        "np_where(a > 0, np_sqrt(a), np_nan)",
        "1.5",
        "a / 0",
        "np_log(a)",
    ],
)
def test_formula_equals_the_baselines_evaluation(expression):
    engine = _formula(expression, _AB)
    table = engine.generate_table("t")
    got = table["x"].to_numpy(zero_copy_only=False)
    cols = {n: table[n].to_numpy(zero_copy_only=False) for n in ("a", "b")}
    want = _baseline_style(expression, cols)
    want = np.full(len(got), want) if np.ndim(want) == 0 else np.asarray(want)
    assert got.shape == want.shape
    assert np.array_equal(got, want, equal_nan=True), expression


def test_formula_extensions_and_types():
    engine = _formula("min(a, b, 3) + max(a, 0)", _AB)
    table = engine.generate_table("t")
    a, b = (table[n].to_numpy() for n in ("a", "b"))
    assert np.array_equal(table["x"].to_numpy(), np.minimum(np.minimum(a, b), 3) + np.maximum(a, 0))
    ternary = _formula("a if a > 0 else 0 - b", _AB).generate_table("t")
    a, b = (ternary[n].to_numpy() for n in ("a", "b"))
    assert np.array_equal(ternary["x"].to_numpy(), np.where(a > 0, a, -b))
    boolean = _formula("a > 0 and b < 10 or not (a < 50)", _AB).generate_table("t")
    a, b = (boolean[n].to_numpy() for n in ("a", "b"))
    assert boolean["x"].type == pa.bool_()
    assert np.array_equal(boolean["x"].to_numpy(), ((a > 0) & (b < 10)) | ~(a < 50))
    chained = _formula("0 < b < 10", _AB).generate_table("t")
    b = chained["b"].to_numpy()
    assert np.array_equal(chained["x"].to_numpy(), (b > 0) & (b < 10))
    ints = _formula("id * 2 + 1", {}).generate_table("t")
    assert ints["x"].type == pa.int64() and ints["x"].to_pylist()[:3] == [3, 5, 7]
    scaled = _formula("a / 3", _AB, scale=2).generate_table("t")
    assert all(round(v, 2) == v for v in scaled["x"].to_pylist())
    assert _formula("12.5", {}).generate_table("t")["x"].to_pylist() == [12.5] * 500
    # a decimal helper column reads as a number
    assert pa.types.is_floating(_formula("a * 2", _AB).generate_table("t")["x"].type)


def test_formula_identical_for_any_chunking_and_random_access():
    engine = _formula("np_round(a * b - a / (b + 1), 4)", _AB, rows=9_000)
    whole = engine.generate_table("t", chunk_rows=9_000).column("x").combine_chunks()
    for chunk in (1_000, 3_331):
        assert (
            engine.generate_table("t", chunk_rows=chunk).column("x").combine_chunks().equals(whole)
        )
    assert engine.generate_chunk("t", 5_000, 321).column("x").equals(whole.slice(5_000, 321))


def test_formula_null_in_an_input_gives_null():
    raw = cases_mod.schema_for(
        cases_mod._case(
            "formula",
            cases_mod._col("x", "decimal", {"strategy": "formula", "expression": "a + b"}),
            helpers={
                "a": cases_mod._col("a", "decimal", _AB["a"], nullable=True, null_rate=0.2),
                "b": cases_mod._col("b", "decimal", _AB["b"], nullable=True, null_rate=0.1),
            },
            rows=4_000,
        ),
        "shape",
    )
    table = _engine(raw).generate_table("t")
    a, b, x = (table[n].to_pylist() for n in ("a", "b", "x"))
    assert any(v is None for v in a) and any(v is None for v in b)
    assert all((p is None or q is None) == (r is None) for p, q, r in zip(a, b, x, strict=True))
    assert all(r == p + q for p, q, r in zip(a, b, x, strict=True) if r is not None)


@pytest.mark.parametrize(
    ("expression", "message"),
    [
        ("", "requires 'expression'"),
        ("a +", "not a valid expression"),
        ("a.real", "Attribute is not allowed"),
        ("a.__class__", "Attribute is not allowed"),
        ("__import__('os').system('true')", "only the documented functions"),
        ("open('x')", "only the documented functions"),
        ("eval('1')", "only the documented functions"),
        ("(lambda: 1)()", "only the documented functions"),
        ("[a for a in range(3)]", "is not allowed"),
        ("a[0]", "Subscript is not allowed"),
        ("'text'", "only numbers are allowed"),
        ("None", "only numbers are allowed"),
        ("1j", "only numbers are allowed"),
        ("(w := 1)", "is not allowed"),
        ("a @ b", "operator MatMult is not allowed"),
        ("a & b", "operator BitAnd is not allowed"),
        ("~a", "operator Invert is not allowed"),
        ("a in b", "only < <= > >= == != comparisons"),
        ("a is b", "only < <= > >= == != comparisons"),
        ("np_round(a, decimals=1)", "positional arguments only"),
        ("a if b", "not a valid expression"),
        ("{a: 1}", "is not allowed"),
        ("f'{a}'", "is not allowed"),
        ("a + " * 700 + "1", "longer than"),
        ("missing_column + 1", "column 'missing_column' is not generated before it"),
        ("min(a)", "needs at least two arguments"),
    ],
)
def test_formula_rejects_what_the_grammar_does_not_allow(expression, message):
    spec: dict[str, Any] = {"strategy": "formula", "expression": expression}
    if expression == "":
        spec = {"strategy": "formula"}
    case = cases_mod._case(
        "formula",
        cases_mod._col("x", "decimal", spec),
        helpers={n: cases_mod._col(n, "decimal", g) for n, g in _AB.items()},
        rows=5,
    )
    with pytest.raises(ValueError, match=re.escape(message)) as err:
        _engine(cases_mod.schema_for(case, "shape")).generate_table("t")
    assert "t.x" in str(err.value)


def test_formula_never_reaches_eval(monkeypatch):
    import builtins

    def refuse(*a: Any, **k: Any) -> None:
        raise AssertionError("eval or exec was called")

    monkeypatch.setattr(builtins, "eval", refuse)
    monkeypatch.setattr(builtins, "exec", refuse)
    assert _formula("a * b + np_sqrt(b)", _AB).generate_table("t").num_rows == 500


def test_formula_text_column_is_rejected():
    case = cases_mod._case(
        "formula",
        cases_mod._col("x", "decimal", {"strategy": "formula", "expression": "name + 1"}),
        helpers={
            "name": cases_mod._col("name", "string", {"strategy": "native", "provider": "city"})
        },
        rows=5,
    )
    with pytest.raises(
        StrategyError, match="reads column 'name' of type string; it must be numeric"
    ):
        _engine(cases_mod.schema_for(case, "shape")).generate_table("t")


def test_formula_compile_is_cached_and_lists_columns():
    first = compile_expression("a * (b + 1) - a")
    assert compile_expression("a * (b + 1) - a") is first
    assert first.names == ("a", "b")
    assert compile_expression("np_sqrt(np_nan + 1)").names == ()
    assert Formula.name == "formula"


# ---------------------------------------------------------------- derived


def _derived_engine(
    generator: dict[str, Any], source_type: str = "ts", rows: int = 2_000
) -> Engine:
    """A table with a date column ``d`` and a derived column ``x``."""
    case = cases_mod._derived({}, rule="copy")
    columns = case["tables"]["t"]["columns"]
    columns["x"] = cases_mod._col(
        "x", "timestamp", {"strategy": "derived", "source": "d", **generator}
    )
    case["tables"]["t"]["rows"] = rows
    raw = cases_mod.schema_for(case, "shape")
    if source_type == "date":
        raw["tables"]["t"]["columns"]["d"]["generator"] = {"strategy": "test_date32"}
    if source_type == "text":
        raw["tables"]["t"]["columns"]["d"]["generator"] = {"strategy": "test_text_dates"}
    engine = _engine(raw, 9)
    engine._strategies["test_date32"] = _Date32()
    engine._strategies["test_text_dates"] = _TextDates()
    return engine


class _Date32:
    def generate(self, spec: Mapping[str, Any], ctx: Any) -> pa.Array:
        return pa.array(
            19_000 + np.arange(ctx.row_start, ctx.row_start + ctx.n_rows) % 700, type=pa.int32()
        ).cast(pa.date32())


class _TextDates:
    def generate(self, spec: Mapping[str, Any], ctx: Any) -> pa.Array:
        i = np.arange(ctx.row_start, ctx.row_start + ctx.n_rows)
        forms = [
            "2024-03-%02d",
            "2024-03-%02dT10:30:00",
            "2024-03-%02d 08:15:45",
            "not a date %02d",
        ]
        return pa.array([forms[k % 4] % (1 + k % 28) for k in i])


def _days(table: pa.Table, a: str = "x", b: str = "d") -> np.ndarray[Any, Any]:
    delta = pc.subtract(table[a].combine_chunks(), table[b].combine_chunks())
    return np.asarray(pc.divide(pc.cast(delta, pa.int64()), 86_400_000_000).to_numpy())


def test_derived_add_days_keeps_the_source_type_and_adds_whole_days():
    table = _derived_engine({"rule": "add_days", "params": {"min": 3, "max": 30}}).generate_table(
        "t"
    )
    assert table["x"].type == table["d"].type == pa.timestamp("us")
    days = _days(table)
    assert days.min() == 3 and days.max() == 30
    # the time of day is untouched
    assert pc.equal(pc.hour(table["x"]), pc.hour(table["d"])).to_pylist().count(False) == 0


def test_derived_days_shorthand_and_alias_and_defaults():
    exact = _derived_engine({"days": 7}).generate_table("t")
    assert set(_days(exact).tolist()) == {7}
    alias = _derived_engine(
        {"operation": "add_days", "params": {"min": 1, "max": 2}}
    ).generate_table("t")
    assert set(_days(alias).tolist()) == {1, 2}
    default = _derived_engine({"rule": "add_days"}).generate_table("t")
    assert _days(default).min() == 1 and _days(default).max() == 30
    copied = _derived_engine({}).generate_table("t")
    assert copied["x"].equals(copied["d"])
    unknown = _derived_engine(
        {"rule": "add_days", "params": {"distribution": "weibull", "min": 2, "max": 4}}
    ).generate_table("t")
    assert set(_days(unknown).tolist()) == {2, 3, 4}
    clipped = _derived_engine(
        {
            "rule": "add_days",
            "params": {"distribution": "normal", "mean": 50, "std_dev": 1, "min": 1, "max": 9},
        }
    ).generate_table("t")
    assert set(_days(clipped).tolist()) == {9}


def test_derived_date_source_and_text_source():
    dates = _derived_engine(
        {"rule": "add_days", "params": {"min": 2, "max": 5}}, "date"
    ).generate_table("t")
    assert dates["x"].type == pa.date32()
    delta = pc.cast(dates["x"], pa.int32()).to_numpy() - pc.cast(dates["d"], pa.int32()).to_numpy()
    assert set(delta.tolist()) == {2, 3, 4, 5}
    text = _derived_engine(
        {"rule": "add_days", "params": {"min": 1, "max": 1}}, "text", rows=8
    ).generate_table("t")
    assert text["x"].type == pa.timestamp("us")
    values = text["x"].to_pylist()
    assert values[0].day == 2 and (values[1].hour, values[1].minute) == (10, 30)
    assert (values[2].minute, values[2].second) == (15, 45)
    assert values[3] is None  # unparsable text is null, as in the baseline's coercion


def test_derived_null_source_gives_null():
    raw = cases_mod.schema_for(CASES["derived/add_days_uniform"], "shape")
    raw["generation"]["scales"]["s"]["t"] = 3_000
    raw["tables"]["t"]["columns"]["d"].update(nullable=True, null_rate=0.25)
    table = _engine(raw, 2).generate_table("t")
    d, x = table["d"].to_pylist(), table["x"].to_pylist()
    assert any(v is None for v in d)
    assert all((p is None) == (q is None) for p, q in zip(d, x, strict=True))


def test_derived_identical_for_any_chunking_and_random_access():
    engine = _derived_engine(
        {
            "rule": "add_days",
            "params": {"distribution": "log_normal", "mean": 2, "sigma": 1, "min": 1, "max": 90},
        },
        rows=7_000,
    )
    whole = engine.generate_table("t", chunk_rows=7_000).column("x").combine_chunks()
    for chunk in (1_000, 2_999):
        assert (
            engine.generate_table("t", chunk_rows=chunk).column("x").combine_chunks().equals(whole)
        )
    assert engine.generate_chunk("t", 3_000, 100).column("x").equals(whole.slice(3_000, 100))


def _cross_engine(
    parent_key: dict[str, Any],
    child_key: dict[str, Any],
    *,
    via: str = "order_id",
    child_rows: int = 400,
    **gen: Any,
) -> Engine:
    case = cases_mod._derived({}, rule="copy")
    raw = cases_mod.schema_for(CASES["derived/cross_table"], "shape")
    raw["tables"]["order"]["columns"]["order_id"]["generator"] = parent_key
    raw["tables"]["order"]["columns"]["order_id"]["type"] = "string"
    child = raw["tables"]["return"]["columns"]
    child["order_id"]["generator"] = child_key
    child["order_id"]["type"] = "string"
    child["x"]["generator"].update({"via": via, **gen})
    raw["generation"]["scales"]["s"].update({"order": 300, "return": child_rows})
    assert case
    return _engine(raw, 8)


def test_derived_cross_table_with_a_sequence_key_and_with_any_other_key():
    seq = _cross_engine(
        {"strategy": "sequence", "start": 100, "step": 5},
        {"strategy": "sequence", "start": 100, "step": 5},
    )
    seq_t = seq.generate_table("return")
    parent = seq.generate_table("order")
    assert seq_t["x"].null_count == 100  # rows 301.. have no parent
    days = _days_cross(seq_t, parent)
    assert days[:300].min() >= 1 and days[:300].max() <= 90
    # a string key goes through a lookup instead of arithmetic, with the same meaning
    keys = {"strategy": "pattern", "format": "O-{seq:5}"}
    text = _cross_engine(keys, keys)
    text_t, text_parent = text.generate_table("return"), text.generate_table("order")
    assert text_t["x"].null_count == 100
    assert _days_cross(text_t, text_parent)[:300].min() >= 1
    # a key column that is not the parent's key matches nothing
    off = _cross_engine(
        {"strategy": "sequence", "start": 1}, {"strategy": "sequence", "start": 100_000}
    )
    assert off.generate_table("return")["x"].null_count == 400


def _days_cross(child: pa.Table, parent: pa.Table) -> np.ndarray[Any, Any]:
    """Days from each parent's date to the child row of the same index (the keys line up)."""
    shifted = pc.subtract(
        child["x"].combine_chunks().slice(0, len(parent)), parent["order_date"].combine_chunks()
    )
    return np.asarray(
        pc.divide(pc.cast(shifted, pa.int64()), 86_400_000_000).to_numpy(zero_copy_only=False)
    )


def test_derived_cross_table_chunking_and_copy():
    engine = _cross_engine(
        {"strategy": "sequence", "start": 1},
        {"strategy": "sequence", "start": 1},
        child_rows=290,
        rule="copy",
    )
    whole = engine.generate_table("return", chunk_rows=290)
    parent = engine.generate_table("order")
    column = whole["x"].combine_chunks()
    assert column.equals(parent["order_date"].combine_chunks().slice(0, 290))
    assert engine.generate_table("return", chunk_rows=64)["x"].combine_chunks().equals(column)
    assert engine.generate_chunk("return", 100, 50).column("x").equals(column.slice(100, 50))


@pytest.mark.parametrize(
    ("generator", "message"),
    [
        ({"rule": "shift"}, "unknown rule 'shift'"),
        ({"source": "nothing"}, "source 'nothing' not found"),
        ({"source": ""}, "source '' not found"),
        ({"source": "order.order_date"}, "source 'order.order_date' not found"),
        ({"rule": "add_days", "source": "id"}, "needs a date, timestamp or ISO text source"),
    ],
)
def test_derived_bad_specs_name_the_column(generator, message):
    engine = _derived_engine({"rule": "copy", **generator})
    with pytest.raises(StrategyError, match=re.escape(message)) as err:
        engine.generate_table("t")
    assert "t.x" in str(err.value)


def test_derived_cross_table_errors():
    def run(**gen: Any) -> None:
        engine = _cross_engine(
            {"strategy": "sequence", "start": 1}, {"strategy": "sequence", "start": 1}, **gen
        )
        engine.generate_table("return")

    with pytest.raises(StrategyError, match="via column 'nope' is not generated before it"):
        run(via="nope")
    with pytest.raises(StrategyError, match="no table 'ghost'"):
        run(source="ghost.order_date")
    with pytest.raises(StrategyError, match="table 'order' has no column 'missing'"):
        run(source="order.missing")


def test_computed_placeholder_and_registration():
    out = Computed().generate({"rule": "sum_children"}, types.SimpleNamespace(n_rows=4))
    assert out.type == pa.float64() and out.null_count == 4
    assert Derived.name == "derived" and Computed.name == "computed"
    engine = _case_engine("computed/sum_children")
    assert engine.dry_run().missing_strategies == []
    raw = engine.generate_table("parent")
    assert raw["x"].null_count == raw.num_rows  # filled only by the compute phase
    assert engine.generate().tables["parent"]["x"].null_count == 0


def _computed_tables(case_id: str) -> tuple[pa.Table, pa.Table]:
    result = _case_engine(case_id).generate()
    return result.tables["parent"], result.tables["line"]


@pytest.mark.parametrize(
    ("case_id", "func", "column"),
    [
        ("computed/sum_children", "sum", "amount"),
        ("computed/count_children", "count", "amount"),
        ("computed/avg_children", "mean", "amount"),
        ("computed/min_children", "min", "amount"),
        ("computed/max_children", "max", "amount"),
        ("computed/sum_of_integers", "sum", "line_id"),
    ],
)
def test_computed_is_the_aggregate_of_the_children(case_id, func, column):
    parent, line = _computed_tables(case_id)
    grouped = line.group_by("parent_id").aggregate([(column, func)])
    expect = dict(
        zip(grouped["parent_id"].to_pylist(), grouped[f"{column}_{func}"].to_pylist(), strict=True)
    )
    got = dict(zip(parent["id"].to_pylist(), parent["x"].to_pylist(), strict=True))
    for key, value in got.items():
        want = expect.get(key, 0)
        assert value == (float(np.round(want, 2)) if isinstance(want, float) else want), key
        assert not isinstance(value, float) or round(value, 2) == value  # no 114.49000000000001
    # the sum over parents is the sum over children (rounding aside)
    if func == "sum":
        assert abs(sum(got.values()) - pc.sum(line[column]).as_py()) < 0.01 * parent.num_rows


def test_computed_lookup_parent_copies_the_parents_value():
    raw = cases_mod.schema_for(CASES["computed/sum_children"], "shape")
    raw["tables"]["parent"]["columns"]["size"] = cases_mod._col(
        "size",
        "decimal",
        {"strategy": "distribution", "distribution": "uniform", "min": 1, "max": 9},
    )
    raw["tables"]["line"]["columns"]["parent_size"] = cases_mod._col(
        "parent_size",
        "decimal",
        {
            "strategy": "computed",
            "rule": "lookup_parent",
            "child_table": "parent",
            "child_column": "size",
        },
    )
    result = _engine(raw).generate()
    line, parent = result.tables["line"], result.tables["parent"]
    sizes = dict(
        zip(
            parent["id"].to_pylist(), [round(v, 2) for v in parent["size"].to_pylist()], strict=True
        )
    )
    assert all(
        s == sizes[k]
        for k, s in zip(line["parent_id"].to_pylist(), line["parent_size"].to_pylist(), strict=True)
    )


def test_computed_unknown_rule_is_an_error():
    raw = cases_mod.schema_for(CASES["computed/sum_children"], "shape")
    raw["tables"]["parent"]["columns"]["x"]["generator"]["rule"] = "median_children"
    with pytest.raises(ValueError, match="Unknown computed rule: 'median_children'"):
        _engine(raw).generate()


def test_every_new_strategy_is_a_registered_builtin():
    from shape.plugins.host import default_host

    host = default_host()
    for name in ("native", "faker", "formula", "derived", "computed"):
        assert host.get("shape.strategies", name).name == name


def test_compute_rounds_the_way_numpy_does():
    """Regression: Arrow's own ``round`` leaves 114.49000000000001 as it is (its scaled value is
    already whole in floating point); the compute phase now gives 114.49, like the baseline."""
    from shape.generation.compute import _round_if_float

    noisy = pa.array([114.49000000000001, 0.1 + 0.2, None, 2.675, 7.0], type=pa.float64())
    assert pc.round(noisy, 2).to_pylist()[0] == 114.49000000000001  # what Arrow does
    got = _round_if_float(noisy)
    assert got.to_pylist() == [114.49, 0.3, None, float(np.round(2.675, 2)), 7.0]
    assert got.type == pa.float64() and got.null_count == 1
    ints = pa.array([1, 2, 3])
    assert _round_if_float(ints) is ints


def test_computed_parents_without_children_get_zero_of_the_natural_type():
    raw = cases_mod.schema_for(CASES["computed/count_children"], "shape")
    raw["generation"]["scales"]["s"].update({"parent": 50, "line": 20})
    for rule, column in (("count_children", "units"), ("sum_children", "line_id")):
        raw["tables"]["parent"]["columns"]["x"]["generator"].update(rule=rule, child_column=column)
        result = _engine(raw).generate()
        x = result.tables["parent"]["x"]
        assert pa.types.is_integer(x.type) and x.null_count == 0
        assert x.to_pylist().count(0) >= 30  # at most 20 parents have a child
