"""Compile the contract rules that need singular dbt SQL tests."""

from __future__ import annotations

import math
import re
from collections.abc import Mapping
from typing import Any

from shape.contracts.emit._common import PATTERNS

from .project import DbtProjectError

DIALECTS = ("duckdb", "postgres", "snowflake", "bigquery")
_SAFE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def compile_singular(
    tables: Mapping[str, Any], *, dialect: str, kind: str, source_name: str
) -> dict[str, str]:
    if dialect not in DIALECTS:
        raise DbtProjectError(
            f"unknown singular-test dialect {dialect!r}; choose {', '.join(DIALECTS)}"
        )
    files: dict[str, str] = {}
    quote = "`" if dialect == "bigquery" else '"'

    def literal(value: Any) -> str:
        if not isinstance(value, str):
            raise DbtProjectError("non-numeric min/max and pattern must be strings")
        # BigQuery string literals interpret backslashes; PostgreSQL standard strings do not.
        text = value.replace("\\", "\\\\") if dialect in ("bigquery", "snowflake") else value
        return "'" + text.replace("'", "''") + "'"

    for model, contract in tables.items():
        if not _SAFE.fullmatch(model):
            raise DbtProjectError(
                f"{model!r}: model name must contain letters, digits and underscores"
            )
        if kind == "sources":
            if not _SAFE.fullmatch(source_name):
                raise DbtProjectError("source name must contain letters, digits and underscores")
            relation = "{{ source('" + source_name + "', '" + model + "') }}"
        else:
            relation = "{{ ref('" + model + "') }}"
        for column, rules in (contract.get("columns") or {}).items():
            if not _SAFE.fullmatch(column):
                raise DbtProjectError(
                    f"{column!r}: column name must contain letters, digits and underscores"
                )
            expr = quote + column + quote
            for rule, value in rules.items():
                predicate: str | None = None
                aggregate = False
                if rule == "pattern":
                    if value not in PATTERNS:
                        raise DbtProjectError(
                            f"{model}.{column}.pattern: unknown pattern label {value!r}"
                        )
                    regex = PATTERNS[value]
                    if dialect == "snowflake":
                        regex = regex.replace("(?:", "(")
                    pattern = literal(regex)
                    matches = {
                        "duckdb": f"regexp_matches({expr}, {pattern})",
                        "postgres": f"{expr} ~ {pattern}",
                        "snowflake": f"regexp_like({expr}, {pattern})",
                        "bigquery": f"regexp_contains({expr}, {pattern})",
                    }[dialect]
                    predicate = f"{expr} is not null and not ({matches})"
                elif rule in ("min_true_rate", "max_true_rate"):
                    if (
                        isinstance(value, bool)
                        or not isinstance(value, (int, float))
                        or not math.isfinite(value)
                        or not 0 <= value <= 1
                    ):
                        raise DbtProjectError(
                            f"{model}.{column}.{rule}: rate must be between 0 and 1"
                        )
                    op = "<" if rule == "min_true_rate" else ">"
                    predicate = (
                        f"1.0 * sum(case when {expr} then 1 else 0 end) "
                        f"/ nullif(count({expr}), 0) {op} {value}"
                    )
                    aggregate = True
                elif rule in ("min", "max") and not isinstance(value, (int, float)):
                    op = "<" if rule == "min" else ">"
                    predicate = f"{expr} is not null and {expr} {op} {literal(value)}"
                if predicate is not None:
                    sql = (
                        f"select {'1 as failure' if aggregate else '*'}\nfrom {relation}\n"
                        f"{'having' if aggregate else 'where'} {predicate}\n"
                    )
                    files[f"{model}__{column}__{rule}.sql"] = (
                        "-- Generated by Shape from the contract.\n" + sql
                    )
    return files
