"""What the ``shape_spark_worker`` notebook runs on a Fabric Spark cluster (P6-13).

``run_job(spark, spec, ...)`` generates the dataset a job spec describes and writes each table as a
Delta table in the Lakehouse (``Tables/<prefix><table>``):

* a table that is large (more rows than ``chunk_rows``) and that no post-pass changes is
  generated by the executors: one Spark partition per chunk, each building the engine from the
  spec and making its row range (the engine's random access makes a chunk independent of the
  others), so the generation is spread over the cluster;
* every other table, and every table of a schema with a post-pass, is generated on the driver
  with ``Engine.generate`` and written from there.

Row counts are exact, and the output does not depend on how Spark split the work. Shape must be
installed on the executors (the notebook's first cell installs it; a Fabric Environment library
works too). Spark is never imported here, so the module is importable and testable anywhere.
"""

from __future__ import annotations

import json
import math
from collections.abc import Callable, Iterator, Mapping
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import pyarrow as pa  # type: ignore[import-untyped]

_DDL = {
    "int8": "tinyint",
    "int16": "smallint",
    "int32": "int",
    "int64": "bigint",
    "float": "float",
    "double": "double",
    "bool": "boolean",
    "string": "string",
    "large_string": "string",
    "date32[day]": "date",
    "timestamp[us]": "timestamp",
    "timestamp[ns]": "timestamp",
}


def arrow_to_ddl(schema: pa.Schema) -> str:
    """A Spark DDL schema string for an Arrow schema (the types the engine produces)."""
    parts = []
    for field in schema:
        text = str(field.type)
        ddl = _DDL.get(text)
        if ddl is None and text.startswith("decimal"):
            ddl = text.replace("decimal128", "decimal").replace("(", "(").replace(" ", "")
        if ddl is None:
            raise TypeError(f"no Spark type for column {field.name!r}: {text}")
        parts.append(f"`{field.name}` {ddl}")
    return ", ".join(parts)


def load_spec(text: str) -> dict[str, Any]:
    spec = json.loads(text)
    if not isinstance(spec, dict) or spec.get("version") != 1 or "schema" not in spec:
        raise ValueError("not a Shape generation job spec (version 1)")
    return spec


def make_engine(spec: Mapping[str, Any]) -> Any:
    from shape.generation.engine import Engine
    from shape.generation.schema import GenSchema

    return Engine(
        GenSchema.from_dict(spec["schema"]),
        seed=int(spec["seed"]),
        row_counts=dict(spec["row_counts"]),
        chunk_rows=int(spec["chunk_rows"]),
    )


def distributed_tables(engine: Any, chunk_rows: int) -> list[str]:
    """The tables executors generate: more than one chunk, and no post-pass changes them."""
    touched = engine._post_pass_tables()
    return [
        name
        for name in engine.order
        if name not in touched and int(engine.row_counts[name]) > chunk_rows
    ]


def _chunk_batches(spec_json: str, table: str) -> Callable[[Iterator[Any]], Iterator[Any]]:
    """The function an executor runs on its partition of chunk numbers."""

    def run(batches: Iterator[Any]) -> Iterator[Any]:
        spec = json.loads(spec_json)
        engine = make_engine(spec)
        size = int(spec["chunk_rows"])
        total = int(engine.row_counts[table])
        for batch in batches:
            for index in batch.column(0).to_pylist():
                start = index * size
                if start < total:
                    yield engine.generate_chunk(table, start, min(size, total - start), chunk=index)

    return run


def run_job(
    spark: Any,
    spec: Mapping[str, Any],
    *,
    workspace_id: str,
    lakehouse_id: str,
    table_prefix: str = "",
    log: Callable[[str], None] = print,
) -> dict[str, Any]:
    """Generate ``spec`` and write Delta tables; returns the result record (rows per table)."""
    engine = make_engine(spec)
    engine.schema.validate_or_raise()
    chunk_rows = int(spec["chunk_rows"])
    root = f"abfss://{workspace_id}@onelake.dfs.fabric.microsoft.com/{lakehouse_id}/Tables"

    def save(frame: Any, table: str) -> None:
        (
            frame.write.format("delta")
            .mode("overwrite")
            .option("overwriteSchema", "true")
            .save(f"{root}/{table_prefix}{table}")
        )

    spread = distributed_tables(engine, chunk_rows)
    rows: dict[str, int] = {}
    if spread:
        spec_json = json.dumps(spec, default=str)
        broadcast = spark.sparkContext.broadcast(spec_json)
        for table in spread:
            total = int(engine.row_counts[table])
            chunks = math.ceil(total / chunk_rows)
            sample = engine.generate_chunk(table, 0, 0, chunk=0)
            ids = spark.range(0, chunks, 1, chunks)
            frame = ids.mapInArrow(
                _chunk_batches(broadcast.value, table), arrow_to_ddl(sample.schema)
            )
            save(frame, table)
            rows[table] = total
            log(f"  wrote {table}: {total:,} rows in {chunks} chunk(s), made on the executors")
    rest = [n for n in engine.order if n not in rows]
    if rest:
        result = engine.generate()
        from shape.integrations.fabric.generation import delta_ready

        for table in rest:
            arrow = delta_ready(result.tables[table])
            save(spark.createDataFrame(arrow.to_pandas()), table)
            rows[table] = arrow.num_rows
            log(f"  wrote {table}: {arrow.num_rows:,} rows, made on the driver")
    return {
        "status": "succeeded",
        "rows_generated": sum(rows.values()),
        "tables": rows,
        "distributed": spread,
    }


def check_result(spec: Mapping[str, Any], result: Mapping[str, Any]) -> None:
    """Raise when the tables written do not have the row counts the spec asked for."""
    wanted = {k: int(v) for k, v in spec["row_counts"].items() if k in spec["schema"]["tables"]}
    got = dict(result["tables"])
    wrong = {k: (wanted[k], got.get(k)) for k in wanted if got.get(k) != wanted[k]}
    if wrong:
        raise RuntimeError(f"row counts differ from the spec (wanted, written): {wrong}")
