"""A small, deterministic set of payer tables for tests and examples.

``sample_tables()`` returns every contract table with a few rows that exercise what the
writers must handle: a subscriber with a spouse and a child, a terminated span, professional
claims (paid, denied with CARC/RARC, a replacement), an inpatient institutional claim with
DRG, revenue codes, ICD-10-PCS and present-on-admission flags, and pharmacy claims (paid,
rejected, reversed).

Every identifier is synthetic: NPIs start with 9 (real NPIs start with 1 or 2) and carry a
valid check digit; names, ids and addresses are invented.
"""

from __future__ import annotations

import datetime as dt
from typing import Any

import pyarrow as pa  # type: ignore[import-untyped]

from . import contract
from .codes import luhn_npi

D = dt.date


def npi(n: int) -> str:
    """Synthetic NPI number ``n``: leading 9 (outside the real 1/2 range) and a check digit."""
    return luhn_npi(f"9{n:08d}")


BILLING = npi(1)
RENDERING = npi(2)
FACILITY = npi(3)
ATTENDING = npi(4)
PCP = npi(5)
PRESCRIBER = npi(6)
PHARMACY = npi(7)


def _table(name: str, rows: list[dict[str, Any]]) -> pa.Table:
    schema = contract.contract_schema(name)
    cols = {f.name: [r.get(f.name) for r in rows] for f in schema}
    return pa.table(cols, schema=schema)


def sample_tables() -> dict[str, pa.Table]:
    members = [
        dict(
            member_id="SYN100001-00",
            subscriber_id="SYN100001",
            member_suffix="00",
            relationship_code="18",
            first_name="Alex",
            last_name="Rivera",
            middle_name="J",
            birth_date=D(1978, 4, 12),
            sex="M",
            address_line1="100 Example Way",
            city="Springfield",
            state="IL",
            zip="62701",
            phone="2175550101",
            race="White",
            ethnicity="Not Hispanic or Latino",
            language="eng",
            marital_status="M",
        ),
        dict(
            member_id="SYN100001-01",
            subscriber_id="SYN100001",
            member_suffix="01",
            relationship_code="01",
            first_name="Jordan",
            last_name="Rivera",
            birth_date=D(1980, 9, 3),
            sex="F",
            address_line1="100 Example Way",
            city="Springfield",
            state="IL",
            zip="62701",
            race="Black or African American",
            ethnicity="Not Hispanic or Latino",
            language="eng",
            marital_status="M",
        ),
        dict(
            member_id="SYN100001-02",
            subscriber_id="SYN100001",
            member_suffix="02",
            relationship_code="19",
            first_name="Sam",
            last_name="Rivera",
            birth_date=D(2012, 1, 20),
            sex="M",
            address_line1="100 Example Way",
            city="Springfield",
            state="IL",
            zip="62701",
            race="White",
            ethnicity="Hispanic or Latino",
            language="spa",
            marital_status="I",
        ),
        dict(
            member_id="SYN200001-00",
            subscriber_id="SYN200001",
            member_suffix="00",
            relationship_code="18",
            first_name="Casey",
            last_name="Okafor",
            birth_date=D(1951, 11, 30),
            sex="F",
            address_line1="55 Sample Road",
            address_line2="Apt 4",
            city="Peoria",
            state="IL",
            zip="616040001",
            race="Asian",
            ethnicity="Not Hispanic or Latino",
            language="eng",
            marital_status="I",
        ),
    ]
    eligibility = [
        dict(
            eligibility_id="E1",
            member_id="SYN100001-00",
            plan_id="PLN-COM-1",
            coverage_start=D(2023, 1, 1),
            coverage_end=None,
            group_id="GRP0001",
            group_name="Example Employer",
            plan_name="Example PPO",
            plan_type="COMMERCIAL",
            coverage_level="FAM",
            insurance_line="HLT",
            payer_id="SYNPAYER01",
            payer_name="Example Health Plan",
            pcp_npi=PCP,
            cob_flag=False,
        ),
        dict(
            eligibility_id="E2",
            member_id="SYN100001-01",
            plan_id="PLN-COM-1",
            coverage_start=D(2023, 1, 1),
            coverage_end=D(2024, 6, 30),
            group_id="GRP0001",
            group_name="Example Employer",
            plan_name="Example PPO",
            plan_type="COMMERCIAL",
            coverage_level="FAM",
            insurance_line="HLT",
            payer_id="SYNPAYER01",
            payer_name="Example Health Plan",
            pcp_npi=PCP,
            cob_flag=True,
            termination_reason="voluntary",
        ),
        dict(
            eligibility_id="E3",
            member_id="SYN100001-02",
            plan_id="PLN-COM-1",
            coverage_start=D(2023, 1, 1),
            coverage_end=None,
            group_id="GRP0001",
            group_name="Example Employer",
            plan_name="Example PPO",
            plan_type="COMMERCIAL",
            coverage_level="FAM",
            insurance_line="HLT",
            payer_id="SYNPAYER01",
            payer_name="Example Health Plan",
            pcp_npi=PCP,
            cob_flag=False,
        ),
        dict(
            eligibility_id="E4",
            member_id="SYN200001-00",
            plan_id="PLN-MA-1",
            coverage_start=D(2024, 1, 1),
            coverage_end=None,
            group_id="GRP0002",
            group_name="Example Medicare Advantage",
            plan_name="Example MA HMO",
            plan_type="MEDICARE_ADVANTAGE",
            coverage_level="IND",
            insurance_line="HLT",
            payer_id="SYNPAYER01",
            payer_name="Example Health Plan",
            pcp_npi=PCP,
            cob_flag=False,
        ),
    ]
    providers = [
        dict(
            npi=BILLING,
            entity_type="2",
            org_name="Example Medical Group",
            taxonomy_code="207Q00000X",
            specialty="Family Medicine",
            tax_id="900000001",
            address_line1="1 Clinic Plaza",
            city="Springfield",
            state="IL",
            zip="62701",
            network_status="IN",
        ),
        dict(
            npi=RENDERING,
            entity_type="1",
            last_name="Nguyen",
            first_name="Taylor",
            taxonomy_code="207Q00000X",
            specialty="Family Medicine",
            tax_id="900000001",
            address_line1="1 Clinic Plaza",
            city="Springfield",
            state="IL",
            zip="62701",
            network_status="IN",
        ),
        dict(
            npi=FACILITY,
            entity_type="2",
            org_name="Example General Hospital",
            taxonomy_code="282N00000X",
            specialty="General Acute Care Hospital",
            tax_id="900000002",
            address_line1="500 Hospital Drive",
            city="Springfield",
            state="IL",
            zip="62702",
            network_status="IN",
        ),
        dict(
            npi=ATTENDING,
            entity_type="1",
            last_name="Brooks",
            first_name="Morgan",
            taxonomy_code="207R00000X",
            specialty="Internal Medicine",
            tax_id="900000002",
            address_line1="500 Hospital Drive",
            city="Springfield",
            state="IL",
            zip="62702",
            network_status="IN",
        ),
        dict(
            npi=PCP,
            entity_type="1",
            last_name="Patel",
            first_name="Riley",
            taxonomy_code="207Q00000X",
            specialty="Family Medicine",
            tax_id="900000001",
            address_line1="1 Clinic Plaza",
            city="Springfield",
            state="IL",
            zip="62701",
            network_status="IN",
        ),
        dict(
            npi=PRESCRIBER,
            entity_type="1",
            last_name="Kim",
            first_name="Avery",
            taxonomy_code="207Q00000X",
            specialty="Family Medicine",
            tax_id="900000003",
            address_line1="2 Clinic Plaza",
            city="Springfield",
            state="IL",
            zip="62701",
            network_status="IN",
        ),
        dict(
            npi=PHARMACY,
            entity_type="2",
            org_name="Example Pharmacy",
            taxonomy_code="333600000X",
            specialty="Pharmacy",
            tax_id="900000004",
            address_line1="9 Main Street",
            city="Springfield",
            state="IL",
            zip="62701",
            network_status="IN",
            ncpdp_id="9000001",
        ),
    ]
    claims = [
        dict(  # professional, paid
            claim_id="CLM-P-0001",
            claim_type="P",
            member_id="SYN100001-00",
            billing_npi=BILLING,
            rendering_npi=RENDERING,
            facility_npi=FACILITY,
            service_from_date=D(2024, 2, 5),
            service_to_date=D(2024, 2, 5),
            place_of_service="11",
            claim_frequency_code="1",
            total_billed=300.0,
            total_allowed=210.0,
            total_paid=170.0,
            member_copay=30.0,
            member_coinsurance=0.0,
            member_deductible=10.0,
            received_date=D(2024, 2, 10),
            adjudication_date=D(2024, 2, 15),
            claim_status="paid",
            plan_id="PLN-COM-1",
            payer_id="SYNPAYER01",
            payer_name="Example Health Plan",
            payer_claim_number="PCN-0001",
        ),
        dict(  # professional, one line denied
            claim_id="CLM-P-0002",
            claim_type="P",
            member_id="SYN100001-01",
            billing_npi=BILLING,
            rendering_npi=RENDERING,
            service_from_date=D(2024, 3, 14),
            service_to_date=D(2024, 3, 14),
            place_of_service="11",
            claim_frequency_code="1",
            total_billed=450.5,
            total_allowed=150.0,
            total_paid=120.0,
            member_copay=20.0,
            member_coinsurance=10.0,
            member_deductible=0.0,
            received_date=D(2024, 3, 20),
            adjudication_date=D(2024, 3, 28),
            claim_status="paid",
            plan_id="PLN-COM-1",
            payer_id="SYNPAYER01",
            payer_name="Example Health Plan",
            prior_auth_number="PA12345",
        ),
        dict(  # professional, replacement of CLM-P-0001-ORIG
            claim_id="CLM-P-0003",
            claim_type="P",
            member_id="SYN200001-00",
            billing_npi=BILLING,
            rendering_npi=RENDERING,
            service_from_date=D(2024, 5, 2),
            service_to_date=D(2024, 5, 2),
            place_of_service="22",
            claim_frequency_code="7",
            total_billed=1200.0,
            total_allowed=800.0,
            total_paid=700.0,
            member_copay=0.0,
            member_coinsurance=100.0,
            member_deductible=0.0,
            received_date=D(2024, 5, 9),
            adjudication_date=D(2024, 5, 20),
            claim_status="adjusted",
            original_claim_id="CLM-P-0003-ORIG",
            plan_id="PLN-MA-1",
            payer_id="SYNPAYER01",
            payer_name="Example Health Plan",
        ),
        dict(  # institutional inpatient
            claim_id="CLM-I-0001",
            claim_type="I",
            member_id="SYN200001-00",
            billing_npi=FACILITY,
            facility_npi=FACILITY,
            attending_npi=ATTENDING,
            type_of_bill="111",
            admission_date=D(2024, 6, 10),
            discharge_date=D(2024, 6, 14),
            service_from_date=D(2024, 6, 10),
            service_to_date=D(2024, 6, 14),
            admission_type_code="1",
            patient_status_code="01",
            drg_code="871",
            claim_frequency_code="1",
            total_billed=42000.0,
            total_allowed=18000.0,
            total_paid=17000.0,
            member_copay=0.0,
            member_coinsurance=1000.0,
            member_deductible=0.0,
            received_date=D(2024, 6, 20),
            adjudication_date=D(2024, 7, 1),
            claim_status="paid",
            plan_id="PLN-MA-1",
            payer_id="SYNPAYER01",
            payer_name="Example Health Plan",
        ),
    ]
    lines = [
        dict(
            claim_id="CLM-P-0001",
            line_number=1,
            procedure_code="99213",
            service_date=D(2024, 2, 5),
            billed_amount=200.0,
            units=1.0,
            place_of_service="11",
            diagnosis_pointers="1",
            allowed_amount=140.0,
            paid_amount=110.0,
            copay=30.0,
            coinsurance=0.0,
            deductible=0.0,
            line_status="paid",
        ),
        dict(
            claim_id="CLM-P-0001",
            line_number=2,
            procedure_code="83036",
            modifier_1="QW",
            service_date=D(2024, 2, 5),
            billed_amount=100.0,
            units=1.0,
            place_of_service="11",
            diagnosis_pointers="1,2",
            allowed_amount=70.0,
            paid_amount=60.0,
            copay=0.0,
            coinsurance=0.0,
            deductible=10.0,
            line_status="paid",
        ),
        dict(
            claim_id="CLM-P-0002",
            line_number=1,
            procedure_code="99214",
            modifier_1="25",
            service_date=D(2024, 3, 14),
            billed_amount=250.5,
            units=1.0,
            place_of_service="11",
            diagnosis_pointers="1",
            allowed_amount=150.0,
            paid_amount=120.0,
            copay=20.0,
            coinsurance=10.0,
            deductible=0.0,
            line_status="paid",
        ),
        dict(
            claim_id="CLM-P-0002",
            line_number=2,
            procedure_code="97110",
            modifier_1="GP",
            service_date=D(2024, 3, 14),
            billed_amount=200.0,
            units=2.0,
            place_of_service="11",
            diagnosis_pointers="1",
            allowed_amount=0.0,
            paid_amount=0.0,
            copay=0.0,
            coinsurance=0.0,
            deductible=0.0,
            line_status="denied",
            denial_carc="50",
            denial_rarc="N115",
        ),
        dict(
            claim_id="CLM-P-0003",
            line_number=1,
            procedure_code="99223",
            service_date=D(2024, 5, 2),
            billed_amount=1200.0,
            units=1.0,
            place_of_service="22",
            diagnosis_pointers="1,2",
            allowed_amount=800.0,
            paid_amount=700.0,
            copay=0.0,
            coinsurance=100.0,
            deductible=0.0,
            line_status="adjusted",
        ),
        dict(
            claim_id="CLM-I-0001",
            line_number=1,
            revenue_code="0120",
            service_date=D(2024, 6, 10),
            billed_amount=12000.0,
            units=4.0,
            allowed_amount=6000.0,
            paid_amount=5700.0,
            coinsurance=300.0,
            line_status="paid",
        ),
        dict(
            claim_id="CLM-I-0001",
            line_number=2,
            revenue_code="0250",
            service_date=D(2024, 6, 10),
            billed_amount=8000.0,
            units=1.0,
            allowed_amount=3000.0,
            paid_amount=2900.0,
            coinsurance=100.0,
            line_status="paid",
        ),
        dict(
            claim_id="CLM-I-0001",
            line_number=3,
            revenue_code="0450",
            procedure_code="99285",
            service_date=D(2024, 6, 10),
            billed_amount=22000.0,
            units=1.0,
            allowed_amount=9000.0,
            paid_amount=8400.0,
            coinsurance=600.0,
            line_status="paid",
        ),
    ]
    diagnoses = [
        dict(claim_id="CLM-P-0001", sequence=1, icd10_code="E119", diagnosis_type="principal"),
        dict(claim_id="CLM-P-0001", sequence=2, icd10_code="I10", diagnosis_type="secondary"),
        dict(claim_id="CLM-P-0002", sequence=1, icd10_code="M545", diagnosis_type="principal"),
        dict(claim_id="CLM-P-0003", sequence=1, icd10_code="J189", diagnosis_type="principal"),
        dict(claim_id="CLM-P-0003", sequence=2, icd10_code="N1830", diagnosis_type="secondary"),
        dict(
            claim_id="CLM-I-0001",
            sequence=1,
            icd10_code="J189",
            diagnosis_type="principal",
            poa_indicator="Y",
        ),
        dict(
            claim_id="CLM-I-0001",
            sequence=2,
            icd10_code="E1165",
            diagnosis_type="secondary",
            poa_indicator="Y",
        ),
        dict(
            claim_id="CLM-I-0001",
            sequence=3,
            icd10_code="N1830",
            diagnosis_type="secondary",
            poa_indicator="Y",
        ),
        dict(
            claim_id="CLM-I-0001",
            sequence=4,
            icd10_code="Z794",
            diagnosis_type="secondary",
            poa_indicator="Y",
        ),
    ]
    procedures = [
        dict(
            claim_id="CLM-I-0001",
            sequence=1,
            icd10pcs_code="0BH17EZ",
            procedure_date=D(2024, 6, 11),
        ),
    ]
    rx = [
        dict(
            rx_claim_id="RX-0001",
            member_id="SYN100001-00",
            ndc="00093726001",
            fill_date=D(2024, 2, 6),
            written_date=D(2024, 2, 5),
            quantity=60.0,
            days_supply=30,
            pharmacy_npi=PHARMACY,
            prescriber_npi=PRESCRIBER,
            rx_number="1000001",
            refill_number=0,
            daw_code="0",
            drug_name="Metformin 500 mg",
            pharmacy_ncpdp_id="9000001",
            ingredient_cost=4.5,
            dispensing_fee=1.5,
            patient_pay=5.0,
            plan_paid=1.0,
            claim_status="paid",
            mail_order=False,
            formulary_tier=1,
            plan_id="PLN-COM-1",
            bin_number="900001",
            pcn="SYNPCN",
            group_id="GRP0001",
        ),
        dict(
            rx_claim_id="RX-0002",
            member_id="SYN100001-00",
            ndc="00093726001",
            fill_date=D(2024, 3, 7),
            written_date=D(2024, 2, 5),
            quantity=60.0,
            days_supply=30,
            pharmacy_npi=PHARMACY,
            prescriber_npi=PRESCRIBER,
            rx_number="1000001",
            refill_number=1,
            daw_code="0",
            drug_name="Metformin 500 mg",
            pharmacy_ncpdp_id="9000001",
            ingredient_cost=0.0,
            dispensing_fee=0.0,
            patient_pay=0.0,
            plan_paid=0.0,
            claim_status="rejected",
            reject_code="79",
            mail_order=False,
            formulary_tier=1,
            plan_id="PLN-COM-1",
            bin_number="900001",
            pcn="SYNPCN",
            group_id="GRP0001",
        ),
        dict(
            rx_claim_id="RX-0003",
            member_id="SYN200001-00",
            ndc="00071015523",
            fill_date=D(2024, 5, 3),
            written_date=D(2024, 5, 2),
            quantity=90.0,
            days_supply=90,
            pharmacy_npi=PHARMACY,
            prescriber_npi=PRESCRIBER,
            rx_number="1000002",
            refill_number=0,
            daw_code="1",
            drug_name="Atorvastatin 40 mg",
            pharmacy_ncpdp_id="9000001",
            ingredient_cost=12.0,
            dispensing_fee=2.0,
            patient_pay=10.0,
            plan_paid=4.0,
            claim_status="reversed",
            mail_order=True,
            formulary_tier=2,
            plan_id="PLN-MA-1",
            bin_number="900001",
            pcn="SYNPCN",
            group_id="GRP0002",
        ),
    ]
    drugs = [
        dict(
            ndc="00093726001",
            drug_name="Metformin Hydrochloride",
            generic_name="metformin",
            strength="500 mg",
            dose_form="TABLET",
            route="ORAL",
            rxnorm_code="861007",
            therapeutic_class="Antidiabetic",
            brand_generic="generic",
            labeler="Example Labs",
        ),
        dict(
            ndc="00071015523",
            drug_name="Lipitor",
            generic_name="atorvastatin calcium",
            strength="40 mg",
            dose_form="TABLET, FILM COATED",
            route="ORAL",
            rxnorm_code="617310",
            therapeutic_class="Statin",
            brand_generic="brand",
            labeler="Example Pharma",
        ),
    ]
    acknowledgments = [
        dict(  # accepted, entity given, payer control number from the claim
            claim_id="CLM-P-0001",
            acknowledgment_date=D(2024, 3, 21),
            status_category_code="A2",
            status_code="20",
            entity_identifier_code="PR",
            reference_number="PCN-0001",
            received_date=D(2024, 2, 10),
        ),
        dict(  # accepted at claim level, with one rejected service line below
            claim_id="CLM-P-0002",
            acknowledgment_date=D(2024, 3, 21),
            status_category_code="A2",
            status_code="20",
            entity_identifier_code="PR",
        ),
        dict(
            claim_id="CLM-P-0002",
            acknowledgment_date=D(2024, 3, 21),
            status_category_code="A7",
            status_code="21",
            line_number=2,
            entity_identifier_code="PR",
        ),
        dict(  # rejected claim, action code given explicitly
            claim_id="CLM-P-0003",
            acknowledgment_date=D(2024, 3, 21),
            status_category_code="A3",
            status_code="21",
            entity_identifier_code="PR",
            action_code="U",
        ),
        dict(  # accepted, institutional, on a later date
            claim_id="CLM-I-0001",
            acknowledgment_date=D(2024, 6, 22),
            status_category_code="A1",
            status_code="20",
            entity_identifier_code="PR",
            reference_number="ICN-I-0001",
            received_date=D(2024, 6, 20),
        ),
    ]
    return {
        "claim_acknowledgment": _table("claim_acknowledgment", acknowledgments),
        "member": _table("member", members),
        "eligibility": _table("eligibility", eligibility),
        "provider": _table("provider", providers),
        "medical_claim": _table("medical_claim", claims),
        "medical_claim_line": _table("medical_claim_line", lines),
        "claim_diagnosis": _table("claim_diagnosis", diagnoses),
        "claim_procedure": _table("claim_procedure", procedures),
        "pharmacy_claim": _table("pharmacy_claim", rx),
        "drug_reference": _table("drug_reference", drugs),
    }
