# ruff: noqa: E501
"""Content digests of the packaged domain schemas. Generated by
``scripts/update_domain_digests.py``; do not edit (see ``shape_domains._packaged``)."""

from __future__ import annotations

JSON_SCHEMA = "b4afd188fc35efe6f0629b43495e63f1c05933308ba758650c8dd0e6d9ea512a"

SCHEMAS = {
    "capital_markets/schema.json": "5e3e4639a12b41a13384f6b2299edf7725b48e47c6866fb240d4ad6a162ea20d",
    "capital_markets/schema_star.json": "d771d0d19171b82adb3cc339c428b8b9eb78b7bd01092fdbc079d0ed857dd3a1",
    "education/schema.json": "492d6a6989f095c1079cb83b9e4ffc4b37c5cbc42a3bedac54fb6da7723ec28e",
    "education/schema_star.json": "ea4770a4bff975c55c2f3603164a1db2b577bafac456cab5a157d7df789f0f38",
    "financial/schema.json": "c12ed960270378aedcb5b61b5bfa86c6e2bc9e402d64fb10e135fd3c86d0e0de",
    "financial/schema_star.json": "8604f03a8d7dba6b64423535b203821d73618eca6b5560293818c1731fc3f2e5",
    "healthcare/schema.json": "5cdff7ba0071a6f003e7d1675fc62aad783f7a25b2a168a17a5872196f7e8fe2",
    "healthcare/schema_star.json": "c9e78b43cff5d7e336436f3608b708ebf941fdd2b96a5daa5f9ac934549ae7a5",
    "hr/schema.json": "0b72f621763fd707cdbf2b3148f6cc818bfaf8c6239d204553de46adea1e44b6",
    "hr/schema_star.json": "e8eb83236f1379267671719174668915bebdd59eec745b066a09e3b85c56647c",
    "insurance/schema.json": "0888b6360aced982e727205a1d6d27b515e506f5d7a4d4f8a2a9fd5801a45ebb",
    "insurance/schema_star.json": "eadca859ef55a686462711e4409fe6f4e240e1a8e2758a6418c4c880bac357d5",
    "iot/schema.json": "8ff3edb38bb3d5f47ca999f506a228093843de2cf40fd9b104cc93e4091504eb",
    "iot/schema_star.json": "43ba8b18d785496dd6e96c825bd3761ed43572d794e04a9ffdf4716c8ce77202",
    "manufacturing/schema.json": "f19022eecb1ee2f184266c8a01f700853a8fac98afaa16f8e5cfe549dc746bcd",
    "manufacturing/schema_star.json": "d1a1e85fc503a7267b1d29cd2fcc2db6accec38dc7a2f089ab406d75d811759c",
    "marketing/schema.json": "f25d5b40d7342a6a03525a6b47a6ef1005aca2e72f1bcb8902b33dacf1e8bd9e",
    "marketing/schema_star.json": "42ed9a618aaa34bfdd3e79375301f55d98850f34520ddc8150db284186d623ca",
    "pulse/schema.json": "d4b94b559afb010dc9f32da80fc8e9c687ee0f63f61f48246c659a006b4c0ce4",
    "pulse/schema_star.json": "adedf62c9675b12cf84a1aa782cd47b58ff7bd816546f2f270fb7c0fa6331294",
    "real_estate/schema.json": "f18eb210bd353faa2b5e652585b2976615185a559547cfd7cd002acc2230244e",
    "real_estate/schema_star.json": "a0a76669f625a14c13e0d36c898786ca8470b91ef20199641f01fa9009d97fa8",
    "retail/schema.json": "5b1fdfb31f5e7ce15a7a647ec2bb4e12bbfab2277cafe53eb4260dfdacfaec63",
    "retail/schema_star.json": "f7be6743e5077a38609dbc95dfa097a4b46238fcca31c9dc542c28c443d7fd47",
    "supply_chain/schema.json": "86adabf1a3bf02518c650991de341adc36850d5065de8bc505189e6d956cdfbb",
    "supply_chain/schema_star.json": "a25563e79ba9621e3bf836d38e36154be4214c1954ea968b946f30fa98cab118",
    "telecom/schema.json": "0a9e7f1d4ab7f7b6900998bd62bd49308c57ce543cec5bb0a3fe0a12d5404f61",
    "telecom/schema_star.json": "98241891bdc49db60b08521432c27deb4796c020003392181ec509a4c5c957f5",
}
