# ruff: noqa: E501
"""Content digests of the packaged domain schemas. Generated by
``scripts/update_domain_digests.py``; do not edit (see ``shape_domains._packaged``)."""

from __future__ import annotations

JSON_SCHEMA = "aa19e19d2a9317fab5978a5dd516a71d2481c7902d8bc2d7acd63ec875cfab17"

SCHEMAS = {
    "capital_markets/schema.json": "5e3e4639a12b41a13384f6b2299edf7725b48e47c6866fb240d4ad6a162ea20d",
    "capital_markets/schema_star.json": "d771d0d19171b82adb3cc339c428b8b9eb78b7bd01092fdbc079d0ed857dd3a1",
    "education/schema.json": "567fe605ded9236e3542ae121e6a5d855025da4f5d71a0a3ef682b5da5c0496b",
    "education/schema_star.json": "f272372a87b6596188d72c2a77465dce934936e96d93196a1878e493ff240273",
    "financial/schema.json": "1c916dc637d01e101a3760c6ba14bee98cc3948de556c9d64258ca0af24c5db9",
    "financial/schema_star.json": "912f8be6f499c367f7f3de936b0e0d1c53226a11aedf172250b2ec82be8740e5",
    "healthcare/schema.json": "7d0b79e9601eddfde208a96da34ff41e63e46dfae88ba3a755dc3eeecaef9038",
    "healthcare/schema_star.json": "e84646bde25c901e4df8396a6f2998f8bc661329e271ea6f2433e13b99c56669",
    "hr/schema.json": "37b834d9bf4d104056757c0cd6d7433100cfe40558ed9fed6e9151c4fdb6cd4d",
    "hr/schema_star.json": "dd2b91bab3ae443854ec223d6781dcf5a99d4171e16363f5f704756ef604e30d",
    "insurance/schema.json": "b365ffa815f1185254a06565d4de66ef8c477583c8f1090c95cda1239120d77f",
    "insurance/schema_star.json": "e882747017a975ad20fe5598ab19435d06d3b7ae94ee0d70cb7745c3a24787f6",
    "iot/schema.json": "88c85d4730e80fb042bc3b73eb29d634cf49295675369267ba6bebf2a21b4152",
    "iot/schema_star.json": "870e7be471367c9d1768dd526541fb85237edf23308ed077ab4bc4c30d885831",
    "manufacturing/schema.json": "18308df3092d946230eea9dde4729e276862c5673f08363d6b8adac37bfd82db",
    "manufacturing/schema_star.json": "844823b46451c4a6d3f554ba698259167ad2e7e35481d1380ef8455cab0cb620",
    "marketing/schema.json": "921cfaf7d6d23147c5abdd641dd4ddbf98248d34144f3b8c8722f322c2682d0d",
    "marketing/schema_star.json": "19060feec1bdcf2b5f5b23f13e4370631cda70f533246ec17b0196faa9d6c081",
    "pulse/schema.json": "d4b94b559afb010dc9f32da80fc8e9c687ee0f63f61f48246c659a006b4c0ce4",
    "pulse/schema_star.json": "adedf62c9675b12cf84a1aa782cd47b58ff7bd816546f2f270fb7c0fa6331294",
    "real_estate/schema.json": "ce67e3dceaa868a60fcb96a3913f31e4183ae01c97c6ad438aa8e56fe13d9263",
    "real_estate/schema_star.json": "7ee4e4782cb1972f05a13516454e2ec57351b09a78a38a2d4497e54cf7f8d250",
    "retail/schema.json": "5b1fdfb31f5e7ce15a7a647ec2bb4e12bbfab2277cafe53eb4260dfdacfaec63",
    "retail/schema_star.json": "f7be6743e5077a38609dbc95dfa097a4b46238fcca31c9dc542c28c443d7fd47",
    "supply_chain/schema.json": "239c62c30275bac6d2e2ebc06cc215d41614c7c5db8cfcba18227ff3bde623de",
    "supply_chain/schema_star.json": "9beea8432d97d8059816b9e8c84e19f0945f22ce6f4db974264d3f57ba1abb42",
    "telecom/schema.json": "e569e78b5d803c0cc2204245fc000af0997511cd89b3e2b600656542b42670b4",
    "telecom/schema_star.json": "c327b1a8498b47252e5b09b00fa10bbdaf3933c5e1a0cf9e02c02126d315877c",
}
