"""Generate ``docs/plugins/api-v1.md`` from ``shape.plugins.api.v1`` (P2-01).

``--check`` exits 1 when the committed page differs from the generated one.
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "plugins" / "api-v1.md"


def _members(proto: type) -> list[str]:
    lines = []
    for name, obj in vars(proto).items():
        if name.startswith("_"):
            continue
        if callable(obj):
            lines.append(f"- `{name}{str(inspect.signature(obj)).replace(chr(39), '')}`")
    return lines


def _attrs(proto: type) -> list[str]:
    return [f"- `{n}: {t}`" for n, t in getattr(proto, "__annotations__", {}).items()]


def render() -> str:
    from shape.plugins.api import v1

    out = [
        "# Plugin API v1",
        "",
        "<!-- Generated by scripts/gen_plugin_api_docs.py from shape.plugins.api.v1 -->",
        "",
        f'`SHAPE_API = "{v1.SHAPE_API}"`. A plugin module declares its own `SHAPE_API = "1.x"`;',
        "the host rejects any other major version. Plugins are trusted, in-process code.",
        "Hooks take and return whole Arrow batches or arrays, never single values or rows.",
        "A plugin satisfies a Protocol structurally; it does not import or subclass it.",
        "What stays stable within 1.x, what counts as a breaking change and how deprecation works",
        "are in [stability.md](stability.md).",
        "",
        "| Entry-point group | Protocol |",
        "|---|---|",
    ]
    out += [f"| `{g}` | `{p}` |" for g, p in v1.GROUPS.items()]
    for group, pname in v1.GROUPS.items():
        proto = v1.PROTOCOLS[pname]
        out += ["", f"## `{pname}`", "", f"Entry-point group `{group}`.", ""]
        doc = inspect.getdoc(proto)
        if doc:
            out += [doc, ""]
        attrs = _attrs(proto)
        if attrs:
            out += ["Attributes:", "", *attrs, ""]
        out += ["Methods:", "", *_members(proto)]
    out += ["", "## Data types", ""]
    for n in v1.__all__:
        obj = getattr(v1, n)
        if inspect.isclass(obj) and obj not in v1.PROTOCOLS.values():
            out += [f"### `{n}`", "", inspect.getdoc(obj) or "", ""]
            out += [f"- `{k}: {t}`" for k, t in obj.__annotations__.items()] + [""]
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    if a.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is out of date; run scripts/gen_plugin_api_docs.py")
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
