"""Generate the docs performance page from the benchmark results (T-24, P8-02).

    python scripts/gen_performance_page.py                       # write docs/PERFORMANCE.md
    python scripts/gen_performance_page.py --check               # exit 1 if the page is stale
    python scripts/gen_performance_page.py --results R --history H --out PAGE

The input is a ``benchmarks/vs_refengine/results.json`` (``run.py``, or the nightly suite's
merged file with its ``nightly`` block) and, optionally, the nightly history
(``nightly.py merge --history``).

Publication rules (plan section 6.4: equivalence before timing):

* Only the product (``shape``) is published; the harness's own reference port is not.
* A workload's numbers are published only when its equivalence verifier exited 0, and, where
  the timed output was verified a second time, that run exited 0 too. Every other workload is
  listed with its verifier status and no number.
* Nothing is published from a modified tree: if the results say the Shape tree was dirty, no
  number is published at all.
* The page never names the baseline library (D-13): the generator refuses to write a page whose
  text contains that name (checked by hash, ``refengine_name.py``) or its results key.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from refengine_name import names_refengine  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_RESULTS = ROOT / "benchmarks" / "vs_refengine" / "results.json"
DEFAULT_OUT = ROOT / "docs" / "PERFORMANCE.md"
BASELINE_KEY = "refengine"  # the results' key for the baseline; never written to the page
IMPL = "shape"
KIND_TITLES = {
    "profile": "Profiling (in-process, exact)",
    "generate": "Generation (generate and write Parquet)",
    "stream": "Streaming (retail `order` events to a file)",
}
DATASETS = {
    "d1": "D1 (200k rows x 6 columns)",
    "d2": "D2 (1M rows x 20 columns)",
    "d3": "D3 (5M rows x 10 columns)",
    "d4": "D4 (100k rows x 200 columns)",
    "mt": "MT (3 tables, foreign-key detection)",
}


class PageError(Exception):
    """The page cannot be generated as the rules require."""


def verifier_ok(rec: dict[str, Any]) -> bool:
    """True when the workload's verifier exited 0 (and its re-run on the timed output, if any)."""
    ver = rec.get("verifier")
    if not isinstance(ver, dict) or ver.get("status") != "pass" or ver.get("exit_code") != 0:
        return False
    first = ver.get("first_run")
    return first is None or (first.get("status") == "pass" and first.get("exit_code") == 0)


def baseline_median(results: dict[str, Any], wid: str, rec: dict[str, Any]) -> float | None:
    if rec.get("refengine_median_s") is not None:
        return float(rec["refengine_median_s"])
    base = ((results.get(BASELINE_KEY) or {}).get("workloads") or {}).get(wid) or {}
    med = base.get("median_s")
    return None if med is None else float(med)


def publishable(results: dict[str, Any], wid: str, rec: dict[str, Any]) -> tuple[bool, str]:
    """(publish?, why not)."""
    if results.get("shape_tree_dirty"):
        return False, "modified tree"
    if not verifier_ok(rec):
        ver = rec.get("verifier") or {}
        return False, f"verifier {ver.get('status', 'not run')}"
    if (
        rec.get("median_s") is None
        or rec.get("speedup_vs_refengine") is None
        or baseline_median(results, wid, rec) is None
    ):
        return False, "no timing recorded"
    return True, ""


def label(rec: dict[str, Any], wid: str) -> str:
    kind = rec.get("kind")
    if kind == "profile":
        ds = str(rec.get("dataset", wid.split(":", 1)[-1]))
        stem, _, ext = ds.partition(".")
        name = DATASETS.get(stem, stem.upper())
        return f"{name}, {ext.upper()}" if ext else name
    if kind == "generate":
        return f"{rec.get('domain')}, {rec.get('scale')}"
    if kind == "stream":
        return f"{rec.get('domain', 'retail')} `order`, {rec.get('scale')}"
    return wid


def _fmt_s(x: float) -> str:
    return f"{x:.3f}" if x < 10 else f"{x:.1f}"


def render(results: dict[str, Any], history: list[dict[str, Any]] | None = None) -> str:
    """The page, as Markdown."""
    shape = (results.get(IMPL) or {}).get("workloads") or {}
    machine = results.get("machine") or {}
    lines = [
        "# Performance",
        "",
        "Status: available.",
        "",
        "<!-- Generated by scripts/gen_performance_page.py from the benchmark results; "
        "do not edit by hand. -->",
        "",
        "Every speed-up on this page is a ratio measured in one job: Shape and the baseline "
        "library it replaces run the same workload on the same machine, each in a fresh "
        "process, and the median of the runs is reported. **A workload's numbers are "
        "published only after its equivalence verifier exited 0**: Shape's output must be "
        "statistically equivalent to the baseline's (same tables, columns, distributions and "
        "relationships within fixed tolerances, with fixed seeds) before any timing counts. A"
        " workload whose verifier did not pass is listed without numbers.",
        "",
        f"- Measured: {results.get('generated_utc', '?')}, mode `{results.get('mode', '?')}`, "
        f"{results.get('runs', '?')} runs per tool.",
        f"- Shape commit: `{str(results.get('shape_commit', '?'))[:12]}`"
        + (" (modified tree: nothing is published)" if results.get("shape_tree_dirty") else ""),
        f"- Machine: {machine.get('cores', '?')} cores, {machine.get('cpu', '?')}, "
        f"Python {machine.get('python', '?')}.",
        "",
    ]
    nightly = results.get("nightly")
    if isinstance(nightly, dict):
        lines += [
            "## Nightly parity suite",
            "",
            f"This run: **{'green' if nightly.get('green') else 'red'}**, "
            f"{nightly.get('passed', 0)} of {nightly.get('required', 0)} workloads verified.",
            "",
        ]
    if history is not None:
        recent = [r for r in history if r.get("event") == "schedule" and r.get("full_suite")]
        lines += ["## Recent nights", ""]
        if recent:
            lines += ["| Night | Commit | Result | Verified |", "|---|---|---|---|"]
            for r in sorted(recent, key=lambda r: str(r.get("date")), reverse=True)[:14]:
                lines.append(
                    f"| {r.get('date')} | `{str(r.get('shape_commit') or '?')[:7]}` | "
                    f"{'green' if r.get('green') else 'red'} | "
                    f"{r.get('passed', 0)}/{r.get('required', 0)} |"
                )
        else:
            lines.append("No scheduled nightly run is recorded yet.")
        lines.append("")
    published = 0
    for kind, title in KIND_TITLES.items():
        rows = sorted(
            ((wid, rec) for wid, rec in shape.items() if rec.get("kind") == kind),
            key=lambda wr: wr[0],
        )
        lines += [f"## {title}", ""]
        if not rows:
            lines += ["No measurement recorded.", ""]
            continue
        lines += [
            "| Workload | Verifier | Baseline median (s) | Shape median (s) | Speed-up |",
            "|---|---|---|---|---|",
        ]
        for wid, rec in rows:
            ok, why = publishable(results, wid, rec)
            if ok:
                base = baseline_median(results, wid, rec)
                assert base is not None
                lines.append(
                    f"| {label(rec, wid)} | pass | {_fmt_s(base)} | "
                    f"{_fmt_s(float(rec['median_s']))} | "
                    f"{float(rec['speedup_vs_refengine']):.1f}x |"
                )
                published += 1
            else:
                lines.append(f"| {label(rec, wid)} | {why} | - | - | - |")
        lines.append("")
    if not published:
        lines += ["No verified measurement is published yet.", ""]
    text = "\n".join(lines)
    if BASELINE_KEY in text.lower() or names_refengine(text):
        raise PageError("the page would name the baseline library (D-13)")
    return text


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--results", type=Path, default=DEFAULT_RESULTS)
    ap.add_argument("--history", type=Path, default=None, help="nightly JSON-lines history")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true", help="exit 1 if --out is not up to date")
    a = ap.parse_args(argv)
    results = json.loads(a.results.read_text())
    history = None
    if a.history is not None:
        history = [
            json.loads(ln)
            for ln in (a.history.read_text().splitlines() if a.history.is_file() else [])
            if ln.strip()
        ]
    try:
        text = render(results, history)
    except PageError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2
    if a.check:
        if not a.out.is_file() or a.out.read_text() != text:
            print(f"{a.out} is out of date; run scripts/gen_performance_page.py", file=sys.stderr)
            return 1
        print(f"{a.out} is up to date")
        return 0
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(text)
    print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
