"""Generate ``docs/EXIT_CODES.md`` from ``shape.cli.exitcodes`` (W1-14).

python scripts/gen_exit_codes.py            # write the document
python scripts/gen_exit_codes.py --check    # exit 1 when it is out of date (make check runs this)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

DEFAULT = Path(__file__).resolve().parents[1] / "docs" / "EXIT_CODES.md"

HEADER = """\
# Exit codes

Status: available.


<!-- Generated by `python scripts/gen_exit_codes.py` from `shape.cli.exitcodes`. Do not edit. -->

Every `shape` command ends with one of the codes below. The classes are the same everywhere:

| Code | Class |
|---|---|
| 0 | ok |
| 1 | a check failed, drift was found, a signature or leak scan failed |
| 2 | bad input: a missing or unreadable file, the wrong kind of file, a bad argument |
| 3 and above | the command's own verdict (a failed certificate, contract or compatibility check) |

Writing a report (`--junit`, `--sarif`, `--json`) never changes a command's exit code, and a
command's `--help` ends with the same table. `shape` itself exits 2 for an argument that does not
parse, and 130 when a scale run is interrupted. See `docs/CLI.md` and `docs/CI.md`.
"""


def render() -> str:
    from shape.cli import exitcodes
    from shape.cli.introspect import core_commands

    out = [HEADER]
    for info in core_commands():
        names = " / ".join(f"`shape {n}`" for n in (info.path, *info.aliases))
        out.append(f"## {names}\n")
        out.append("| Code | Meaning |\n|---|---|")
        for code, meaning in exitcodes.codes(info.path).items():
            out.append(f"| {code} | {meaning} |")
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--check", action="store_true", help="exit 1 when the document is out of date")
    p.add_argument("--output", type=Path, default=DEFAULT, metavar="FILE")
    a = p.parse_args(argv)
    text = render()
    if a.check:
        have = a.output.read_text(encoding="utf-8") if a.output.is_file() else None
        if have != text:
            print(
                f"{a.output} is out of date: run `python scripts/gen_exit_codes.py`",
                file=sys.stderr,
            )
            return 1
        return 0
    a.output.write_text(text, encoding="utf-8")
    print(f"wrote {a.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
