#!/usr/bin/env python3
"""Record the content digests of the packaged domain schemas (``shape_domains/_digests.py``).

A schema listed there was checked against ``generation-schema-v1.json`` when the file was written
(this script refuses to record one that fails), so the host does not check it again at load. The
digest of ``generation-schema-v1.json`` itself is recorded too: when either file changes, the
digests no longer match and the schema is checked again at load, and ``--check`` (run by
``plugins/shape-domains/tests``) fails until this script is run.

    python scripts/update_domain_digests.py          # rewrite
    python scripts/update_domain_digests.py --check  # exit 1 when the file is out of date
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOMAINS = ROOT / "plugins" / "shape-domains" / "src" / "shape_domains"
TARGET = DOMAINS / "_digests.py"
JSON_SCHEMA = ROOT / "src" / "shape" / "schemas" / "generation-schema-v1.json"
HEADER = '''# ruff: noqa: E501
"""Content digests of the packaged domain schemas. Generated by
``scripts/update_domain_digests.py``; do not edit (see ``shape_domains._packaged``)."""

from __future__ import annotations

'''


def render() -> str:
    from shape.generation.schema import GenSchema, schema_problems

    lines = [HEADER, f'JSON_SCHEMA = "{hashlib.sha256(JSON_SCHEMA.read_bytes()).hexdigest()}"\n\n']
    lines.append("SCHEMAS = {\n")
    for path in sorted((DOMAINS / "data").glob("*/schema*.json")):
        content = path.read_bytes()
        document = json.loads(content.decode("utf-8"))
        problems = schema_problems(document)
        if problems:
            raise SystemExit(f"{path}: not a valid generation schema: {problems[:3]}")
        GenSchema.from_dict(document)
        relative = path.relative_to(DOMAINS / "data").as_posix()
        lines.append(f'    "{relative}": "{hashlib.sha256(content).hexdigest()}",\n')
    lines.append("}\n")
    return "".join(lines)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != text:
            print(f"{TARGET} is out of date; run scripts/update_domain_digests.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
