"""The built-ins and the entry point each one registers under (strings only: importing this
module loads no built-in code).

``pyproject.toml`` declares the same table as ``[project.entry-points]``;
``tests/plugins/test_builtins.py`` fails if the two drift apart.
"""

from __future__ import annotations

# (entry-point group, name, "module:Class")
BUILTINS: tuple[tuple[str, str, str], ...] = (
    ("shape.sources", "csv", "shape.builtins.sources:CsvSource"),
    ("shape.sources", "parquet", "shape.builtins.sources:ParquetSource"),
    ("shape.sources", "jsonl", "shape.builtins.sources:JsonlSource"),
    ("shape.sources", "ipc", "shape.builtins.sources:IpcSource"),
    ("shape.sources", "abfss", "shape.builtins.sources:AbfssSource"),
    ("shape.sources", "delta", "shape.builtins.sources:DeltaSource"),
    ("shape.sinks", "csv", "shape.builtins.sinks:CsvSink"),
    ("shape.sinks", "parquet", "shape.builtins.sinks:ParquetSink"),
    ("shape.sinks", "jsonl", "shape.builtins.sinks:JsonlSink"),
    ("shape.sinks", "ipc", "shape.builtins.sinks:IpcSink"),
    ("shape.sinks", "tsv", "shape.builtins.sinks:TsvSink"),
    ("shape.sinks", "sql", "shape.builtins.sinks:SqlSink"),
    ("shape.sinks", "excel", "shape.builtins.sinks:ExcelSink"),
    ("shape.sinks", "delta", "shape.builtins.sinks:DeltaSink"),
    ("shape.emitters", "console", "shape.builtins.emitters:ConsoleEmitter"),
    ("shape.emitters", "file", "shape.builtins.emitters:FileEmitter"),
    ("shape.emitters", "jsonl", "shape.builtins.emitters:JsonlEmitter"),
    ("shape.detectors", "email", "shape.builtins.detectors:EmailDetector"),
    ("shape.detectors", "us_ssn", "shape.builtins.detectors:UsSsnDetector"),
    ("shape.detectors", "phone", "shape.builtins.detectors:PhoneDetector"),
    ("shape.detectors", "ipv4", "shape.builtins.detectors:Ipv4Detector"),
    ("shape.fitters", "auto", "shape.builtins.fitters:AutoFitter"),
    ("shape.strategies", "constant", "shape.builtins.strategies:Constant"),
    ("shape.strategies", "sequence", "shape.builtins.strategies:Sequence"),
    ("shape.strategies", "choice", "shape.builtins.strategies:Choice"),
    ("shape.strategies", "uniform", "shape.builtins.strategies:Uniform"),
    ("shape.strategies", "normal", "shape.builtins.strategies:Normal"),
    ("shape.strategies", "native", "shape.builtins.strategies.providers:Native"),
    ("shape.strategies", "faker", "shape.builtins.strategies.providers:Faker"),
    ("shape.strategies", "formula", "shape.builtins.strategies.formula:Formula"),
    ("shape.strategies", "derived", "shape.builtins.strategies.derived:Derived"),
    ("shape.strategies", "computed", "shape.builtins.strategies.derived:Computed"),
    ("shape.strategies", "address", "shape.builtins.strategies:AddressStrategy"),
    ("shape.strategies", "uuid", "shape.builtins.strategies.basic:Uuid"),
    ("shape.strategies", "weighted_enum", "shape.builtins.strategies.basic:WeightedEnum"),
    ("shape.strategies", "distribution", "shape.builtins.strategies.numeric:Distribution"),
    ("shape.strategies", "empirical", "shape.builtins.strategies.numeric:Empirical"),
    ("shape.strategies", "pattern", "shape.builtins.strategies.text:Pattern"),
    ("shape.strategies", "lookup", "shape.builtins.strategies.linked:Lookup"),
    ("shape.strategies", "conditional", "shape.builtins.strategies.linked:Conditional"),
    ("shape.strategies", "correlated", "shape.builtins.strategies.linked:Correlated"),
    (
        "shape.strategies",
        "reference_data",
        "shape.builtins.strategies.reference_data:ReferenceData",
    ),
    ("shape.strategies", "record_sample", "shape.builtins.strategies.reference_data:RecordSample"),
    ("shape.strategies", "record_field", "shape.builtins.strategies.reference_data:RecordField"),
    ("shape.strategies", "hierarchy", "shape.builtins.strategies.hierarchy:Hierarchy"),
    ("shape.strategies", "hierarchy_field", "shape.builtins.strategies.hierarchy:HierarchyField"),
    ("shape.strategies", "bootstrap", "shape.builtins.strategies.bootstrap:Bootstrap"),
    ("shape.strategies", "temporal", "shape.builtins.strategies.temporal:Temporal"),
    ("shape.strategies", "foreign_key", "shape.builtins.strategies.keys:ForeignKey"),
    (
        "shape.strategies",
        "composite_foreign_key",
        "shape.builtins.strategies.keys:CompositeForeignKey",
    ),
    ("shape.strategies", "composite_fk_field", "shape.builtins.strategies.keys:CompositeFkField"),
    ("shape.strategies", "first_per_parent", "shape.builtins.strategies.groups:FirstPerParent"),
    ("shape.strategies", "scd2", "shape.builtins.strategies.groups:Scd2"),
    ("shape.strategies", "self_referencing", "shape.builtins.strategies.hierarchy:SelfReferencing"),
    ("shape.strategies", "self_ref_field", "shape.builtins.strategies.hierarchy:SelfRefField"),
    ("shape.strategies", "lifecycle", "shape.builtins.strategies.lifecycle:Lifecycle"),
    ("shape.commands", "ctgan", "shape.builtins.ctgan:CtganCommand"),
    ("shape.transforms", "mask", "shape.builtins.transforms:Mask"),
    ("shape.transforms", "star", "shape.builtins.dimensional:StarTransform"),
    ("shape.transforms", "cdm", "shape.builtins.dimensional:CdmTransform"),
    ("shape.distributions", "normal", "shape.builtins.distributions:Normal"),
    ("shape.distributions", "uniform", "shape.builtins.distributions:Uniform"),
    ("shape.distributions", "exponential", "shape.builtins.distributions:Exponential"),
    ("shape.distributions", "lognormal", "shape.builtins.distributions:Lognormal"),
    ("shape.distributions", "log_normal", "shape.builtins.distributions:LogNormalFamily"),
    ("shape.distributions", "pareto", "shape.builtins.distributions:Pareto"),
    ("shape.distributions", "zipf", "shape.builtins.distributions:Zipf"),
    ("shape.distributions", "geometric", "shape.builtins.distributions:Geometric"),
    ("shape.distributions", "poisson", "shape.builtins.distributions:Poisson"),
    ("shape.distributions", "bernoulli", "shape.builtins.distributions:Bernoulli"),
    ("shape.distributions", "gamma", "shape.builtins.distributions:Gamma"),
    ("shape.distributions", "beta", "shape.builtins.distributions:Beta"),
    ("shape.distributions", "weibull", "shape.builtins.distributions:Weibull"),
    ("shape.distributions", "triangular", "shape.builtins.distributions:Triangular"),
    ("shape.distributions", "negative_binomial", "shape.builtins.distributions:NegativeBinomial"),
    ("shape.distributions", "power_law_cutoff", "shape.builtins.distributions:PowerLawCutoff"),
    ("shape.distributions", "mixture", "shape.builtins.distributions:Mixture"),
    ("shape.distributions", "truncated", "shape.builtins.distributions:Truncated"),
    ("shape.distributions", "histogram", "shape.builtins.distributions:Histogram"),
    ("shape.calendars", "us_federal", "shape.builtins.calendars:UsFederalCalendar"),
    ("shape.calendars", "us_retail", "shape.builtins.calendars:UsRetailCalendar"),
    ("shape.calendars", "composite", "shape.builtins.calendars:CompositeCalendar"),
    ("shape.chaos", "schema", "shape.builtins.chaos:SchemaChaos"),
    ("shape.chaos", "value", "shape.builtins.chaos:ValueChaos"),
    ("shape.chaos", "file", "shape.builtins.chaos:FileChaos"),
    ("shape.chaos", "referential", "shape.builtins.chaos:ReferentialChaos"),
    ("shape.chaos", "temporal", "shape.builtins.chaos:TemporalChaos"),
    ("shape.chaos", "volume", "shape.builtins.chaos:VolumeChaos"),
    ("shape.reports", "json", "shape.builtins.reports:JsonReport"),
    ("shape.reports", "md", "shape.builtins.reports:MarkdownReport"),
    ("shape.reports", "html", "shape.builtins.reports:HtmlReport"),
)
