-- Generated by Shape v@VERSION@

-- ============================================================
-- Table: t
-- ============================================================

IF OBJECT_ID('[app].[t]', 'U') IS NOT NULL
    DROP TABLE [app].[t];
GO
CREATE TABLE [app].[t] (
    [id]                           BIGINT               NOT NULL,
    [name]                         NVARCHAR(40)         NULL,
    [amount]                       DECIMAL(10,2)        NULL,
    [created]                      DATETIME2            NULL,
    CONSTRAINT [PK_t] PRIMARY KEY ([id])
);
GO

INSERT INTO [app].[t] ([id], [name], [amount], [created])
VALUES
  (1, N'a', 1.50, N'2026-01-02 03:04:05'),
  (2, N'b''c', 2.00, N'2026-01-02 03:04:05'),
  (3, NULL, NULL, N'2026-01-02 03:04:05');
GO

