-- Generated by Shape v@VERSION@

-- ============================================================
-- Table: t
-- ============================================================

DROP TABLE IF EXISTS "app"."t" CASCADE;

CREATE TABLE "app"."t" (
    "id"                           BIGINT               NOT NULL,
    "name"                         VARCHAR(40)          NULL,
    "amount"                       NUMERIC(10,2)        NULL,
    "created"                      TIMESTAMP            NULL,
    CONSTRAINT "PK_t" PRIMARY KEY ("id")
);

INSERT INTO "app"."t" ("id", "name", "amount", "created")
VALUES
  (1, 'a', 1.50, '2026-01-02 03:04:05'),
  (2, 'b''c', 2.00, '2026-01-02 03:04:05'),
  (3, NULL, NULL, '2026-01-02 03:04:05');

