-- Generated by Shape v@VERSION@

-- ============================================================
-- Table: t
-- ============================================================

DROP TABLE IF EXISTS [app].[t];
GO
-- NOTE: Fabric Warehouse does not enforce PRIMARY KEY constraints;
-- [id] is the logical primary key.
CREATE TABLE [app].[t] (
    [id]                           BIGINT               NOT NULL,
    [name]                         VARCHAR(40)          NULL,
    [amount]                       DECIMAL(10,2)        NULL,
    [created]                      DATETIME2(6)         NULL
);
GO

INSERT INTO [app].[t] ([id], [name], [amount], [created])
VALUES
  (1, 'a', 1.50, '2026-01-02 03:04:05'),
  (2, 'b''c', 2.00, '2026-01-02 03:04:05'),
  (3, NULL, NULL, '2026-01-02 03:04:05');
GO

