"""Type stub of the native kernel (rust/shape-kernel). Twin: shape.kernel.reference."""

from typing import Any

NAME: str

def version() -> str: ...
def roundtrip_batch(batch: Any) -> Any: ...
def buffer_addresses(batch: Any) -> list[int]: ...
def hash_array(array: Any, seed: int = 0) -> Any: ...
def set_threads(n: int = 0) -> int: ...
def num_rows(batch: Any) -> int: ...

class Hll:
    def __init__(self, p: int = 14) -> None: ...
    @property
    def p(self) -> int: ...
    def update_hash(self, h: int) -> None: ...
    def update_array(self, array: Any) -> None: ...
    def update_hashes(self, hashes: Any) -> None: ...
    def merge(self, other: Hll) -> None: ...
    def estimate(self) -> float: ...
    def registers(self) -> bytes: ...
    @staticmethod
    def from_registers(p: int, registers: bytes) -> Hll: ...

class Kll:
    def __init__(self, k: int = 200) -> None: ...
    @property
    def k(self) -> int: ...
    @property
    def n(self) -> int: ...
    def update(self, x: float) -> None: ...
    def update_values(self, values: Any) -> None: ...
    def merge(self, other: Kll) -> None: ...
    def quantile(self, q: float) -> float | None: ...
    def levels(self) -> list[list[float]]: ...

class SpaceSaving:
    def __init__(self, capacity: int = 64) -> None: ...
    @property
    def capacity(self) -> int: ...
    @property
    def n(self) -> int: ...
    def __len__(self) -> int: ...
    def update(self, key: int, n: int = 1) -> None: ...
    def update_array(self, array: Any) -> None: ...
    def update_keys(self, keys: Any) -> None: ...
    def merge(self, other: SpaceSaving) -> None: ...
    def top(self) -> list[tuple[int, int, int]]: ...

class ProfileState:
    def __init__(self, schema: Any, mode: str = "exact") -> None: ...
    @property
    def rows(self) -> int: ...
    @property
    def mode(self) -> str: ...
    def update(self, batch: Any) -> None: ...
    def merge(self, other: ProfileState) -> None: ...
    def finalize(self, top_n: int = 500) -> dict[str, Any]: ...
