"""Type stub of the native kernel (rust/shape-kernel). Twin: shape.kernel.reference."""

from typing import Any

NAME: str

def version() -> str: ...
def roundtrip_batch(batch: Any) -> Any: ...
def buffer_addresses(batch: Any) -> list[int]: ...
def num_rows(batch: Any) -> int: ...
