"""Type stub of the native kernel (rust/shape-kernel). Twin: shape.kernel.reference."""

from typing import Any

NAME: str

def version() -> str: ...
def roundtrip_batch(batch: Any) -> Any: ...
def buffer_addresses(batch: Any) -> list[int]: ...
def hash_array(array: Any, seed: int = 0) -> Any: ...
def fit_distribution(sample: Any, full: Any | None = None) -> dict[str, Any]: ...
def numpy_loops_mode() -> str: ...
def set_threads(n: int = 0) -> int: ...
def num_rows(batch: Any) -> int: ...
def philox_words(k0: int, k1: int, row_start: int, n_rows: int, per_row: int = 1) -> Any: ...
def philox_uniform(
    k0: int, k1: int, row_start: int, n_rows: int, per_row: int = 1, slot: int = 0
) -> Any: ...
def philox_normal(
    k0: int, k1: int, row_start: int, n_rows: int, per_row: int = 2, slot: int = 0
) -> Any: ...
def alias_build(weights: Any) -> tuple[Any, Any]: ...
def alias_sample(
    prob: Any,
    alias: Any,
    k0: int,
    k1: int,
    row_start: int,
    n_rows: int,
    per_row: int = 2,
    slot: int = 0,
) -> Any: ...
def pool_take(pool: Any, indices: Any) -> Any: ...
def template_strings(
    literals: list[str], slots: list[tuple[int, int]], columns: list[Any], n_rows: int
) -> Any: ...
def join_strings(columns: list[Any], sep: str, skip_nulls: bool = False) -> Any: ...
def string_case(array: Any, mode: str) -> Any: ...
def uuid4_strings(k0: int, k1: int, row_start: int, n_rows: int) -> Any: ...
def random_strings(
    k0: int, k1: int, row_start: int, n_rows: int, length: int, alphabet: str
) -> Any: ...
def day_weights(
    start_day: int,
    n_days: int,
    month_weights: list[float],
    dow_weights: list[float],
    per_bucket: bool = True,
) -> Any: ...
def hour_weights_peaks(peaks: list[float], std: float) -> Any: ...
def temporal_sample(
    day_weights: Any,
    hour_weights: Any,
    start_day: int,
    k0: int,
    k1: int,
    row_start: int,
    n_rows: int,
    whole_seconds: bool = False,
) -> Any: ...
def first_flags(codes: Any) -> Any: ...
def dense_rows(keys: Any, start: int, size: int) -> Any: ...
def group_sums(keys: Any, values: Any, start: int, size: int) -> tuple[Any, Any]: ...
def group_order(codes: Any, keys: Any) -> tuple[Any, Any, Any]: ...
def scd2_offsets(codes: Any, total_days: int, min_gap: int, k0: int, k1: int) -> Any: ...
def cap_per_parent(indices: Any, pool: int, max_per_parent: int, k0: int, k1: int) -> Any: ...

class Hll:
    def __init__(self, p: int = 14) -> None: ...
    @property
    def p(self) -> int: ...
    def update_hash(self, h: int) -> None: ...
    def update_array(self, array: Any) -> None: ...
    def update_hashes(self, hashes: Any) -> None: ...
    def merge(self, other: Hll) -> None: ...
    def estimate(self) -> float: ...
    def registers(self) -> bytes: ...
    @staticmethod
    def from_registers(p: int, registers: bytes) -> Hll: ...

class Kll:
    def __init__(self, k: int = 200) -> None: ...
    @property
    def k(self) -> int: ...
    @property
    def n(self) -> int: ...
    def update(self, x: float) -> None: ...
    def update_values(self, values: Any) -> None: ...
    def merge(self, other: Kll) -> None: ...
    def quantile(self, q: float) -> float | None: ...
    def levels(self) -> list[list[float]]: ...

class SpaceSaving:
    def __init__(self, capacity: int = 64) -> None: ...
    @property
    def capacity(self) -> int: ...
    @property
    def n(self) -> int: ...
    def __len__(self) -> int: ...
    def update(self, key: int, n: int = 1) -> None: ...
    def update_array(self, array: Any) -> None: ...
    def update_keys(self, keys: Any) -> None: ...
    def merge(self, other: SpaceSaving) -> None: ...
    def top(self) -> list[tuple[int, int, int]]: ...

class ProfileState:
    def __init__(self, schema: Any, mode: str = "exact") -> None: ...
    @property
    def rows(self) -> int: ...
    @property
    def mode(self) -> str: ...
    def update(self, batch: Any) -> None: ...
    def merge(self, other: ProfileState) -> None: ...
    def finalize(self, top_n: int = 500) -> dict[str, Any]: ...
    def snapshot(self) -> bytes: ...
    @staticmethod
    def from_snapshot(schema: Any, data: bytes) -> ProfileState: ...
