"""Common Data Model folder output: ``model.json`` plus one data file per entity.

The folder follows the CDM ``model.json`` format that Fabric, Dataverse, Power Platform and Azure
Data Lake Storage CDM connectors read: ``<Entity>/<Entity>.csv`` (or ``.parquet``) for each table,
and a manifest that lists every entity's attributes and data partition.
"""

from __future__ import annotations

import json
import re
from collections.abc import Mapping
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pyarrow as pa  # type: ignore[import-untyped]

from shape.dimensional.files import FORMATS, write_table


def entity_name(table: str, names: Mapping[str, str] | None = None) -> str:
    """The CDM entity for ``table``: its entry in ``names``, else the table name in PascalCase
    (``order_line`` becomes ``OrderLine``)."""
    if names and table in names:
        return names[table]
    return "".join(part.capitalize() for part in re.split(r"[_\s]+", table))


def cdm_type(t: pa.DataType) -> str:
    """The CDM ``dataType`` of an Arrow type."""
    if pa.types.is_integer(t):
        return "int64"
    if pa.types.is_floating(t):
        return "double"
    if pa.types.is_decimal(t):
        return "decimal"
    if pa.types.is_boolean(t):
        return "boolean"
    if pa.types.is_timestamp(t):
        return "dateTime"
    if pa.types.is_date(t):
        return "date"
    if pa.types.is_time(t):
        return "time"
    return "string"


def _partition(entity: str, fmt: str) -> dict[str, Any]:
    location = f"{entity}/{entity}.{fmt}"
    if fmt == "parquet":
        settings: dict[str, Any] = {"$type": "ParquetFormatSettings"}
    else:
        settings = {
            "$type": "CsvFormatSettings",
            "columnHeaders": True,
            "delimiter": ",",
            "quoteStyle": "QuoteStyle.Csv",
            "encoding": "UTF-8",
        }
    return {"name": f"{entity}-0", "location": location, "fileFormatSettings": settings}


def _entities(
    tables: Mapping[str, pa.Table], names: Mapping[str, str] | None
) -> dict[str, tuple[str, pa.Table]]:
    out: dict[str, tuple[str, pa.Table]] = {}
    seen: dict[str, str] = {}
    for table, data in tables.items():
        entity = entity_name(table, names)
        if entity in seen:
            raise ValueError(
                f"tables {seen[entity]!r} and {table!r} both become the entity {entity!r}; "
                f"name one of them in the entity map"
            )
        seen[entity] = table
        out[table] = (entity, data)
    return out


def model_document(
    tables: Mapping[str, pa.Table],
    model_name: str,
    names: Mapping[str, str] | None = None,
    fmt: str = "csv",
    modified: str | None = None,
) -> dict[str, Any]:
    """The ``model.json`` document. ``modified`` (default: now, UTC) is its ``modifiedTime``."""
    if fmt not in FORMATS:
        raise ValueError(f"unknown format {fmt!r} (csv, parquet)")
    entities = [
        {
            "name": entity,
            "$type": "LocalEntity",
            "description": f"Generated by Shape. Source table: {table}",
            "attributes": [{"name": f.name, "dataType": cdm_type(f.type)} for f in data.schema],
            "partitions": [_partition(entity, fmt)],
        }
        for table, (entity, data) in _entities(tables, names).items()
    ]
    return {
        "name": model_name,
        "description": "Generated by Shape (sqllocks-shape)",
        "version": "1.0",
        "culture": "en-US",
        "modifiedTime": modified or datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "application": "Shape by SQLLocks",
        "entities": entities,
    }


def write_cdm_folder(
    tables: Mapping[str, pa.Table],
    out_dir: str | Path,
    model_name: str,
    names: Mapping[str, str] | None = None,
    fmt: str = "csv",
    modified: str | None = None,
) -> list[Path]:
    """Write the CDM folder; returns the data files, then ``model.json``."""
    document = model_document(tables, model_name, names, fmt, modified)
    root = Path(out_dir)
    root.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for entity, data in _entities(tables, names).values():
        folder = root / entity
        folder.mkdir(exist_ok=True)
        path = folder / f"{entity}.{fmt}"
        write_table(data, path, fmt)
        written.append(path)
    model = root / "model.json"
    model.write_text(json.dumps(document, indent=2), encoding="utf-8")
    written.append(model)
    return written
