"""Daily batches: each batch is its own new rows, and its foreign keys reach every earlier batch.

A batch generator is told how many new rows each table gets per batch (``customer=300``,
``order=4000``). Batch ``i`` (batch 0 is the start date) is generated by an engine whose row
counts are the totals so far, ``(i + 1) x rows_per_batch``, keeping the last ``rows_per_batch`` rows
of each table. So

* **keys are stable**: row ``k`` of a table is the same row in every batch, so a sequence or
  pattern key (``C{seq:9}``) never changes and a later batch can name an earlier batch's key;
* **foreign keys reach back**: a child row draws its parent from every parent row that exists
  after the batch (this batch's and every earlier batch's), so every order points at a real
  customer;
* **a batch is regenerable alone**: it depends only on the schema, the seed, the rows per batch
  and its index, never on files from other batches, so the same batch is the same bytes whenever
  and wherever it runs (a daily job and a backfill agree).

A table the batch does not list (a reference table such as ``store``) keeps the schema's scale
count in every batch and is not part of the batch. A schema with a post-pass (computed columns,
business rules, correlated columns) generates the whole running total of a batch's tables and
keeps the last rows, because those passes need whole tables; any other schema generates just the
rows of the batch, whatever the total.
"""

from __future__ import annotations

import datetime as dt
from collections.abc import Mapping
from dataclasses import dataclass, field

import numpy as np
import pyarrow as pa  # type: ignore[import-untyped]

from shape.generation.engine import Engine
from shape.generation.output import needs_post_pass
from shape.generation.schema import GenSchema
from shape.io.landing import parse_date


@dataclass(frozen=True)
class BatchResult:
    """One batch: the new rows of each listed table.

    ``row_ranges[table]`` is ``(first, stop)``: the batch's rows are rows ``first .. stop - 1`` of
    the table as it exists after this batch, which holds ``stop`` rows in all (``totals``).
    """

    batch_index: int
    batch_date: dt.date
    tables: dict[str, pa.Table]
    row_ranges: dict[str, tuple[int, int]]
    totals: dict[str, int] = field(default_factory=dict)


class BatchGenerator:
    """Generates batch ``i`` of a schema; see the module docstring.

    Args:
        schema: A generation schema.
        rows_per_batch: New rows per batch for each table that is part of a batch.
        start_date: The date of batch 0.
        seed: Overrides the schema's seed.
        scale: A scale preset for the tables the batch does not list.
        date_columns: ``{"order": "order_date"}``: a date or timestamp column set to the batch
            date (a timestamp keeps its time of day), so a day's rows are dated that day.
    """

    def __init__(
        self,
        schema: GenSchema,
        rows_per_batch: Mapping[str, int],
        *,
        start_date: str | dt.date,
        seed: int | None = None,
        scale: str | None = None,
        date_columns: Mapping[str, str] | None = None,
    ) -> None:
        if not rows_per_batch:
            raise ValueError("name the tables of a batch and their new rows: TABLE=N")
        for name, n in rows_per_batch.items():
            if name not in schema.tables:
                raise ValueError(
                    f"table {name!r} is not in the schema ({', '.join(schema.tables)})"
                )
            if n < 1:
                raise ValueError(f"rows per batch of {name!r} must be at least 1, got {n}")
        for name, column in (date_columns or {}).items():
            if name not in rows_per_batch:
                raise ValueError(f"date column given for {name!r}, which is not part of a batch")
            if column not in schema.tables[name].columns:
                raise ValueError(f"table {name!r} has no column {column!r}")
        self.schema = schema
        self.rows_per_batch = dict(rows_per_batch)
        self.start_date = parse_date(start_date)
        self.seed = seed
        self.scale = scale
        self.date_columns = dict(date_columns or {})
        self._post_pass = needs_post_pass(schema)

    def index_of(self, batch_date: str | dt.date) -> int:
        """The batch index of a date (days since ``start_date``)."""
        index = (parse_date(batch_date) - self.start_date).days
        if index < 0:
            raise ValueError(f"batch date {batch_date} is before the start date {self.start_date}")
        return index

    def generate(self, batch: int | str | dt.date) -> BatchResult:
        """The batch with this index, or on this date."""
        index = batch if isinstance(batch, int) else self.index_of(batch)
        if index < 0:
            raise ValueError("a batch index is 0 or more")
        totals = {t: n * (index + 1) for t, n in self.rows_per_batch.items()}
        engine = Engine(self.schema, scale=self.scale, seed=self.seed, row_counts=totals)
        ranges = {t: (n * index, n * (index + 1)) for t, n in self.rows_per_batch.items()}
        tables: dict[str, pa.Table] = {}
        if self._post_pass:
            whole = engine.generate().tables
            for name, (first, stop) in ranges.items():
                tables[name] = whole[name].slice(first, stop - first)
        else:
            engine.schema.validate_or_raise()
            for name, (first, stop) in ranges.items():
                chunk = engine.generate_chunk(name, first, stop - first)
                tables[name] = pa.Table.from_batches([chunk])
        day = self.start_date + dt.timedelta(days=index)
        for name, column in self.date_columns.items():
            tables[name] = _stamp(tables[name], column, day)
        return BatchResult(index, day, tables, ranges, totals)


def _stamp(table: pa.Table, column: str, day: dt.date) -> pa.Table:
    """``table`` with ``column`` on ``day`` (a timestamp keeps its time of day)."""
    i = table.schema.get_field_index(column)
    col = table.column(i).combine_chunks()
    typ = col.type
    if pa.types.is_date(typ):
        values = pa.array([day] * len(col), type=typ, mask=col.is_null().to_numpy(False))
    elif pa.types.is_timestamp(typ):
        raw = np.array(col.cast(pa.timestamp("ns")).fill_null(0).to_numpy(zero_copy_only=False))
        raw = raw.astype("datetime64[ns]")
        shifted = np.datetime64(day.isoformat(), "ns") + (raw - raw.astype("datetime64[D]"))
        values = pa.array(shifted, type=pa.timestamp("ns"), mask=col.is_null().to_numpy(False))
        values = values.cast(typ)
    else:
        raise ValueError(f"column {column!r} is {typ}, not a date or timestamp")
    return table.set_column(i, table.schema.field(i), values)


__all__ = ["BatchGenerator", "BatchResult"]
